.TH "AboutDialog" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AboutDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AboutDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~AboutDialog\fP ()"
.br
.ti -1c
.RI "void \fBSetModel\fP (const \fBUI\fP *model)"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBOnButtonBoxAccepted\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< Ui_AboutDialog > \fB_dlg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'About' dialog box 
.PP
Definition at line 26 of file AboutDialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AboutDialog::AboutDialog (QWidget *parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line 19 of file AboutDialog\&.cc\&.
.PP
References _dlg\&.
.PP
.nf
22 : QDialog(parent), _dlg(new Ui_AboutDialog)
23 {
24         _dlg->setupUi(this);
25         // prevent resizing
26         setFixedSize(size());
27 }
.fi
.SS "AboutDialog::~AboutDialog ()"

.PP
Definition at line 31 of file AboutDialog\&.cc\&.
.PP
.nf
32 {
33 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void AboutDialog::OnButtonBoxAccepted ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 50 of file AboutDialog\&.cc\&.
.PP
.nf
51 {
52         close();
53 }
.fi
.SS "void AboutDialog::SetModel (const \fBUI\fP *model)"

.PP
Definition at line 38 of file AboutDialog\&.cc\&.
.PP
References _dlg, and UI::ApplicationVersion()\&.
.PP
.nf
41 {
42         // replace %VERSION% with app version or unspecified string
43         _dlg->label_appversion->setText(model ? model->ApplicationVersion() : "unspecified");
44         
45 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "std::unique_ptr<Ui_AboutDialog> AboutDialog::_dlg\fC [private]\fP"
Designed form; nothing we can do about naming convention 
.PP
Definition at line 33 of file AboutDialog\&.h\&.
.PP
Referenced by AboutDialog(), and SetModel()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
