.TH "Allocator.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Allocator.h \- 
.PP
Memory Allocation tracking for the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'definitions\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMALLOC\fP(size)   malloc(size)"
.br
.ti -1c
.RI "#define \fBREALLOC\fP(ptr, size)   realloc(ptr, size)"
.br
.ti -1c
.RI "#define \fBFREE\fP(varname)   free(varname)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Memory Allocation tracking for the application\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBAllocator\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define FREE(varname)   free(varname)"

.PP
Definition at line 360 of file Allocator\&.h\&.
.PP
Referenced by IrcParser::Handle005(), IrcParser::Handle332(), IrcParser::Handle333(), IrcParser::Handle353(), IrcParser::Handle366(), IrcParser::Handle432(), IrcParser::Handle433(), IrcParser::HandleCap(), IrcParser::HandleInvite(), IrcParser::HandleKick(), IrcParser::HandleKill(), IrcParser::HandleMode(), IrcParser::HandleNotice(), IrcParser::HandlePrivmsg(), IrcParser::HandleTopic(), and ObjectPool< IrcUser >::TotalErase()\&.
.SS "#define MALLOC(size)   malloc(size)"

.PP
Definition at line 358 of file Allocator\&.h\&.
.PP
Referenced by Runtime::GetObjectFromModule(), ObjectPool< IrcUser >::GrandAlloc(), IrcParser::Handle005(), Configuration::Load(), and IrcParser::ParseParameters()\&.
.SS "#define REALLOC(ptr, size)   realloc(ptr, size)"

.PP
Definition at line 359 of file Allocator\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
