app.h
NAME
app.h -
Application initialization, execution, and cleanup routines.
SYNOPSIS
#include <api/types.h>
#include <api/char_helper.h>
Functions
void app_exec ()
void app_init (int32_t argc, char **argv)
void app_stop ()
bool parse_commandline (int32_t argc, char **argv)
Detailed Description
Application initialization, execution, and cleanup routines.
Author:
James Warren
Definition in file app.h.
Function Documentation
void app_exec ()
Executes the main processing loop of the application. Does not return until the application window is closed.
Executed only after app_init() has returned, and is wrapped in a dedicated exception handler.
Definition at line 34 of file app.cc.
References Runtime::Config(), Debug, Log::Flush(), get_ms_time(), Info, Configuration::library, LOG, Runtime::Logger(), runtime, and Configuration::ui.
Referenced by main().
{
        // all classes are safe to use at this point, so we can do ANYTHING now
        uint64_t start_time = get_ms_time();
        uint64_t end_time;
        
        if ( runtime.Config()->ui.library.pfunc_spawn_interface() == 0 )
        {
                LOG(ELogLevel::Debug) << "spawn_interface() executed successfully; handing control to GUI library\n";
                runtime.Config()->ui.library.pfunc_process_interface();
                runtime.Config()->ui.library.pfunc_destroy_interface();
        }
        LOG(ELogLevel::Debug) << "GUI library returned control\n";
        end_time = get_ms_time();
        LOG(ELogLevel::Info) << "The application ran for "
                << (end_time - start_time) / 1000 << " seconds\n";
        // ensure log entries are written
        runtime.Logger()->Flush();
}
void app_init (int32_targc, char **argv)
Initializes the application; the command line arguments from main are passed into the function, where they are processed in parse_commandline().
Is wrapped in a dedicated exception handler.
Parameters:
argc The number of arguments within argv
argv An array of pointers to arguments
Definition at line 64 of file app.cc.
References Runtime::Config(), Debug, get_current_binary_path(), get_ms_time(), Info, Configuration::Load(), LOG, Runtime::Logger(), Log::Open(), parse_commandline(), runtime, Log::SetLogLevel(), and unlink.
Referenced by main().
{
        uint64_t start_time = get_ms_time();
        uint64_t end_time;
#if defined(_WIN32)
        /* very first thing; ensure our current directory is that of the binary
         * if we're on Windows; in Visual Studio debugging, this is not the case
         * automatically! */
        wchar_t cur_path[MAX_PATH];
        get_current_binary_path(cur_path, _countof(cur_path));
        SetCurrentDirectory(cur_path);
#endif
#if defined(USING_MEMORY_DEBUGGING)
        // delete all the old log files, if present.
        unlink(MEM_LEAK_LOG_NAME);
#endif
        /* since the runtime classes are now accessible, we can actually use
         * them all immediately; so we can log from the outset, at a cost of
         * keeping the 'global classes' constructors performing minimal
         * activity. */
        runtime.Logger()->Open("app.log");
        // default to all events logged, override in the config if desired
        runtime.Logger()->SetLogLevel(ELogLevel::Debug);
        runtime.Config()->Load();
        /* parse the command line, assign overrides before other objects are
         * created. This way command line takes precedence over config file. */
        parse_commandline(argc, argv);
#if defined(_WIN32)
        {
                RECT work_area;
                if ( SystemParametersInfo(SPI_GETWORKAREA, 0, &work_area, 0) )
                {
                        HWND hwnd = GetConsoleWindow();
                        RECT wnd_rect;
                        GetWindowRect(hwnd, &wnd_rect);
                        // relocate the console window
#if 0 // Bottom-Left
                        work_area.top = work_area.bottom - (wnd_rect.bottom - wnd_rect.top);
#endif
#if 0 // Bottom-Right
                        work_area.top = work_area.bottom - (wnd_rect.bottom - wnd_rect.top);
                        work_area.left = work_area.right - (wnd_rect.right - wnd_rect.left);
#endif
#if 1 // Top-Left
#endif
#if 0 // Top-Right
                        work_area.left = work_area.right - (wnd_rect.right - wnd_rect.left);
#endif
                        //SetWindowPos(hwnd, NULL, work_area.left, work_area.top, 0, 0, SWP_NOSIZE);
                        MoveWindow(hwnd, work_area.left, work_area.top, 800, 500, true);
                }
                /* intercept ctrl+c - mostly useful for debugging - don't care
                 * if we fail */
                //SetConsoleCtrlHandler((PHANDLER_ROUTINE)sig_handler, TRUE);
        }
#endif
        // have you been modifying anything..
#if defined(USING_MEMORY_DEBUGGING)
        assert(runtime.Memory() != nullptr);
#endif
        //assert(runtime.Pools() != nullptr);
        assert(runtime.Logger() != nullptr);
        //assert(runtime.Config() != nullptr);
        /*runtime.Config()->Load();
        if ( !runtime.Config()->display.show_terminal )
        {
#if defined(_WIN32)
                HWND console_wnd = GetConsoleWindow();
                ShowWindow(console_wnd, SW_HIDE);
#else
                std::cout << "'show_terminal' setting ignored for this operating system\n";
#endif
        }
        */
        
        end_time = get_ms_time();
        std::cout << "Application startup completed in " << (end_time - start_time) << "ms\n";
        LOG(ELogLevel::Info) << "Application startup completed in " << (end_time - start_time) << "ms\n";
}
void app_stop ()
Cleans up any resources still loaded by the application.
Executed only after app_exec() has returned, and is wrapped in a dedicated exception handler.
Definition at line 177 of file app.cc.
References Log::Flush(), Runtime::Logger(), and runtime.
Referenced by main().
{
        //runtime.Config()->Unload();
        runtime.Logger()->Flush();
}
bool parse_commandline (int32_targc, char **argv)
Parameters:
argc The number of arguments within argv
argv An array of pointers to arguments
Return values:
false if an invalid option was passed in
true if all options were processed, or none to do
Definition at line 186 of file app.cc.
References getopt().
Referenced by app_init().
{
        char getopt_str[] = "c:h";
        int32_t opt = getopt(argc, argv, getopt_str);
        //app_config_writer cfg_writer;
        while ( opt != -1 )
        {
                switch ( opt )
                {
                case 'c':
                        //cfg_writer.Set_Path_Configuration(optarg);
                        break;
                case 'g':
                        // do nothing beyond text event generation
                        //cfg_writer.Set_GenerateTextEvents();
                        return true;
                case 'h':
                default:
                        //display_usage(argv[0], opt);
                        return false;
                }
                opt = getopt(argc, argv, getopt_str);
        }
        // nothing invalid or help, so startup can proceed
        return true;
}
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.