.TH "rfc2812.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rfc2812.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <api/char_helper\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRFC2812_MAX_NICKNAME_LENGTH\fP   9"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RFC2812_MAX_NICKNAME_LENGTH   9"

.PP
Definition at line 18 of file bak/rfc2812\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
