.TH "config_structs.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_structs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <api/char_helper\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBconfig_profile\fP"
.br
.ti -1c
.RI "struct \fBconfig_server\fP"
.br
.ti -1c
.RI "struct \fBconfig_network\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
