nethelper.cc
NAME
nethelper.cc -
SYNOPSIS
#include <string>
#include <WS2tcpip.h>
#include <in6addr.h>
#include <api/char_helper.h>
#include <api/utils.h>
#include <api/Terminal.h>
#include <api/Runtime.h>
#include <api/Log.h>
#include 'nethelper.h'
Functions
int32_t host_to_ipv4 (const char *hostname, int32_t index, char *ip_dest, uint32_t dest_size)
bool ipv4_to_host (const char *ipv4_address, char *host_dest, uint32_t dest_size)
bool is_ip_address (const char *data)
void net_cleanup ()
bool net_startup (uint16_t winsock_version)
Function Documentation
int32_t host_to_ipv4 (const char *hostname, int32_tindex, char *ip_dest, uint32_tdest_size)
Validates and looks up the supplied hostname. On success, the first IP address (or overriden by index) is copied into ip_dest. This allows a different address to be returned in case the first one tried is unreachable.
If the index is out of range, an error is generated.
Useful on systems that have a lookup cache, otherwise, you'll be doing a fresh lookup every time you need to use an alternate address - hopefully this shouldn't come up too often anyway.
Example usage:
       char buf[NI_MAXHOST];
       int num_res;
       char ip_dest[INET_ADDRSTRLEN];
       // fgets into buf
       if (( num_res = host_to_ipv4(buf, -1, ip_dest, sizeof(ip_dest))) >= 0 )
       {
        printf("Primary Index: %s\n", ip_dest);
        // do work on address, otherwise enter loop
        for ( int i = 1; i < num_res; i++ )
        {
                host_to_ipv4(buf, i, ip_dest, sizeof(ip_dest));
                printf("Secondary Index [%i]: %s\n", i, ip_dest);
                // attempt work on alternate address
        }
       }
// Example Output::
//
// google.com
// Primary Index: 173.194.34.65
// Secondary Index [1]: 173.194.34.68
// Secondary Index [2]: 173.194.34.70
// Secondary Index [3]: 173.194.34.69
// Secondary Index [4]: 173.194.34.66
// Secondary Index [5]: 173.194.34.64
// Secondary Index [6]: 173.194.34.78
// Secondary Index [7]: 173.194.34.67
// Secondary Index [8]: 173.194.34.73
// Secondary Index [9]: 173.194.34.72
// Secondary Index [10]: 173.194.34.71
*
Parameters:
hostname The hostname to lookup
index The 0-based index within the results to return
ip_dest The buffer to copy the IP address to
dest_size The size of ip_dest
Returns:
The function returns the number of addresses found for the specified hostname.
-1 is returned if the input data is invalid; 0 is returned if the data was valid, but there were no results (this is abnormal).
See Also:
ipv4_to_host
Definition at line 40 of file bak/nethelper.cc.
References Error, fg_green(), fg_red(), Info, LOG, and strlcpy().
{
        struct addrinfo hints = { 0 };
        struct addrinfo* result = NULL;
        struct addrinfo* rp = NULL;
        int32_t ret = 0;
        int32_t res;
        // obtain address(es) matching host
        // IPv4 only
        hints.ai_family = AF_INET;
        if (( res = getaddrinfo(hostname, NULL, &hints, &result)) != 0 )
        {
                LOG(LL_Error) << fg_red << "Error " << res
                        << " (" << gai_strerror(res)
                        << ") looking up" << hostname
                        << "\n";
                ret--;
        }
        else
        {
                for ( rp = result; rp != NULL; rp = rp->ai_next, ++ret )
                {
                        struct sockaddr_in *a = (struct sockaddr_in*)rp->ai_addr;
                        if ( index < 0 )
                        {
                                // no index specified; copy the first result
                                strlcpy(ip_dest, (char*)inet_ntoa(a->sin_addr), dest_size);
                                index = 0;
                        }
                        else if ( index == ret )
                        {
                                // copy the specified index
                                strlcpy(ip_dest, (char*)inet_ntoa(a->sin_addr), dest_size);
                        }
                }
                if ( index >= ret )
                {
                        LOG(LL_Error) << fg_red << "The specified index '"
                                << index << "' is out of range ("
                                << ret << ")\n";
                }
                else
                {
                        LOG(LL_Info) << fg_green << hostname << " resolved to "
                                << ip_dest << "\n";
                }
        }
        if ( result != NULL )
                freeaddrinfo(result);
        // -1 on error
        // 0 is abnormal (lookup succeeded, but no results)
        // >=1 if 1 or more results
        return ret;
}
bool ipv4_to_host (const char *ipv4_address, char *host_dest, uint32_tdest_size)
Performs a reverse lookup on the input ipv4_address.
e.g. 173.194.34.67 reverse lookup: lhr14s19-in-f3.1e100.net
Parameters:
ipv4_address The IPv4 address to reverse-lookup
host_dest The destination buffer to copy the hostname to
dest_size The size of host_dest
Returns:
The function returns true if the IP address is valid, and a lookup is performed. If the name could not be found, true is still returned; only on an error is false returned.
See Also:
host_to_ipv4
Definition at line 112 of file bak/nethelper.cc.
References Error, fg_red(), Info, and LOG.
{
        struct addrinfo hints = { 0 };
        struct addrinfo* result = NULL;
        int32_t res;
        // IPv4 only
        hints.ai_family = AF_INET;
        if (( res = getaddrinfo(ipv4_address, NULL, &hints, &result)) != 0 )
        {
                LOG(LL_Error) << "Error " << res
                        << " (" << gai_strerror(res)
                        << ") looking up" << ipv4_address
                        << "\n";
                return false;
        }
        /* we don't want to fail if the name cannot be looked up, so supply no
         * flags; if the lookup does not resolve, */
        if (( res = getnameinfo(result->ai_addr, result->ai_addrlen, host_dest, dest_size, NULL, 0, 0)) != 0 )
        {
                LOG(LL_Error) << "Error " << res
                        << " (" << gai_strerror(res)
                        << ") looking up" << ipv4_address
                        << "\n";
                freeaddrinfo(result);
                return false;
        }
        LOG(LL_Info) << ipv4_address << " resolved to " << host_dest << "\n";
        freeaddrinfo(result);
        return true;
}
bool is_ip_address (const char *data)
Checks if the supplied string is an IPv4 or IPv6 address. Mostly used for determining if a server in the config is an IP address or hostname.
Definition at line 159 of file bak/nethelper.cc.
References ip_address::data.
{
        struct ip_address ipaddr;
        // inet_pton returns 1 on success, -1 on error, or 0 if input is invalid
        if ( inet_pton(AF_INET, data, &ipaddr.data) != 1 )
        {
                if ( inet_pton(AF_INET6, data, &ipaddr.data) != 1 )
                {
                        // not an IPv4 or IPv6 address
                        return false;
                }
        }
        // is an IPv4 or IPv6 address
        return true;
}
void net_cleanup ()
Cleans up all aspects of networking loaded within the application. Should only ever be called before the application closes, as a chance to free any dynamically allocated memory not yet freed.
We use the opportunity to cleanup things that don't 'really' need to be called, such as WSACleanup and ERR_free_strings; but it's good practice to do so.
See Also:
net_startup
Definition at line 182 of file bak/nethelper.cc.
{
        /* no error checking to be done, since we only call this when the app
         * is closing, and needless reporting will slow it down */
#if defined(USING_OPENSSL)
        // free OpenSSLs loaded error strings
        ERR_free_strings();
#endif
#if defined(_WIN32)
        // unload winsock
        WSACleanup();
#endif
}
bool net_startup (uint16_twinsock_version = 0)
Loads OpenSSL networking components (and non-SSL networking) - as Windows utilizes (and requires) WinSock, this will also call WSAStartup on Windows builds. winsock_version is ignored on non-Windows builds, and it can therefore be omitted.
Parameters:
winsock_version The version of Winsock to load and initialize
Returns:
Returns true on success, false on failure
See Also:
net_cleanup
Definition at line 201 of file bak/nethelper.cc.
References Error, fg_red(), and LOG.
{
#if defined(USING_OPENSSL)
        // load the openssl components
        SSL_library_init();
        SSL_load_error_strings();
        ERR_load_crypto_strings();
        ERR_load_BIO_strings();
        ERR_load_SSL_strings();
        ERR_load_ERR_strings();
        /* in case of an older version of OpenSSL being used; see man page */
        OpenSSL_add_all_algorithms();
#endif
#if defined(_WIN32)
        struct WSAData wsa;
        if ( WSAStartup(winsock_version, &wsa) != 0 )
        {
                LOG(LL_Error) << "Could not startup Winsock; Win32 error "
                        << GetLastError() << "\n";
                return false;
        }
#endif
        // cannot return false on non-Windows builds
        return true;
}
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.