.TH "build_config.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build_config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <api/compiler\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSING_MEMORY_DEBUGGING\fP"
.br
.ti -1c
.RI "#define \fBDISABLE_MEMORY_CHECK_TO_STDOUT\fP"
.br
.ti -1c
.RI "#define \fBDISABLE_MEMORY_OP_TO_STDOUT\fP"
.br
.ti -1c
.RI "#define \fBUSING_API_WARNINGS\fP"
.br
.ti -1c
.RI "#define \fBUSING_DETAILED_REFERENCE_COUNTING\fP"
.br
.ti -1c
.RI "#define \fBUSING_OPENSSL\fP"
.br
.ti -1c
.RI "#define \fBUSING_JSON\fP"
.br
.ti -1c
.RI "#define \fBUSING_LIBCONFIG\fP"
.br
.ti -1c
.RI "#define \fBUSING_BOOST_NET\fP"
.br
.ti -1c
.RI "#define \fBUSING_QT5_GUI\fP"
.br
.ti -1c
.RI "#define \fB_WIN32_WINNT\fP   0x0600"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _WIN32_WINNT   0x0600"

.PP
Definition at line 44 of file build_config\&.h\&.
.SS "#define DISABLE_MEMORY_CHECK_TO_STDOUT"

.PP
Definition at line 14 of file build_config\&.h\&.
.SS "#define DISABLE_MEMORY_OP_TO_STDOUT"

.PP
Definition at line 17 of file build_config\&.h\&.
.SS "#define USING_API_WARNINGS"

.PP
Definition at line 20 of file build_config\&.h\&.
.SS "#define USING_BOOST_NET"

.PP
Definition at line 35 of file build_config\&.h\&.
.SS "#define USING_DETAILED_REFERENCE_COUNTING"

.PP
Definition at line 23 of file build_config\&.h\&.
.SS "#define USING_JSON"

.PP
Definition at line 29 of file build_config\&.h\&.
.SS "#define USING_LIBCONFIG"

.PP
Definition at line 32 of file build_config\&.h\&.
.SS "#define USING_MEMORY_DEBUGGING"

.PP
Definition at line 11 of file build_config\&.h\&.
.SS "#define USING_OPENSSL"

.PP
Definition at line 26 of file build_config\&.h\&.
.SS "#define USING_QT5_GUI"

.PP
Definition at line 41 of file build_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
