.TH "char_helper.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
char_helper.h \- 
.PP
Cross-platform string conversion helper (mostly for Windows)  

.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'compiler\&.h'\fP
.br
\fC#include 'definitions\&.h'\fP
.br
\fC#include 'types\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRESET_STREAM\fP(s)   s\&.str('')"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBCHARTYPE\fP"
.br
.ti -1c
.RI "typedef std::stringstream \fBCHARSTREAMTYPE\fP"
.br
.ti -1c
.RI "typedef std::string \fBCHARSTRINGTYPE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cross-platform string conversion helper (mostly for Windows) 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBchar_helper\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define RESET_STREAM(s)   s\&.str('')"

.PP
Definition at line 38 of file char_helper\&.h\&.
.PP
Referenced by Log::Flush()\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef std::stringstream \fBCHARSTREAMTYPE\fP"

.PP
Definition at line 36 of file char_helper\&.h\&.
.SS "typedef std::string \fBCHARSTRINGTYPE\fP"

.PP
Definition at line 37 of file char_helper\&.h\&.
.SS "typedef char \fBCHARTYPE\fP"

.PP
Definition at line 35 of file char_helper\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
