.TH "compiler.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compiler.h \- 
.PP
Supported compiler macros, definitions and functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_VISUAL_STUDIO\fP   1"
.br
.ti -1c
.RI "#define \fBMS_VISUAL_CPP_VS8\fP   1400"
.br
.ti -1c
.RI "#define \fBMS_VISUAL_CPP_VS9\fP   1500"
.br
.ti -1c
.RI "#define \fBMS_VISUAL_CPP_VS10\fP   1600"
.br
.ti -1c
.RI "#define \fBMS_VISUAL_CPP_VS11\fP   1700"
.br
.ti -1c
.RI "#define \fBMS_VISUAL_CPP_VS12\fP   1800"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS8\fP   (_MSC_VER == \fBMS_VISUAL_CPP_VS8\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS9\fP   (_MSC_VER == \fBMS_VISUAL_CPP_VS9\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS10\fP   (_MSC_VER == \fBMS_VISUAL_CPP_VS10\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS11\fP   (_MSC_VER == \fBMS_VISUAL_CPP_VS11\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS12\fP   (_MSC_VER == \fBMS_VISUAL_CPP_VS12\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS8_OR_LATER\fP   (_MSC_VER >= \fBMS_VISUAL_CPP_VS8\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS9_OR_LATER\fP   (_MSC_VER >= \fBMS_VISUAL_CPP_VS9\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS10_OR_LATER\fP   (_MSC_VER >= \fBMS_VISUAL_CPP_VS10\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS11_OR_LATER\fP   (_MSC_VER >= \fBMS_VISUAL_CPP_VS11\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_IS_VS12_OR_LATER\fP   (_MSC_VER >= \fBMS_VISUAL_CPP_VS12\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_BEFORE_VS8\fP   (_MSC_VER < \fBMS_VISUAL_CPP_VS8\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_BEFORE_VS9\fP   (_MSC_VER < \fBMS_VISUAL_CPP_VS9\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_BEFORE_VS10\fP   (_MSC_VER < \fBMS_VISUAL_CPP_VS10\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_BEFORE_VS11\fP   (_MSC_VER < \fBMS_VISUAL_CPP_VS11\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_BEFORE_VS12\fP   (_MSC_VER < \fBMS_VISUAL_CPP_VS12\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_LATER_THAN_VS8\fP   (_MSC_VER > \fBMS_VISUAL_CPP_VS8\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_LATER_THAN_VS9\fP   (_MSC_VER > \fBMS_VISUAL_CPP_VS9\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_LATER_THAN_VS10\fP   (_MSC_VER > \fBMS_VISUAL_CPP_VS10\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_LATER_THAN_VS11\fP   (_MSC_VER > \fBMS_VISUAL_CPP_VS11\fP)"
.br
.ti -1c
.RI "#define \fBMSVC_LATER_THAN_VS12\fP   (_MSC_VER > \fBMS_VISUAL_CPP_VS12\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Supported compiler macros, definitions and functionality\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBcompiler\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_VISUAL_STUDIO   1"

.PP
Definition at line 58 of file compiler\&.h\&.
.SS "#define MS_VISUAL_CPP_VS10   1600"
Visual Studio 2010 
.PP
Definition at line 64 of file compiler\&.h\&.
.SS "#define MS_VISUAL_CPP_VS11   1700"
Visual Studio 2012 
.PP
Definition at line 65 of file compiler\&.h\&.
.SS "#define MS_VISUAL_CPP_VS12   1800"
Visual Studio 2013 
.PP
Definition at line 66 of file compiler\&.h\&.
.SS "#define MS_VISUAL_CPP_VS8   1400"
Visual Studio 2005 
.PP
Definition at line 62 of file compiler\&.h\&.
.SS "#define MS_VISUAL_CPP_VS9   1500"
Visual Studio 2008 
.PP
Definition at line 63 of file compiler\&.h\&.
.SS "#define MSVC_BEFORE_VS10   (_MSC_VER < \fBMS_VISUAL_CPP_VS10\fP)"
Is Pre-Visual Studio 2010 
.PP
Definition at line 80 of file compiler\&.h\&.
.SS "#define MSVC_BEFORE_VS11   (_MSC_VER < \fBMS_VISUAL_CPP_VS11\fP)"
Is Pre-Visual Studio 2012 
.PP
Definition at line 81 of file compiler\&.h\&.
.SS "#define MSVC_BEFORE_VS12   (_MSC_VER < \fBMS_VISUAL_CPP_VS12\fP)"
Is Pre-Visual Studio 2013 
.PP
Definition at line 82 of file compiler\&.h\&.
.SS "#define MSVC_BEFORE_VS8   (_MSC_VER < \fBMS_VISUAL_CPP_VS8\fP)"
Is Pre-Visual Studio 2005 
.PP
Definition at line 78 of file compiler\&.h\&.
.SS "#define MSVC_BEFORE_VS9   (_MSC_VER < \fBMS_VISUAL_CPP_VS9\fP)"
Is Pre-Visual Studio 2008 
.PP
Definition at line 79 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS10   (_MSC_VER == \fBMS_VISUAL_CPP_VS10\fP)"
Is Visual Studio 2010 
.PP
Definition at line 70 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS10_OR_LATER   (_MSC_VER >= \fBMS_VISUAL_CPP_VS10\fP)"
Is or later than Visual Studio 2010 
.PP
Definition at line 75 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS11   (_MSC_VER == \fBMS_VISUAL_CPP_VS11\fP)"
Is Visual Studio 2012 
.PP
Definition at line 71 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS11_OR_LATER   (_MSC_VER >= \fBMS_VISUAL_CPP_VS11\fP)"
Is or later than Visual Studio 2012 
.PP
Definition at line 76 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS12   (_MSC_VER == \fBMS_VISUAL_CPP_VS12\fP)"
Is Visual Studio 2013 
.PP
Definition at line 72 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS12_OR_LATER   (_MSC_VER >= \fBMS_VISUAL_CPP_VS12\fP)"
Is or later than Visual Studio 2013 
.PP
Definition at line 77 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS8   (_MSC_VER == \fBMS_VISUAL_CPP_VS8\fP)"
Is Visual Studio 2005 
.PP
Definition at line 68 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS8_OR_LATER   (_MSC_VER >= \fBMS_VISUAL_CPP_VS8\fP)"
Is or later than Visual Studio 2005 
.PP
Definition at line 73 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS9   (_MSC_VER == \fBMS_VISUAL_CPP_VS9\fP)"
Is Visual Studio 2008 
.PP
Definition at line 69 of file compiler\&.h\&.
.SS "#define MSVC_IS_VS9_OR_LATER   (_MSC_VER >= \fBMS_VISUAL_CPP_VS9\fP)"
Is or later than Visual Studio 2008 
.PP
Definition at line 74 of file compiler\&.h\&.
.SS "#define MSVC_LATER_THAN_VS10   (_MSC_VER > \fBMS_VISUAL_CPP_VS10\fP)"
Is Post-Visual Studio 2010 
.PP
Definition at line 85 of file compiler\&.h\&.
.SS "#define MSVC_LATER_THAN_VS11   (_MSC_VER > \fBMS_VISUAL_CPP_VS11\fP)"
Is Post-Visual Studio 2012 
.PP
Definition at line 86 of file compiler\&.h\&.
.SS "#define MSVC_LATER_THAN_VS12   (_MSC_VER > \fBMS_VISUAL_CPP_VS12\fP)"
Is Post-Visual Studio 2013 
.PP
Definition at line 87 of file compiler\&.h\&.
.SS "#define MSVC_LATER_THAN_VS8   (_MSC_VER > \fBMS_VISUAL_CPP_VS8\fP)"
Is Post-Visual Studio 2005 
.PP
Definition at line 83 of file compiler\&.h\&.
.SS "#define MSVC_LATER_THAN_VS9   (_MSC_VER > \fBMS_VISUAL_CPP_VS9\fP)"
Is Post-Visual Studio 2008 
.PP
Definition at line 84 of file compiler\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
