.TH "Configuration::proxy< T >" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration::proxy< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Configuration\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBproxy\fP ()"
.br
.ti -1c
.RI "\fBoperator const T &\fP () const "
.br
.ti -1c
.RI "\fBoperator const T &\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "T \fBoperator=\fP (const T &arg)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBdata\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBConfiguration\fP"
.br
.ti -1c
.RI "class \fBConfigurationWriter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class Configuration::proxy< T >"

.PP
Definition at line 126 of file Configuration\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBConfiguration::proxy\fP< T >::\fBproxy\fP ()\fC [inline]\fP"

.PP
Definition at line 138 of file Configuration\&.h\&.
.PP
.nf
139                 {
140                 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<class T> \fBConfiguration::proxy\fP< T >::operator const T & () const\fC [inline]\fP"

.PP
Definition at line 141 of file Configuration\&.h\&.
.PP
.nf
141                                           {
142                         return data;
143                 }
.fi
.SS "template<class T> \fBConfiguration::proxy\fP< T >::operator const T & ()\fC [inline]\fP"

.PP
Definition at line 144 of file Configuration\&.h\&.
.PP
.nf
144                                     {
145                         return data;
146                 }
.fi
.SS "template<class T> T \fBConfiguration::proxy\fP< T >::operator= (const T &arg)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 133 of file Configuration\&.h\&.
.PP
.nf
133                                            {
134                         data = arg; return data;
135                 }
.fi
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T> friend class \fBConfiguration\fP\fC [friend]\fP"

.PP
Definition at line 128 of file Configuration\&.h\&.
.SS "template<class T> friend class ConfigurationWriter\fC [friend]\fP"

.PP
Definition at line 130 of file Configuration\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> T \fBConfiguration::proxy\fP< T >::data\fC [private]\fP"

.PP
Definition at line 132 of file Configuration\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
