Configuration
NAME
Configuration -
SYNOPSIS
#include <Configuration.h>
Classes
class proxy
Public Member Functions
~Configuration ()
void Dump () const
void Load (const char *specific_path=nullptr)
void LoadUI ()
const char * Path () const
void Save ()
Public Attributes
struct {
   proxy< char > command_prefix
   proxy< bool > enable_gui
   proxy< bool > no_terminal
   struct {
      proxy< std::string > file_name
      proxy< std::string > cfg_name
      proxy< HMODULE > module
      int32_t(* pfunc_destroy_interface )()
      int32_t(* pfunc_process_interface )()
      int32_t(* pfunc_spawn_interface )()
   } library
} ui
Private Member Functions
NO_CLASS_ASSIGNMENT (Configuration)
NO_CLASS_COPY (Configuration)
bool CreateDefault ()
Configuration ()
Private Attributes
std::string _path
Friends
class Runtime
Detailed Description
Definition at line 34 of file Configuration.h.
Constructor & Destructor Documentation
Configuration::Configuration () [inline], [private]
Definition at line 60 of file Configuration.h.
        {
                _path = "sbi.exe.cfg";
        }
Configuration::~Configuration () [inline]
Definition at line 66 of file Configuration.h.
{}
Member Function Documentation
bool Configuration::CreateDefault () [private]
Attempts to create a default configuration file.
Only called when an attempt to load the configuration file fails with 'file not found'.
Return values:
true when the file is created
false if the file could not be created
Definition at line 49 of file Configuration.cc.
References fg_grey(), and fg_red().
Referenced by Load().
{
        FILE* default_config;
        std::cout << fg_grey << "Creating default config file\n";
#if defined(_WIN32)
        if ( (default_config = _fsopen(_path.c_str(), "w", _SH_DENYWR)) == nullptr )
        {
                std::cerr << fg_red << "Could not open " << _path << " to apply the default configuration file\n";
                return false;
        }
#else
        int fd;
        if ( (fd = open(_path.c_str(), O_WRONLY | O_CREAT, O_NOATIME | S_IRWXU | S_IRGRP | S_IROTH)) == -1 )
        {
                std::cerr << fg_red << "Could not open " << _path << " to apply the default configuration file; errno " << errno << "\n";
                return false;
        }
        if ( (default_config = fdopen(fd, "w")) == nullptr )
        {
                std::cerr << fg_red << "fdopen failed on the file descriptor for " << _path << "; errno " << errno << "\n";
                return false;
        }
#endif
        char* config_array[] = {
#if defined(USING_LIBCONFIG)
                "ui =",
                "{",
                " enable_gui = 1;",
                " enable_terminal = 1;",
                " command_prefix = \"/\";",
                " library = {",
                " // looks for 'libui-XXX.dll' ",
                " name : \"qt5\";",
                " };",
                "};",
        };
#else
        };
# error "Need a configuration library to use and store defaults"
#endif
        uint32_t config_array_size = sizeof(config_array) / sizeof(char*);
        for ( uint32_t i = 0; i < config_array_size; i++ )
                fprintf(default_config, "%s\n", config_array[i]);
        fclose(default_config);
        return true;
}
void Configuration::Dump () const
Dumps the entire configuration, as-is, to the application log file. ELogLevel::Debug does not need to be set, as it will be output directly, not checking the level.
Definition at line 108 of file Configuration.cc.
References Log::Append(), Force, LOG, Runtime::Logger(), mb_to_utf8(), runtime, and ui.
{
        // we want to start on a newline, logging will have the prefix data
        LOG(ELogLevel::Force) << "\n\t==== Dumping Parsed Configuration ====\n";
        std::stringstream log_str;
        //uint32_t i;
        log_str << "\t---- UI Settings ----\n"
                << "\t* ui.command_prefix = " << ui.command_prefix << "\n"
                << "\t* ui.enable_gui = " << ui.enable_gui << "\n"
                << "\t* ui.library = " << ui.library.file_name.data << "\n"
                << "\t* ui.no_terminal = " << ui.no_terminal << "\n";
        
        log_str << "\t#### End Settings Dump ####\n";
#if defined(_WIN32)
        wchar_t buf[8192];
        mb_to_utf8(buf, log_str.str().c_str(), _countof(buf));
        runtime.Logger()->Append(buf);
#else
        runtime.Logger()->Append(log_str.str());
#endif
}
void Configuration::Load (const char *specific_path = nullptr)
Loads the core requirements of the application; enough to bring it up and let the user start doing whatever relevant tasks.
If you want to load something that doesn't need to be present until after we're already running, use LoadDelayed().
Parameters:
specific_path Set this to a path, relative or full, of the configuration file to load. This enables a different configuration to be executed by default simply by setting it on the command line.
Definition at line 137 of file Configuration.cc.
References _path, CreateDefault(), LoadUI(), MALLOC, mb_to_utf8(), path_exists(), and ui.
Referenced by app_init().
{
        if ( specific_path != nullptr )
                _path = specific_path;
#if defined(USING_LIBCONFIG)
        libconfig::Config cfg;
# if defined(_WIN32)
        wchar_t w[MAX_PATH];
        mb_to_utf8(w, _path.c_str(), _countof(w));
        if ( !path_exists(w) )
# else
# error nix equivalent
# endif
        {
                CreateDefault();
        }
        try
        {
                cfg.readFile(_path.c_str());
        }
        catch ( libconfig::FileIOException& e )
        {
                // error reading the file.
                throw;
        }
        catch ( libconfig::ParseException& e )
        {
                // error parsing the file.
                throw;
        }
        if ( !cfg.lookupValue("ui.library.name", ui.library.file_name.data) )
        {
        }
        if ( !cfg.lookupValue("ui.enable_terminal", ui.no_terminal.data) )
        {
        }
        if ( !cfg.lookupValue("ui.enable_gui", ui.enable_gui.data) )
        {
        }
        if ( !cfg.lookupValue("ui.command_prefix", (int32_t&)ui.command_prefix.data) )
        {
        }
        LoadUI();
#else
        // holds the entire config file in memory, ready to parse
        char* buffer;
        uint32_t alloc;
        FILE* fp;
        if ( (fp = _fsopen(_path.c_str(), "r", _SH_DENYWR)) == nullptr )
        {
                printf("Failed to open configuration file '%s'; errno %d\n",
                       _path.c_str(), errno);
                return;
        }
        // move to file end
        fseek(fp, 0, SEEK_END);
        // obtain file size, and amount to allocate
        alloc = ftell(fp);
        // return to start of file
        fseek(fp, 0, SEEK_SET);
        // allocate the buffer
        buffer = (char*)MALLOC(alloc);
        // copy into memory
        fread(buffer, alloc, 1, fp);
        // done with the file, close it
        fclose(fp);
        struct json_object* json_root;
        json_root = json_tokener_parse(buffer);
        LoadUI(json_root);
#endif
}
void Configuration::LoadUI ()
Definition at line 263 of file Configuration.cc.
References BUILD_STRING, Debug, Info, LOG, mb_to_utf8(), module, str_format(), and ui.
Referenced by Load().
{
        char mb[260];
        uint32_t func_num = 0;
        char* func_names[] = {
                "destroy_interface",
                "process_interface",
                "spawn_interface"
        };
        int32_t (*pfunc[sizeof(func_names)])();
        uint32_t funcarray_size = sizeof(func_names) / sizeof(char*);
#if defined(_WIN32)
        HMODULE module;
        wchar_t w_file[MAX_PATH];
        str_format(mb, sizeof(mb),
                   "libui-%s.dll",
                   ui.library.file_name.data.c_str());
        mb_to_utf8(w_file, mb, _countof(w_file));
        LOG(ELogLevel::Info) << "Loading Dynamic Library '" << CHARSTRINGTYPE(w_file) << "'\n";
        // load from the current directory
        module = LoadLibrary(w_file);
        // error 126 means the libui file or one of its dependencies is missing
        if ( module == nullptr )
                throw std::runtime_error("LoadLibrary failed - error code " + std::to_string(GetLastError()));
        for ( func_num = 0; func_num != funcarray_size; func_num++ )
        {
                if ( (pfunc[func_num] = (int32_t(__cdecl*)())GetProcAddress(module, func_names[func_num])) == nullptr )
                {
                        FreeLibrary(module);
                        throw std::runtime_error(BUILD_STRING("Failed to load ", mb, "; missing exported function '", func_names[--func_num], "'"));
                }
        }
        ui.library.pfunc_destroy_interface = pfunc[0];
        ui.library.pfunc_process_interface = pfunc[1];
        ui.library.pfunc_spawn_interface = pfunc[2];
        ui.library.module = module;
        LOG(ELogLevel::Debug) << "Library loaded successfully (" << ui.library.module << "). Functions:\n"
                "\t* destroy_interface = " << ui.library.pfunc_destroy_interface << "\n"
                "\t* process_interface = " << ui.library.pfunc_process_interface << "\n"
                "\t* spawn_interface = " << ui.library.pfunc_spawn_interface << "\n";
#else
#endif // _WIN32
}
Configuration::NO_CLASS_ASSIGNMENT (Configuration) [private]
Configuration::NO_CLASS_COPY (Configuration) [private]
const char * Configuration::Path () const
Retrieves the configuration file path; pointer remains valid as long as this class exists (which as long as it's in runtime, is after main returns).
Definition at line 325 of file Configuration.cc.
References _path.
Referenced by spawn_interface().
{
        return _path.c_str();
}
void Configuration::Save ()
Saves the current configuration to the file previously loaded.
Friends And Related Function Documentation
friend class Runtime [friend]
Definition at line 37 of file Configuration.h.
Member Data Documentation
std::string Configuration::_path [private]
the path to the configuration file
Definition at line 44 of file Configuration.h.
Referenced by Load(), and Path().
proxy<std::string> Configuration::cfg_name
Definition at line 165 of file Configuration.h.
proxy<char> Configuration::command_prefix
Definition at line 151 of file Configuration.h.
proxy<bool> Configuration::enable_gui
Definition at line 153 of file Configuration.h.
proxy<std::string> Configuration::file_name
Definition at line 160 of file Configuration.h.
struct { ... } Configuration::library
Referenced by app_exec().
proxy<HMODULE> Configuration::module
Definition at line 168 of file Configuration.h.
Referenced by LoadUI().
proxy<bool> Configuration::no_terminal
Definition at line 154 of file Configuration.h.
int32_t(* Configuration::pfunc_destroy_interface)()
Definition at line 174 of file Configuration.h.
int32_t(* Configuration::pfunc_process_interface)()
Definition at line 175 of file Configuration.h.
int32_t(* Configuration::pfunc_spawn_interface)()
Definition at line 176 of file Configuration.h.
struct { ... } Configuration::ui
Referenced by app_exec(), Dump(), Load(), and LoadUI().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.