.TH "Configuration.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration.h \- 
.PP
The application configuration\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'char_helper\&.h'\fP
.br
\fC#include <Windows\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfiguration\fP"
.br
.ti -1c
.RI "class \fBConfiguration::proxy< T >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The application configuration\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBConfiguration\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define WIN32_LEAN_AND_MEAN"

.PP
Definition at line 15 of file Configuration\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
