.TH "detailed_reference_info" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detailed_reference_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IrcObject\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBsource_object\fP"
.br
.ti -1c
.RI "uint32_t \fBline\fP"
.br
.ti -1c
.RI "char \fBfile\fP [32]"
.br
.ti -1c
.RI "char \fBfunc\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file bak/IrcObject\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char detailed_reference_info::file[32]"

.PP
Definition at line 36 of file bak/IrcObject\&.h\&.
.SS "char detailed_reference_info::func[32]"

.PP
Definition at line 37 of file bak/IrcObject\&.h\&.
.SS "uint32_t detailed_reference_info::line"

.PP
Definition at line 35 of file bak/IrcObject\&.h\&.
.SS "void* detailed_reference_info::source_object"
Usually a derived class from \fBIrcObject\fP, but because the \fBIrcEngine\fP does reference handling (and it isn't an \fBIrcObject\fP derivative) we have to use just a normal void pointer 
.PP
Definition at line 34 of file bak/IrcObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
