.TH "E_LOG_LEVEL" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E_LOG_LEVEL \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBLL_None\fP = 0, \fBLL_Error\fP, \fBLL_Warn\fP, \fBLL_Info\fP, \fBLL_Debug\fP, \fBLL_Force\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBE_LOG_LEVEL::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILL_None \fP\fP
no logging at all 
.TP
\fB\fILL_Error \fP\fP
logging errors 
.TP
\fB\fILL_Warn \fP\fP
logging warnings + above 
.TP
\fB\fILL_Info \fP\fP
logging info + above 
.TP
\fB\fILL_Debug \fP\fP
logging debug (all) 
.TP
\fB\fILL_Force \fP\fP
logging forced; statement WILL be logged 
.PP
Definition at line 23 of file Log\&.h\&.
.PP
.nf
24         {
25                 LL_None = 0,    
26                 LL_Error,       
27                 LL_Warn,        
28                 LL_Info,        
29                 LL_Debug,       
30                 LL_Force        
31         };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
