.TH "E_UI_FLAGS" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E_UI_FLAGS \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBReset\fP = 0, \fBSaveLastPosition\fP, \fBSaveLastSize\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBE_UI_FLAGS::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIReset \fP\fP
.TP
\fB\fISaveLastPosition \fP\fP
.TP
\fB\fISaveLastSize \fP\fP
.PP
Definition at line 23 of file library\&.cc\&.
.PP
.nf
24         {
25                 Reset = 0,
26                 SaveLastPosition,
27                 SaveLastSize
28         };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
