.TH "EInterfaceStatus" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EInterfaceStatus \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBOk\fP = 0, \fBFileNotFound\fP, \fBLoadFailure\fP, \fBInsufficientResources\fP, \fBUnknown\fP = -1 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEInterfaceStatus::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOk \fP\fP
.TP
\fB\fIFileNotFound \fP\fP
.TP
\fB\fILoadFailure \fP\fP
.TP
\fB\fIInsufficientResources \fP\fP
.TP
\fB\fIUnknown \fP\fP
.PP
Definition at line 13 of file interface_status\&.h\&.
.PP
.nf
14         {
15                 Ok = 0,
16                 FileNotFound,
17                 LoadFailure,
18                 InsufficientResources,
19                 Unknown = -1
20         };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
