.TH "ErrorConflictingType::DisabledType" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorConflictingType::DisabledType \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBDisabledType\fP ()"
.br
.ti -1c
.RI "\fB~DisabledType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file types\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ErrorConflictingType::DisabledType::DisabledType ()\fC [private]\fP"

.SS "ErrorConflictingType::DisabledType::~DisabledType ()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
