.TH "file_version_info" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_version_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utils_win\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBmajor\fP"
.br
.ti -1c
.RI "uint16_t \fBminor\fP"
.br
.ti -1c
.RI "uint16_t \fBrevision\fP"
.br
.ti -1c
.RI "uint16_t \fBbuild\fP"
.br
.ti -1c
.RI "wchar_t \fBdescription\fP [1024]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds version information for a file; to be used with binaries 
.PP
Definition at line 19 of file utils_win\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t file_version_info::build"

.PP
Definition at line 30 of file utils_win\&.h\&.
.PP
Referenced by get_file_version_info()\&.
.SS "wchar_t file_version_info::description[1024]"

.PP
Definition at line 32 of file utils_win\&.h\&.
.PP
Referenced by get_file_version_info()\&.
.SS "uint16_t file_version_info::major"

.PP
Definition at line 27 of file utils_win\&.h\&.
.PP
Referenced by get_file_version_info()\&.
.SS "uint16_t file_version_info::minor"

.PP
Definition at line 28 of file utils_win\&.h\&.
.PP
Referenced by get_file_version_info()\&.
.SS "uint16_t file_version_info::revision"

.PP
Definition at line 29 of file utils_win\&.h\&.
.PP
Referenced by get_file_version_info()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
