.TH "interface_status.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interface_status.h \- 
.PP
Interface library status codes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEInterfaceStatus\fP { \fBEInterfaceStatus::Ok\fP = 0, \fBEInterfaceStatus::FileNotFound\fP, \fBEInterfaceStatus::LoadFailure\fP, \fBEInterfaceStatus::InsufficientResources\fP, \fBEInterfaceStatus::Unknown\fP = -1 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface library status codes\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBinterface_status\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEInterfaceStatus\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOk \fP\fP
.TP
\fB\fIFileNotFound \fP\fP
.TP
\fB\fILoadFailure \fP\fP
.TP
\fB\fIInsufficientResources \fP\fP
.TP
\fB\fIUnknown \fP\fP
.PP
Definition at line 11 of file interface_status\&.h\&.
.PP
.nf
12 {
13         Ok = 0,
14         FileNotFound,
15         LoadFailure,
16         InsufficientResources,
17         Unknown = -1
18 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
