.TH "ip_address" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_address \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nethelper\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBfamily\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct in_addr \fBip4\fP"
.br
.ti -1c
.RI "   struct in6_addr \fBip6\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct in_addr \fBip4\fP"
.br
.ti -1c
.RI "   struct in6_addr \fBip6\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores an IP address for the family type 
.PP
Definition at line 40 of file nethelper\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "union { \&.\&.\&. }   ip_address::data"

.PP
Referenced by is_ip_address()\&.
.SS "union { \&.\&.\&. }   ip_address::data"

.SS "int32_t ip_address::family"
AF_INET or AF_INET6 
.PP
Definition at line 42 of file nethelper\&.h\&.
.SS "struct in_addr ip_address::ip4"
IPv4 address 
.PP
Definition at line 46 of file nethelper\&.h\&.
.SS "struct in6_addr ip_address::ip6"
IPv6 address 
.PP
Definition at line 47 of file nethelper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
