.TH "irc_status.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc_status.h \- 
.PP
IRC-specific status codes returned from functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <api/definitions\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEIrcStatus\fP { \fBEIrcStatus::OK\fP, \fBEIrcStatus::MissingParameter\fP, \fBEIrcStatus::InvalidParameter\fP, \fBEIrcStatus::ObjectNotFound\fP, \fBEIrcStatus::ParsingError\fP, \fBEIrcStatus::OSAPIError\fP, \fBEIrcStatus::QueueEmpty\fP, \fBEIrcStatus::NickIsNotClient\fP, \fBEIrcStatus::InvalidState\fP, \fBEIrcStatus::ObjectAddError\fP, \fBEIrcStatus::ObjectFreeError\fP, \fBEIrcStatus::InvalidData\fP, \fBEIrcStatus::LimitExceeded\fP, \fBEIrcStatus::ServerClosed\fP, \fBEIrcStatus::UnknownResponse\fP, \fBEIrcStatus::NoOwner\fP, \fBEIrcStatus::NoMoreNicks\fP, \fBEIrcStatus::OpenSSLError\fP, \fBEIrcStatus::LookupFailed\fP, \fBEIrcStatus::Unknown\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
IRC-specific status codes returned from functions\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBirc_status\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEIrcStatus\fP\fC [strong]\fP"
IRC status code enumeration\&.
.PP
These are not error codes; for example, when creating a new user in a channel we'll try to Get() that user when we expect it to not exist (in order to verify we're not trying to add the same user twice, which would mean we've been handling something incorrectly or not at all); as a result, the return value of ObjectNotFound is intended and should not be reported as an error\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOK \fP\fP
.TP
\fB\fIMissingParameter \fP\fP
.TP
\fB\fIInvalidParameter \fP\fP
.TP
\fB\fIObjectNotFound \fP\fP
.TP
\fB\fIParsingError \fP\fP
.TP
\fB\fIOSAPIError \fP\fP
.TP
\fB\fIQueueEmpty \fP\fP
.TP
\fB\fINickIsNotClient \fP\fP
.TP
\fB\fIInvalidState \fP\fP
.TP
\fB\fIObjectAddError \fP\fP
.TP
\fB\fIObjectFreeError \fP\fP
.TP
\fB\fIInvalidData \fP\fP
.TP
\fB\fILimitExceeded \fP\fP
.TP
\fB\fIServerClosed \fP\fP
.TP
\fB\fIUnknownResponse \fP\fP
.TP
\fB\fINoOwner \fP\fP
.TP
\fB\fINoMoreNicks \fP\fP
.TP
\fB\fIOpenSSLError \fP\fP
.TP
\fB\fILookupFailed \fP\fP
.TP
\fB\fIUnknown \fP\fP
.PP
Definition at line 32 of file irc_status\&.h\&.
.PP
.nf
33 {
34         OK,
35         MissingParameter,       // expected parameter was missing or null
36         InvalidParameter,       // supplied parameter is invalid
37         ObjectNotFound,         // a user/channel/etc\&. was not found
38         ParsingError,           // data parsing failed when should never
39         OSAPIError,             // OS function failed
40         QueueEmpty,             // The queue contained no items
41         NickIsNotClient,        // Expected client nickname, did not match
42         InvalidState,           // The state is incompatible or invalid in context
43         ObjectAddError,         // Failed to create an IrcObject
44         ObjectFreeError,        // Failed to free an IrcObject
45         InvalidData,            // The data is not in a recognizable format
46         LimitExceeded,          // A limit was exceeded
47         ServerClosed,           // The server closed the connection
48         UnknownResponse,        // Server supplied valid but unknown data
49         NoOwner,                // The objects parent was a nullptr
50         NoMoreNicks,            // There are no nicknames left to use
51         OpenSSLError,           // OpenSSL encountered an error
52         LookupFailed,           // DNS lookup failed
53         Unknown                 // Placeholder/default; should never see this reported
54 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
