.TH "irc_structs.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc_structs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <api/char_helper\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBirc_activity\fP"
.br
.ti -1c
.RI "struct \fBircbuf_data\fP"
.br
.ti -1c
.RI "struct \fBircbuf_sender\fP"
.br
.ti -1c
.RI "struct \fBmode_data\fP"
.br
.ti -1c
.RI "struct \fBmode_update\fP"
.br
.ti -1c
.RI "struct \fBuser_modes_change\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
