.TH "irc_channel_modes.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc_channel_modes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <api/definitions\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHANFLAG_RAW\fP   0x00000000"
.br
.ti -1c
.RI "#define \fBCHANFLAG_ACTIVE\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBCHANFLAG_RESERVED0\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBCHANFLAG_RESERVED1\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBCHANFLAG_RESERVED2\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBCHANFLAG_USERLIMIT\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBCHANFLAG_KEY\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBCHANFLAG_PRIVATE\fP   0x00000040"
.br
.ti -1c
.RI "#define \fBCHANFLAG_SECRET\fP   0x00000080"
.br
.ti -1c
.RI "#define \fBCHANFLAG_TOPIC_PROTECT\fP   0x00000100"
.br
.ti -1c
.RI "#define \fBCHANFLAG_NO_MESSAGES\fP   0x00000200"
.br
.ti -1c
.RI "#define \fBCHANFLAG_INVITE_ONLY\fP   0x00000400"
.br
.ti -1c
.RI "#define \fBCHANFLAG_MODERATED\fP   0x00000800"
.br
.ti -1c
.RI "#define \fBCHANFLAG_BANDWIDTH_SAVE\fP   0x00001000"
.br
.ti -1c
.RI "#define \fBCHANFLAG_SECURE_ONLY\fP   0x00002000"
.br
.ti -1c
.RI "#define \fBCHANFLAG_MODERATE_UNREG\fP   0x00004000"
.br
.ti -1c
.RI "#define \fBCHANFLAG_REGGED_ONLY\fP   0x00008000"
.br
.ti -1c
.RI "#define \fBCHANFLAG_IRC_OPS_ONLY\fP   0x00010000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHANFLAG_ACTIVE   0x00000001"
Channel object exists, but we're not actually in it 
.PP
Definition at line 18 of file irc_channel_modes\&.h\&.
.PP
Referenced by IrcParser::HandleJoin(), and IrcChannel::IsActive()\&.
.SS "#define CHANFLAG_BANDWIDTH_SAVE   0x00001000"
Bandwidth saver - don't receive messages if idle 
.PP
Definition at line 30 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_INVITE_ONLY   0x00000400"
Can only join if invited or on invite-list 
.PP
Definition at line 28 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_IRC_OPS_ONLY   0x00010000"
Only IRC Ops may join the channel 
.PP
Definition at line 34 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_KEY   0x00000020"
Password 'key' required to join 
.PP
Definition at line 23 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_MODERATE_UNREG   0x00004000"
Moderated, but anyone authenticated is allowed to talk 
.PP
Definition at line 32 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_MODERATED   0x00000800"
Moderated - only users with +v or greater may talk 
.PP
Definition at line 29 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_NO_MESSAGES   0x00000200"
No external messages allowed in 
.PP
Definition at line 27 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_PRIVATE   0x00000040"
Must be member of channel to find it 
.PP
Definition at line 24 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_RAW   0x00000000"
Default Channel State 
.PP
Definition at line 17 of file irc_channel_modes\&.h\&.
.PP
Referenced by IrcParser::HandleKick(), and IrcParser::HandlePart()\&.
.SS "#define CHANFLAG_REGGED_ONLY   0x00008000"
Only authenticated users may join the channel 
.PP
Definition at line 33 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_RESERVED0   0x00000002"

.PP
Definition at line 19 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_RESERVED1   0x00000004"

.PP
Definition at line 20 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_RESERVED2   0x00000008"

.PP
Definition at line 21 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_SECRET   0x00000080"
Server will pretend channel doesn't exist for some commands 
.PP
Definition at line 25 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_SECURE_ONLY   0x00002000"
Only users connected via SSL may join the channel 
.PP
Definition at line 31 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_TOPIC_PROTECT   0x00000100"
Only ops can set topic 
.PP
Definition at line 26 of file irc_channel_modes\&.h\&.
.SS "#define CHANFLAG_USERLIMIT   0x00000010"
Limit to number of users that can join 
.PP
Definition at line 22 of file irc_channel_modes\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
