.TH "irc_client" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc_client \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <live_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBautoauth_service\fP"
.br
.ti -1c
.RI "std::string \fBautoauth_password\fP"
.br
.ti -1c
.RI "std::string \fBhostmask\fP"
.br
.ti -1c
.RI "std::string \fBnickname\fP"
.br
.ti -1c
.RI "std::string \fBkick_reason\fP"
.br
.ti -1c
.RI "std::string \fBpart_reason\fP"
.br
.ti -1c
.RI "std::string \fBquit_reason\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBnicknames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The client parameters used for an individual connection\&. Pretty much the same as the configuration struct, but this is used for the 'live' settings and also on reconnection\&.
.PP
This enables you to retain your saved, preferred settings, but for this one instance you want a slight change\&. On reconnect, it will retain your small changes, and not reload the defaults from the file\&. 
.PP
Definition at line 30 of file live_structs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string irc_client::autoauth_password"
The password to the receiving service 
.PP
Definition at line 33 of file live_structs\&.h\&.
.SS "std::string irc_client::autoauth_service"
The service receiving user authentication 
.PP
Definition at line 32 of file live_structs\&.h\&.
.SS "std::string irc_client::hostmask"
The custom hostmask to use, if any 
.PP
Definition at line 34 of file live_structs\&.h\&.
.PP
Referenced by IrcNetwork::ClientHostmask()\&.
.SS "std::string irc_client::kick_reason"
The default kick reason, if none other is supplied 
.PP
Definition at line 36 of file live_structs\&.h\&.
.SS "std::string irc_client::nickname"
The current nickname to use 
.PP
Definition at line 35 of file live_structs\&.h\&.
.PP
Referenced by IrcNetwork::ClientNickname(), IrcParser::Handle001(), IrcParser::HandleJoin(), IrcParser::HandleKick(), IrcParser::HandleKill(), IrcParser::HandleMode(), IrcParser::HandleNick(), IrcParser::HandleNotice(), IrcParser::HandlePart(), IrcParser::HandleQuit(), and IrcConnection::SendInit()\&.
.SS "std::vector< std::string > irc_client::nicknames"
The list of nicknames available to use 
.PP
Definition at line 39 of file live_structs\&.h\&.
.SS "std::string irc_client::part_reason"
The default part reason, if none other is supplied 
.PP
Definition at line 37 of file live_structs\&.h\&.
.SS "std::string irc_client::quit_reason"
The default quit reason, if none other is supplied 
.PP
Definition at line 38 of file live_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
