.TH "irc_user_modes.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc_user_modes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <api/definitions\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBE_USER_MODE\fP { \fBUM_None\fP = 0x0, \fBUM_Voice\fP = 0x1, \fBUM_HalfOp\fP = 0x2, \fBUM_Op\fP = 0x4, \fBUM_Admin\fP = 0x8, \fBUM_Owner\fP = 0x10, \fBUM_Unknown\fP = 0xFF, \fBUM_None\fP = 0x0, \fBUM_Voice\fP = 0x1, \fBUM_HalfOp\fP = 0x2, \fBUM_Op\fP = 0x4, \fBUM_Admin\fP = 0x8, \fBUM_Owner\fP = 0x10, \fBUM_Unknown\fP = 0xFF }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBE_USER_MODE\fP"
Known server user modes - used for arranging the nicklist and checking authorization internally\&.
.PP
At time of writing, the most modes I've ever seen on a server is six: no_mode, Voice, HalfOp, Op, Admin, and Owner UM_Unknown is reserved for unknown types, and will be sorted separately\&. No point putting them at the top, since you can't go higher than owner\&.\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUM_None \fP\fP
Default user state 
.TP
\fB\fIUM_Voice \fP\fP
User is 'voiced' 
.TP
\fB\fIUM_HalfOp \fP\fP
User has 'halfop' 
.TP
\fB\fIUM_Op \fP\fP
User has 'op' 
.TP
\fB\fIUM_Admin \fP\fP
User is a channel admin 
.TP
\fB\fIUM_Owner \fP\fP
User is the channel owner 
.TP
\fB\fIUM_Unknown \fP\fP
Plain unknown type 
.TP
\fB\fIUM_None \fP\fP
Default user state 
.TP
\fB\fIUM_Voice \fP\fP
User is 'voiced' 
.TP
\fB\fIUM_HalfOp \fP\fP
User has 'halfop' 
.TP
\fB\fIUM_Op \fP\fP
User has 'op' 
.TP
\fB\fIUM_Admin \fP\fP
User is a channel admin 
.TP
\fB\fIUM_Owner \fP\fP
User is the channel owner 
.TP
\fB\fIUM_Unknown \fP\fP
Plain unknown type 
.PP
Definition at line 28 of file irc_user_modes\&.h\&.
.PP
.nf
29 {
30         UM_None = 0x0,          
31         UM_Voice = 0x1,         
32         UM_HalfOp = 0x2,        
33         UM_Op = 0x4,            
34         UM_Admin = 0x8,         
35         UM_Owner = 0x10,        
36         UM_Unknown = 0xFF       
37 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
