.TH "ircbuf_sender" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ircbuf_sender \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <irc_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBnickname\fP"
.br
.ti -1c
.RI "std::string \fBident\fP"
.br
.ti -1c
.RI "std::string \fBhostmask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to store the three 'components' of an IRC sender - the nickname, ident and hostmask\&. Frequently the sender is the server itself, which has no ident or 'nickname'\&. We interpret it as the nickname however, to maintain consistency\&. 
.PP
Definition at line 110 of file irc_structs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string ircbuf_sender::hostmask"
The users hostmask (empty if server) 
.PP
Definition at line 114 of file irc_structs\&.h\&.
.PP
Referenced by IrcParser::Handle353(), IrcParser::HandleCap(), IrcParser::HandleJoin(), IrcParser::HandlePrivmsg(), IrcParser::HandleQuit(), and IrcParser::SplitSender()\&.
.SS "std::string ircbuf_sender::ident"
The users ident (empty if server) 
.PP
Definition at line 113 of file irc_structs\&.h\&.
.PP
Referenced by IrcParser::Handle353(), IrcParser::HandleCap(), IrcParser::HandleJoin(), IrcParser::HandlePrivmsg(), IrcParser::HandleQuit(), and IrcParser::SplitSender()\&.
.SS "std::string ircbuf_sender::nickname"
The senders nickname/entire server string 
.PP
Definition at line 112 of file irc_structs\&.h\&.
.PP
Referenced by IrcParser::Handle001(), IrcParser::Handle003(), IrcParser::Handle004(), IrcParser::Handle005(), IrcParser::Handle353(), IrcParser::HandleCap(), IrcParser::HandleJoin(), IrcParser::HandleNick(), IrcParser::HandlePart(), IrcParser::HandlePrivmsg(), IrcParser::HandleQuit(), and IrcParser::SplitSender()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
