.TH "IrcConnection.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IrcConnection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <set>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <WS2tcpip\&.h>\fP
.br
\fC#include <api/char_helper\&.h>\fP
.br
\fC#include <api/Runtime\&.h>\fP
.br
\fC#include 'IrcObject\&.h'\fP
.br
\fC#include 'nethelper\&.h'\fP
.br
\fC#include 'irc_structs\&.h'\fP
.br
\fC#include 'irc_status\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBirc_connection_params\fP"
.br
.ti -1c
.RI "class \fBIrcConnection\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
