IrcConnection
NAME
IrcConnection -
SYNOPSIS
#include <IrcConnection.h>
Inherits IrcObject, and IrcObject.
Public Member Functions
IrcConnection (std::shared_ptr< IrcNetwork > network)
~IrcConnection ()
EIrcStatus AddChannel (const char *channel_name)
EIrcStatus AutoChangeNick ()
EIrcStatus Cleanup ()
EIrcStatus ConnectToServer ()
EIrcStatus DeleteChannel (const char *channel_name)
irc_activity & GetActivity ()
std::shared_ptr< IrcChannel > GetChannel (const char *channel_name)
std::string GetCurrentNickname () const
std::string GroupName () const
uint32_t Id () const
bool IsActive ()
bool IsConnecting ()
bool IsDisconnected ()
bool IsDisconnecting ()
std::string NetworkName () const
std::shared_ptr< IrcNetwork > Owner ()
EIrcStatus SendAway (const char *message=nullptr)
EIrcStatus SendBack ()
EIrcStatus SendCTCP (const char *target, const char *message)
EIrcStatus SendCTCPNotice (const char *destination, const char *message)
EIrcStatus SendInit ()
EIrcStatus SendInvite (const char *channel_name, const char *nickname)
EIrcStatus SendJoin (const char *channel_name, const char *channel_key=nullptr)
EIrcStatus SendKick (const char *channel_name, const char *nickname, const char *msg=nullptr)
EIrcStatus SendMode (const char *target, const char *mode)
EIrcStatus SendNick (const char *nickname)
EIrcStatus SendIdentify (const char *service, const char *pass)
EIrcStatus SendNotice (const char *target, const char *message)
EIrcStatus SendPart (const char *channel_name, const char *msg=nullptr)
EIrcStatus SendPrivmsg (const char *target, const char *privmsg)
EIrcStatus SendRaw (const char *data)
EIrcStatus SendQuit (const char *msg=nullptr)
EIrcStatus SendTopic (const char *channel_name, const char *message=nullptr)
EIrcStatus SendUser (const char *username, const uint16_t mode=8, const char *realname=nullptr)
EIrcStatus SetActiveChannel (const char *channel_name)
EIrcStatus Setup (std::shared_ptr< IrcNetwork > network, std::shared_ptr< config_server > server_config)
IrcConnection (IrcNetwork *parent_network)
~IrcConnection ()
bool AddChannel (const char *channel_name)
int32_t AutoChangeNick ()
void Cleanup ()
int32_t ConnectToServer ()
bool DeleteChannel (IrcChannel *channel)
irc_activity & GetActivity ()
IrcChannel * GetChannel (const char *channel_name)
std::string GetCurrentNickname () const
std::string GroupName () const
bool IsActive ()
bool IsConnecting ()
bool IsDisconnected ()
bool IsDisconnecting ()
std::string NetworkName () const
IrcNetwork * Owner ()
void SendAway (const char *message=nullptr)
void SendBack ()
void SendCTCP (const char *target, const char *message)
void SendCTCPNotice (const char *destination, const char *message)
void SendInit ()
void SendInvite (const char *channel_name, const char *nickname)
void SendJoin (const char *channel_name, const char *channel_key=nullptr)
void SendKick (const char *channel_name, const char *nickname, const char *msg=nullptr)
void SendMode (const char *target, const char *mode)
void SendNick (const char *nickname)
void SendIdentify (const char *service, const char *pass)
void SendNotice (const char *target, const char *message)
void SendPart (const char *channel_name, const char *msg=nullptr)
void SendPrivmsg (const char *target, const char *privmsg)
void SendRaw (const char *data)
void SendQuit (const char *msg=nullptr)
void SendTopic (const char *channel_name, const char *message=nullptr)
void SendUser (const char *username, const uint16_t mode=8, const char *realname=nullptr)
void SetActiveChannel (IrcChannel *channel)
bool Setup (IrcNetwork *network, std::shared_ptr< config_server > server_config)
Private Member Functions
NO_CLASS_ASSIGNMENT (IrcConnection)
NO_CLASS_COPY (IrcConnection)
EIrcStatus AddToRecvQueue (const char *data)
EIrcStatus AddToSendQueue (const char *data)
EIrcStatus EraseChannelList ()
uint32_t EstablishConnection ()
EIrcStatus SendBypass (const char *data_format,...)
NO_CLASS_ASSIGNMENT (IrcConnection)
NO_CLASS_COPY (IrcConnection)
bool AddToRecvQueue (const char *data)
bool AddToSendQueue (const char *data)
void EraseChannelList ()
uint32_t EstablishConnection ()
int32_t SendBypass (const char *data_format,...)
Static Private Member Functions
static uint32_t __stdcall ExecEstablishConnection (void *thisptr)
static uint32_t __stdcall ExecEstablishConnection (void *thisptr)
Private Attributes
uint32_t _state
time_t _last_data
time_t _lag_sent
uint64_t _bytes_recv
uint64_t _bytes_sent
std::mutex _mutex
std::queue< std::string > _recv_queue
std::queue< std::string > _send_queue
std::set< std::string > _channel_list
std::weak_ptr< IrcNetwork > _owner
std::vector< std::string > _cap_ack
std::vector< std::string > _cap_nak
std::vector< std::string > _cap_ls
irc_activity _activity
irc_connection_params _params
uint32_t _id
uint32_t _thread
std::set< IrcChannel * > _channel_list
IrcNetwork * _parent_network
Friends
class IrcParser
class IrcNetwork
Additional Inherited Members
Detailed Description
Definition at line 76 of file IrcConnection.h.
Constructor & Destructor Documentation
IrcConnection::IrcConnection (std::shared_ptr< IrcNetwork >network)
Definition at line 62 of file IrcConnection.cc.
References CS_Disconnected.
  : _owner(network)
{
#if defined(USING_OPENSSL_NET)
        _socket = nullptr;
        _ssl = nullptr;
        _ssl_context = nullptr;
#endif
        _bytes_recv = 0;
        _bytes_sent = 0;
        _state = CS_Disconnected;
        _last_data = 0;
        _lag_sent = 0;
        _thread = 0;
        // and the parameters
#if !defined(USING_BOOST_NET)
        memset(&_params.ip, 0, sizeof(_params.ip));
        memset(&_params.sa, 0, sizeof(_params.sa));
#endif
}
IrcConnection::~IrcConnection ()
Definition at line 90 of file IrcConnection.cc.
References IrcParser::Cleanup().
{
        Cleanup();
}
IrcConnection::IrcConnection (IrcNetwork *parent_network)
Definition at line 60 of file bak/IrcConnection.cc.
References IrcObject::_irc_engine, CS_Disconnected, and IrcEngine::NotifyNewConnection().
  : _parent_network(parent_network)
{
#if defined(USING_OPENSSL)
        _socket = nullptr;
        _ssl = nullptr;
        _ssl_context = nullptr;
#endif
        _bytes_recv = 0;
        _bytes_sent = 0;
        _state = CS_Disconnected;
        _last_data = 0;
        _lag_sent = 0;
        _thread = 0;
        // and the parameters
#if !defined(USING_POCO_NET)
        memset(&_params.ip, 0, sizeof(_params.ip));
        memset(&_params.sa, 0, sizeof(_params.sa));
#endif
        /* must be a better way of doing this.. (rtti/dynamic_cast does NOT work
         * in IrcEngine::NotifyNewObject) */
        _irc_engine->NotifyNewConnection(this);
}
IrcConnection::~IrcConnection ()
Member Function Documentation
bool IrcConnection::AddChannel (const char *channel_name)
Allocates a new IrcChannel, identified as channel_name, linking it into the connections channel list.
To retrieve it, call GetChannel()
Parameters:
channel_name The channel name to add to the channel list
Returns:
If the channel is added to the connection list, the function returns true; otherwise false
bool IrcConnection::AddChannel (const char *channel_name)
Allocates a new IrcChannel, identified as channel_name, linking it into the connections channel list.
To retrieve it, call GetChannel()
Parameters:
channel_name The channel name to add to the channel list
Returns:
If the channel is added to the connection list, the function returns true; otherwise false
Definition at line 98 of file IrcConnection.cc.
References IrcObject::_irc_engine, IrcFactory::CreateIrcChannel(), IrcEngine::Factory(), fg_red(), IrcPool::GetConnection(), InvalidParameter, OK, and IrcEngine::Pools().
Referenced by IrcParser::HandleJoin().
{
        if ( channel_name == nullptr )
                goto no_name;
        {
                std::lock_guard<std::mutex> lock(_mutex);
                
                if ( _irc_engine->Factory()->CreateIrcChannel(
                        _irc_engine->Pools()->GetConnection(_id), channel_name)
                        != nullptr )
                {
                        _channel_list.insert(channel_name);
                }
        }
        return EIrcStatus::OK;
no_name:
        std::cerr << fg_red << "The supplied channel name was a nullptr\n";
        return EIrcStatus::InvalidParameter;
}
bool IrcConnection::AddToRecvQueue (const char *data) [private]
Adds the supplied data to the connections receiving queue, ready to be picked up aned processed by the parsing thread.
Parameters:
data The raw text to have received
Returns:
Returns true if the data is added to the pending queue, otherwise false is returned
bool IrcConnection::AddToRecvQueue (const char *data) [private]
Adds the supplied data to the connections receiving queue, ready to be picked up aned processed by the parsing thread.
Parameters:
data The raw text to have received
Returns:
Returns true if the data is added to the pending queue, otherwise false is returned
Definition at line 126 of file IrcConnection.cc.
References Debug, fg_red(), InvalidData, InvalidParameter, LOG, MAX_BUF_IRC_MSG, and OK.
{
        uint32_t length = 0;
        if ( data == nullptr )
                goto no_data;
        length = strlen(data);
        /* if truncation occurs, the received message is longer than the known
         * IRC RFC limit, and is therefore invalid. We have already stripped the
         * CR-LF so do not include that in the size check */
        if ( length >= MAX_BUF_IRC_MSG )
                goto data_too_long;
        if ( length < 2 )
                goto data_too_short;
        {
                std::lock_guard<std::mutex> lock(_mutex);
                // append the new data to the receiving queue as a copy
                _recv_queue.push(data);
        }
        // Debug log
        LOG(ELogLevel::Debug) << "Recv on " << this << ": " << data << "\n";
        return EIrcStatus::OK;
no_data:
        std::cerr << fg_red << "The supplied data was a nullptr\n";
        return EIrcStatus::InvalidParameter;
data_too_long:
        std::cerr << fg_red << "The supplied data exceeded the maximum buffer size for an IRC message\n";
        return EIrcStatus::InvalidData;
data_too_short:
        std::cerr << fg_red << "The supplied data was too short for a valid IRC message\n";
        return EIrcStatus::InvalidData;
}
bool IrcConnection::AddToSendQueue (const char *data) [private]
Adds the supplied data to the connections send queue, ready for sending to the server. The queue is processed by the dedicated thread automatically, keeping within the bounds of flood protection.
The trailing carriage return and linefeed are added BY this function, so there is no need to supply it as part of the data.
Parameters:
data The raw text to send
Return values:
retval true if the data is added to the pending queue
false on any failure; no data added to the pending queue
bool IrcConnection::AddToSendQueue (const char *data) [private]
Adds the supplied data to the connections send queue, ready for sending to the server. The queue is processed by the dedicated thread automatically, keeping within the bounds of flood protection.
The trailing carriage return and linefeed are added BY this function, so there is no need to supply it as part of the data.
Parameters:
data The raw text to send
Return values:
retval true if the data is added to the pending queue
false on any failure; no data added to the pending queue
Todo
existing functionality is temporary - flood protection!
Definition at line 171 of file IrcConnection.cc.
References OK.
{
        SendBypass("%s\r\n", data);
        return EIrcStatus::OK;
}
int32_t IrcConnection::AutoChangeNick ()
Sends a request to the connected server to choose the next nickname in the users profile.
Returns:
If no more nicknames are available, EC_NoMoreNicks is returned, but the counter is reset (so it can be called continuously again). EC_Success is returned when the nick is changed.
int32_t IrcConnection::AutoChangeNick ()
Sends a request to the connected server to choose the next nickname in the users profile.
Returns:
If no more nicknames are available, EC_NoMoreNicks is returned, but the counter is reset (so it can be called continuously again). EC_Success is returned when the nick is changed.
Definition at line 185 of file IrcConnection.cc.
References fg_red(), config_profile::nicknames, NoMoreNicks, NoOwner, and OK.
Referenced by IrcParser::Handle432(), and IrcParser::Handle433().
{
        config_profile* profile;
        std::string next_nick;
        bool use = false;
        std::shared_ptr<IrcNetwork> network = _owner.lock();
        if ( network == nullptr )
                goto no_parent;
        profile = &network->_profile_config;
        for ( auto n : profile->nicknames )
        {
                if ( use )
                {
                        next_nick = n;
                        break;
                }
                if ( n.compare(network->ClientNickname()) == 0 )
                {
                        use = true;
                }
        }
        if ( next_nick.empty() )
        {
                // if use is true, then the current nick was the final one
                if ( use )
                        goto no_more_nicks;
                // otherwise, we have a non-profile nick; so use the first again
                next_nick = profile->nicknames[0];
        }
        network->_client.nickname = next_nick;
        SendNick(next_nick.c_str());
        return EIrcStatus::OK;
no_parent:
        std::cerr << fg_red << "The supplied connections parent network was a nullptr\n";
        return EIrcStatus::NoOwner;
no_more_nicks:
        std::cerr << fg_red << "There are no more nicknames left to try\n";
        return EIrcStatus::NoMoreNicks;
}
void IrcConnection::Cleanup ()
Cleans up the connection, freeing any allocated memory, closing any sockets and shutting down SSL, if in usage.
This will not destroy the connection object itself, allowing it to be reused for another connection (i.e. reconnecting to the same server)
void IrcConnection::Cleanup ()
Cleans up the connection, freeing any allocated memory, closing any sockets and shutting down SSL, if in usage.
This will not destroy the connection object itself, allowing it to be reused for another connection (i.e. reconnecting to the same server)
Definition at line 236 of file IrcConnection.cc.
References CS_Active, CS_Disconnected, CS_Disconnecting, fg_red(), OK, runtime, and Runtime::WaitThenKillThread().
{
        // the order of cleanup here should be the most stable/suitable
        if ( _state & CS_Active )
        {
                /* we can't use _owner->_client.quit_reason.c_str() here,
                 * as the parent network has already been deleted if we're closing
                 * the application. Yes, we can copy it; or move the structs into
                 * this class; until we're fully aware of all the intricate bits,
                 * yes send a quit without a message. Not that important... */
                SendQuit();
                _state = CS_Disconnecting;
        }
        /* we can safely wipe out the channel list while we're waiting for the
         * server to close the connection and the thread to return */
        EraseChannelList();
#if 0 // Code Removed: now handled by Runtime
#if defined(_WIN32)
        if ( _thread != nullptr && _thread != INVALID_HANDLE_VALUE )
        {
                DWORD exit_code = 0;
                /* give the thread 1 second to close */
                WaitForSingleObject(_thread, 1000);
                if ( !GetExitCodeThread(_thread, &exit_code) || exit_code == STILL_ACTIVE )
                {
                        /* tried to let the thread go peacefully - kill it */
                        if ( !TerminateThread(_thread, EXIT_FAILURE) )
                        {
                                /* termination failed - we're very likely to crash if the
                                 * thread tries to resume at the blocking BIO_read, since
                                 * we're about to free the ssl & class data.. */
                                std::cerr << fg_red << "Failed to terminate the connection thread; Win32 error " << GetLastError();
                        }
                }
                /* we want nothing to do with the thread anymore; we've tried to kill
                 * it (even if it succeeded) and so we can close the handle, and the
                 * system should cleanup all the associated resources for it when it is
                 * able to do so. */
                CloseHandle(_thread);
                _thread = nullptr;
                _thread_id = 0;
        }
#elif defined(__linux__) || defined(BSD)
        /* this cleanup code has been copied and used in the IrcParser and
         * IrcAntiTimeout classes; modifications should be duplicated there;
         * either that or we call a function that does it....recommended! */
        if ( _thread != 0 )
        {
                s32 ret;
                timespec wait_time;
                wait_time.tv_sec = 1;
                /* wait 1 second for the thread to finish up */
                ret = pthread_timedjoin_np(_thread, nullptr, &wait_time);
                if ( ret == ETIMEDOUT )
                {
                        /* tried to let the thread go peacefully - stop it */
                        pthread_cancel(_thread);
                        /* wait again */
                        ret = pthread_timedjoin_np(_thread, nullptr, &wait_time);
                        if ( ret == ETIMEDOUT )
                        {
                                std::cout << fg_red << "Thread " << _thread << " has been forcibly killed after failing to finish on request\n";
                                /* second timeout, even after cancelling. Just
                                 * kill it and live with any resource leaks */
                                pthread_kill(_thread, SIGKILL);
                        }
                        else if ( ret != 0 )
                        {
                                std::cout << fg_red << "Received errno " << ret << " after waiting for thread " << _thread << " to finish\n";
                        }
                }
                _thread = 0;
        }
#endif
#endif // Code Removed
#if defined(USING_OPENSSL_NET)
        /* the EstablishConnection thread will still be running (assuming we
         * actually connected) at this stage; and since it's blocking on the BIO
         * the only way we can sync it is to delete it. As such, perform the
         * deletion, and **wait** for the thread to finish before returning from
         * this function. */
        if ( _socket != nullptr )
        {
                if ( _ssl != nullptr )
                {
                        SSL_shutdown(_ssl.release());
                        SSL_CTX_free(_ssl_context.release());
                        // frees the connection->socket too, no need to reset
                        SSL_free(_ssl.release());
                        _ssl = nullptr;
                        _ssl_context = nullptr;
                }
                else
                {
                        BIO_reset(_socket.get());
                        BIO_free(_socket.release());
                }
                _socket = nullptr;
        }
#endif // USING_OPENSSL_NET
        runtime.WaitThenKillThread(_thread);
        // theoretically possible for a queue to add entries inbetween above
        while ( !_send_queue.empty() )
                _send_queue.pop();
        while ( !_recv_queue.empty() )
                _recv_queue.pop();
        _last_data = 0;
        _lag_sent = 0;
        _state = CS_Disconnected;
        return EIrcStatus::OK;
}
int32_t IrcConnection::ConnectToServer ()
Todo
fixme Physically connects to the server set within the connection. This is done within , which includes performing a DNS lookup and populating the sockaddr structures. This function makes the first real outbound call, and on success, creates a thread to parse any data received.
Note:
Currently hardcoded to use OpenSSL for a connection without any preprocessor guards - to change if we want to support other SSL implementations. Until then, this will cause a compile error if not USING_OPENSSL
Returns:
If an outbound connection is successfully made, and a thread created to process it, the function returns 0.
Any failure causes the function to return -1
If the connection is already active, the function returns 1
int32_t IrcConnection::ConnectToServer ()
Todo
fixme Physically connects to the server set within the connection. This is done within , which includes performing a DNS lookup and populating the sockaddr structures. This function makes the first real outbound call, and on success, creates a thread to parse any data received.
Note:
Currently hardcoded to use OpenSSL for a connection without any preprocessor guards - to change if we want to support other SSL implementations. Until then, this will cause a compile error if not USING_OPENSSL
Returns:
If an outbound connection is successfully made, and a thread created to process it, the function returns 0.
Any failure causes the function to return -1
If the connection is already active, the function returns 1
Definition at line 580 of file IrcConnection.cc.
{
# error No implementation exists for this function with current project settings
}
bool IrcConnection::DeleteChannel (IrcChannel *channel)
Deletes the supplied channel. If it is still a part of the channel list, it will be unlinked first.
See Also:
GetChannel(), RemoveChannel()
Parameters:
channel The IrcChannel to delete
Returns:
Returns true if the channel is deleted; otherwise false
Definition at line 632 of file bak/IrcConnection.cc.
References _channel_list, IrcObject::_irc_engine, _mutex, IrcFactory::DeleteIrcObject(), IrcEngine::Factory(), and IrcChannel::Name().
{
        bool found = false;
        if ( channel == nullptr )
                goto no_channel;
        {
                std::lock_guard<std::mutex> lock(_mutex);
                for ( auto c : _channel_list )
                {
                        if ( c == channel )
                        {
                                found = true;
                                _irc_engine->Factory()->DeleteIrcObject(channel);
                                _channel_list.erase(c);
                                // must break out of the loop, iterator invalid
                                break;
                        }
                }
        }
        if ( !found )
        {
                std::cerr << fg_red << "The supplied channel (" << channel->Name() << ") was not found in the channel list\n";
                return false;
        }
        return true;
no_channel:
        std::cerr << fg_red << "The supplied channel was a nullptr\n";
        return false;
}
EIrcStatus IrcConnection::DeleteChannel (const char *channel_name)
Deletes the supplied channel. If it is still a part of the channel list, it will be unlinked first.
See Also:
GetChannel(), RemoveChannel()
Parameters:
channel The IrcChannel to delete
Returns:
Returns true if the channel is deleted; otherwise false
Definition at line 641 of file IrcConnection.cc.
References IrcObject::_irc_engine, ObjectPool< T >::FreeObject(), IrcPool::GetChannel(), InvalidParameter, IrcPool::IrcChannels(), ObjectNotFound, OK, and IrcEngine::Pools().
{
        bool found = false;
        if ( channel_name == nullptr )
                goto no_channel;
        {
                std::lock_guard<std::mutex> lock(_mutex);
                for ( auto c : _channel_list )
                {
                        if ( c == channel_name )
                        {
                                found = true;
                                _irc_engine->Pools()->IrcChannels()->FreeObject(
                                        _irc_engine->Pools()->GetChannel(_id, channel_name)
                                );
                                _channel_list.erase(channel_name);
                                // must break out of the loop, iterator invalid
                                break;
                        }
                }
        }
        if ( !found )
                goto not_found;
        return EIrcStatus::OK;
no_channel:
        std::cerr << fg_red << "The supplied channel was a nullptr\n";
        return EIrcStatus::InvalidParameter;
not_found:
        std::cerr << fg_red << "The supplied channel (" << channel_name << ") was not found in the channel list\n";
        return EIrcStatus::ObjectNotFound;
}
void IrcConnection::EraseChannelList () [private]
Wipes out the linked list containing the IRC channels.
Only expected to be executed when the destructor or Cleanup() are called.
void IrcConnection::EraseChannelList () [private]
Wipes out the linked list containing the IRC channels.
Only expected to be executed when the destructor or Cleanup() are called.
Definition at line 684 of file IrcConnection.cc.
References IrcObject::_irc_engine, ObjectPool< T >::FreeObject(), IrcPool::IrcChannels(), OK, and IrcEngine::Pools().
Referenced by IrcParser::HandleQuit().
{
        std::lock_guard<std::mutex> lock(_mutex);
        // all channels should be at reference count 1 here
        for ( auto c : _channel_list )
        {
                _irc_engine->Pools()->IrcChannels()->FreeObject(GetChannel(c.c_str()));
        }
        _channel_list.clear();
        return EIrcStatus::OK;
}
uint32_t IrcConnection::EstablishConnection () [private]
The thread function that constantly receives data and adds it to the receiving queue. Automatically sends data (initial connection, PING and PONGs) where applicable.
Only called through ExecEstablishConnection() as part of a new thread.
Returns:
Always returns 0.
See Also:
ExecEstablishConnection, Runtime::CreateThread
uint32_t IrcConnection::EstablishConnection () [private]
The thread function that constantly receives data and adds it to the receiving queue. Automatically sends data (initial connection, PING and PONGs) where applicable.
Only called through ExecEstablishConnection() as part of a new thread.
Returns:
Always returns 0.
See Also:
ExecEstablishConnection, Runtime::CreateThread
Definition at line 702 of file IrcConnection.cc.
References IrcObject::_irc_engine, CS_Disconnected, IrcPool::GetConnection(), LN_NewData, MAX_BUF_IRC_MSG_CRLF, IrcEngine::NotifyListeners(), IrcEngine::Parser(), IrcEngine::Pools(), runtime, SLEEP_SECONDS, str_token(), strlcat(), strlcpy(), Runtime::ThreadStopping(), and IrcParser::TriggerSync().
{
        char buffer[MAX_BUF_IRC_MSG_CRLF];
        char store_buffer[MAX_BUF_IRC_MSG_CRLF] = { '\0' };
        char delim[] = "\n";
        char* last = nullptr;
        char* p = nullptr;
        int32_t buffer_read = 0;
        uint32_t len;
        uint32_t max_len = sizeof(buffer) - 1;
        if ( &_owner == nullptr )
                goto invalid_parent;
        // ConnectToServer must have opened the connection
        if ( !IsConnecting() )
                goto invalid_state;
        // store the thread id so the class can close it cleanly
#if defined(_WIN32)
        _thread = GetCurrentThreadId();
#else
        _thread = pthread_self();
#endif
        try
        {
        /*
         * Different servers have different first responses. For example, Rizon
         * brings back the following:
         | :irc.shakeababy.net 439 * :Please wait while we process your connection.
         | :irc.shakeababy.net NOTICE AUTH :*** Looking up your hostname...
         | ...
         * Whereas connecting to irc.freenode.net results in:
         | :calvino.freenode.net NOTICE * :*** Looking up your hostname...
         | ...
         * ngIRCd even WAITS for US to send the first data!
         |
         * This makes it difficult to predict and determine at what stages we
         * should proceed with sending the connection data, and handling an event
         * when we connect. The only guarantee is that 001 will be received when
         * the connection is successful.
         *
         * Since I discovered ngIRCd does not send any data on initial connection
         * (at least by default), then we have to go through our init procedure
         * before the first read, otherwise it'll simply timeout, since the parse
         * function never gets called. As such, we have to maintain this for all
         * the other servers too!
         */
        SendInit();
        while ( IsActive() || IsConnecting() )
        {
#if defined(USING_OPENSSL_NET)
                if (( buffer_read = BIO_read(_socket.get(), buffer, max_len)) == 0 )
                {
                        if ( !BIO_should_retry(_socket.get()) )
                                goto bio_abort_0;
                        else
                        {
                                // sleep for a second, then retry
                                SLEEP_SECONDS(1);
                                continue;
                        }
                }
                else if ( buffer_read < 0 )
                {
                        if ( _socket != nullptr && BIO_should_retry(_socket.get()) )
                        {
                                continue;
                        }
                        goto bio_abort;
                }
                else
#elif defined(USING_BOOST_NET)
                if ( 0 )
                {
                }
#else
# error No implementation exisits for this function with current project settings
#endif
                {
                        // successfully retrieved data
                        _last_data = time(NULL);
                        _bytes_recv += buffer_read;
                        /* ensure the buffer is nul-terminated; only this thread accesses
                         * this buffer, copies are made for later usage. */
                        buffer[buffer_read] = '\0';
                        /* if it's a PING, reply straight away, bypassing the
                         * queue; otherwise, add it. More efficient checking
                         * it here than allocating memory for the queue */
                        if ( strncmp(buffer, "PING :", 6) == 0 )
                        {
                                // Turn PING into PONG
                                buffer[1] = 'O';
                                SendBypass("%s", buffer);
                                continue;
                        }
                        /* we don't handle PONG's here (replies from our PING LAG12345) as it
                         * contains the server prefix like a normal message */
                        /* reuse the same buffer that will be used for storing the 'prev'
                         * data, and make a copy of each instance. This eases debugging,
                         * and benefits the add_to_recv_queue functionality by making it
                         * do less work, at the cost of copying the string here - which
                         * will still be faster. */
                        p = str_token(buffer, delim, &last);
                        /* !!NOTE:: the str_token call will nul the newline
                         * character, leaving only the linefeed behind, which we
                         * check for (and remove) */
                        while ( p != nullptr )
                        {
                                if ( store_buffer[0] != '\0' )
                                {
                                        // linefeed is 1 before nul
                                        len = strlen(p);
                                        if ( len < 1 || p[len-1] != '\r' )
                                                goto invalid_data;
                                        // nul the linefeed
                                        p[len-1] = '\0';
                                        // append the rest of the string to the previous buffer
                                        strlcat(store_buffer, p, sizeof(store_buffer));
                                        // and add it to the queue as normal
                                        AddToRecvQueue(store_buffer);
                                        store_buffer[0] = '\0';
                                }
                                else
                                {
                                        len = strlcpy(store_buffer, p, sizeof(store_buffer));
                                        /* if linefeed is the last character, we've received a full
                                         * message, otherwise retain it in the store_buffer ready
                                         * for the next batch of data */
                                        if ( len > 1 && store_buffer[len-1] == '\r' )
                                        {
                                                // remove the linefeed
                                                store_buffer[len-1] = '\0';
                                                // add the whole string to the queue
                                                AddToRecvQueue(store_buffer);
                                                // whole message, start fresh with next iteration
                                                store_buffer[0] = '\0';
                                        }
                                }
                                p = str_token(nullptr, delim, &last);
                        }
                        /* do the notifications here, on end of data instance,
                         * rather than AddToRecvQueue - potential race condition
                         * with the queues otherwise? */
                        // notify the pre-parse listeners there is new data available
                        _irc_engine->NotifyListeners(LN_NewData, _irc_engine->Pools()->GetConnection(_id));
                        // trigger the parser
                        _irc_engine->Parser()->TriggerSync();
                }
        } // end while
        }
        catch ( std::exception& e )
        {
                std::cerr << fg_red << "Caught an exception; " << e.what() << "\n";
        }
        catch ( ... )
        {
                std::cerr << fg_red << "Caught an unhandled exception\n";
        }
        goto finish;
invalid_parent:
        std::cerr << fg_red << "The supplied connections parent_network was a nullptr\n";
        goto finish;
invalid_data:
        std::cerr << fg_red << "The received data was invalid\n";
        goto finish;
invalid_state:
        std::cerr << fg_red << "The connection state is invalid\n";
        goto finish;
#if defined(USING_OPENSSL_NET)
bio_abort:
        // as this thread blocks on the socket, it can be deleted legitimately
        if ( _socket != nullptr )
                std::cerr << fg_red << "BIO_should_retry returned false\n";
        goto finish;
bio_abort_0:
        if ( _socket != nullptr )
                std::cerr << fg_red << "BIO_should_retry returned false\n";
        goto finish;
#elif defined(USING_BOOST_NET)
#else
        // non-OpenSSL equivalent
#endif
finish:
        _state = CS_Disconnected;
#if defined(_WIN32)
        runtime.ThreadStopping(GetCurrentThreadId(), __FUNCTION__);
#else
        runtime.ThreadStopping(pthread_self(), __FUNCTION__);
#endif
        return 0;
}
static uint32_t __stdcall IrcConnection::ExecEstablishConnection (void *thisptr) [static], [private]
Used for creating a thread for the EstablishConnection() function. Since we reside in a C++ class, this is necessary to be able to have it called via a new thread.
Warning:
Do not call manually; the internal functions and other classes will do all necessary preparation, and call Runtime::CreateThread, which in turn will execute this function. As a result, no safety checks are performed.
Runtime::CreateThread is a friend in order to call this function.
Parameters:
thisptr A pointer to the IrcConnection class
Returns:
Always returns 0. Whatever happens in the called function stays unique and separate.
See Also:
Runtime::CreateThread, IrcParser::ExecParser
uint32_t IrcConnection::ExecEstablishConnection (void *thisptr) [static], [private]
Used for creating a thread for the EstablishConnection() function. Since we reside in a C++ class, this is necessary to be able to have it called via a new thread.
Warning:
Do not call manually; the internal functions and other classes will do all necessary preparation, and call Runtime::CreateThread, which in turn will execute this function. As a result, no safety checks are performed.
Runtime::CreateThread is a friend in order to call this function.
Parameters:
thisptr A pointer to the IrcConnection class
Returns:
Always returns 0. Whatever happens in the called function stays unique and separate.
See Also:
Runtime::CreateThread, IrcParser::ExecParser
Definition at line 929 of file IrcConnection.cc.
{
#if defined(_WIN32)
        return ((IrcConnection*)connection)->EstablishConnection();
#else
        ((IrcConnection*)connection)->EstablishConnection();
        return nullptr;
#endif
}
irc_activity& IrcConnection::GetActivity () [inline]
Gets the irc_activity struct for this connection.
Only called within IrcEngine as a means of getting the struct to pass to the listeners. As such, the lifetime of the returned reference is 'guaranteed' to be sufficient for as long as the listener functions are being run, and is also the only point at which the data within the struct should be accurate for usage.
Returns:
A reference to the irc_activity if returned
Definition at line 348 of file bak/IrcConnection.h.
        { return _activity; }
irc_activity& IrcConnection::GetActivity () [inline]
Gets the irc_activity struct for this connection.
Only called within IrcEngine as a means of getting the struct to pass to the listeners. As such, the lifetime of the returned reference is 'guaranteed' to be sufficient for as long as the listener functions are being run, and is also the only point at which the data within the struct should be accurate for usage.
Returns:
A reference to the irc_activity is returned
Definition at line 354 of file IrcConnection.h.
Referenced by IrcParser::Handle001(), IrcParser::Handle002(), IrcParser::Handle003(), IrcParser::Handle004(), IrcParser::Handle005(), IrcParser::Handle332(), IrcParser::Handle333(), IrcParser::Handle353(), IrcParser::Handle366(), IrcParser::Handle372(), IrcParser::Handle375(), IrcParser::Handle376(), IrcParser::Handle432(), IrcParser::Handle433(), IrcParser::HandleCap(), IrcParser::HandleInvite(), IrcParser::HandleJoin(), IrcParser::HandleKick(), IrcParser::HandleKill(), IrcParser::HandleMode(), IrcParser::HandleNick(), IrcParser::HandleNotice(), IrcParser::HandlePart(), IrcParser::HandlePong(), IrcParser::HandlePrivmsg(), IrcParser::HandleQuit(), IrcParser::HandleTopic(), and IrcEngine::NotifyListeners().
        { return _activity; }
IrcChannel* IrcConnection::GetChannel (const char *channel_name)
Gets the IrcChannel object from the specified connection, whose name matches channel_name.
Will not generate an error if the specified channel is not found, as this can be used for a simple search; raise your own error if this is undesired.
Warning:
Increments the reference counter for the channel; you must call Dereference on it when finished using it!
Parameters:
channel_name The name of the channel to locate
Returns:
If the channel is not found, a nullptr is returned, otherwise it is a pointer to the IrcChannel called channel_name
IrcChannel * IrcConnection::GetChannel (const char *channel_name)
Gets the IrcChannel object from the specified connection, whose name matches channel_name.
Will not generate an error if the specified channel is not found, as this can be used for a simple search; raise your own error if this is undesired.
Warning:
Increments the reference counter for the channel; you must call Dereference on it when finished using it!
Parameters:
channel_name The name of the channel to locate
Returns:
If the channel is not found, a nullptr is returned, otherwise it is a pointer to the IrcChannel called channel_name
Definition at line 944 of file IrcConnection.cc.
References IrcObject::_irc_engine, IrcPool::GetChannel(), and IrcEngine::Pools().
Referenced by IrcParser::Handle332(), IrcParser::Handle333(), IrcParser::Handle353(), IrcParser::Handle366(), IrcParser::HandleJoin(), IrcParser::HandleKick(), IrcParser::HandleMode(), IrcParser::HandlePart(), IrcParser::HandlePrivmsg(), and IrcParser::HandleTopic().
{
        if ( channel_name == nullptr )
                goto invalid_name;
        {
                std::lock_guard<std::mutex> lock(_mutex);
                for ( auto c : _channel_list )
                {
                        if ( strcmp(c.c_str(), channel_name) == 0 )
                        {
                                return _irc_engine->Pools()->GetChannel(_id, channel_name);
                        }
                }
        }
        /* channel not found. Do not generate an error; this can be (and is used
         * for) locating if a channel exists or not; the caller must raise an
         * error if it's required */
        return nullptr;
invalid_name:
        std::cerr << fg_red << "The supplied channel name was a nullptr\n";
        return nullptr;
}
std::string IrcConnection::GetCurrentNickname () const
Retrieves a copy of the current nickname in usage for the network connection.
Returns:
The copied string is returned, so the memory will not be invalidated if the nickname changes while this is still held
std::string IrcConnection::GetCurrentNickname () const
Retrieves a copy of the current nickname in usage for the network connection.
Returns:
The copied string is returned, so the memory will not be invalidated if the nickname changes while this is still held
Definition at line 976 of file IrcConnection.cc.
Referenced by IrcParser::HandleKill().
{
        std::lock_guard<std::mutex> lock(_mutex);
        std::shared_ptr<IrcNetwork> net = _owner.lock();
        return net == nullptr ? "" : net->_client.nickname;
}
std::string IrcConnection::GroupName () const
Retrieves the group name of the network, as set by the user.
See Also:
IrcNetwork::GroupName
Returns:
A copy of the group network name
std::string IrcConnection::GroupName () const
Retrieves the group name of the network, as set by the user.
See Also:
IrcNetwork::GroupName
Returns:
A copy of the group network name
Definition at line 986 of file IrcConnection.cc.
{
        std::lock_guard<std::mutex> lock(_mutex);
        std::shared_ptr<IrcNetwork> net = _owner.lock();
        return net == nullptr ? "" : net->_group_name;
}
uint32_t IrcConnection::Id () const [inline]
Definition at line 404 of file IrcConnection.h.
        {
                return _id;
        }
bool IrcConnection::IsActive ()
Determines if the connection is currently pending (i.e. in the state between connecting to the server, and being actually connected to it.
Returns:
Returns true if the connection is in the 'connected' state, otherwise returns false
bool IrcConnection::IsActive ()
Determines if the connection is currently pending (i.e. in the state between connecting to the server, and being actually connected to it.
Returns:
Returns true if the connection is in the 'connected' state, otherwise returns false
Definition at line 996 of file IrcConnection.cc.
References CS_Active.
Referenced by IrcParser::Handle005(), and IrcParser::HandleNotice().
{
        return (_state & CS_Active) != 0;
}
bool IrcConnection::IsConnecting ()
Determines if the connection is currently pending (i.e. in the state between connecting to the server, and being actually connected to it.
Returns:
Returns true if the connection is in the 'connecting' state, otherwise returns false
bool IrcConnection::IsConnecting ()
Determines if the connection is currently pending (i.e. in the state between connecting to the server, and being actually connected to it.
Returns:
Returns true if the connection is in the 'connecting' state, otherwise returns false
Definition at line 1004 of file IrcConnection.cc.
References CS_Connecting.
{
        return (_state & CS_Connecting) != 0;
}
bool IrcConnection::IsDisconnected ()
Determines if the connection is currently in a complete disconnected state - so is ready for a reconnect call, if needed.
Returns:
Returns true if the connection is in the 'disconnected' state, otherwise returns false
bool IrcConnection::IsDisconnected ()
Determines if the connection is currently in a complete disconnected state - so is ready for a reconnect call, if needed.
Returns:
Returns true if the connection is in the 'disconnected' state, otherwise returns false
Definition at line 1012 of file IrcConnection.cc.
References CS_Disconnected.
{
        return (_state & CS_Disconnected) != 0;
}
bool IrcConnection::IsDisconnecting ()
Determines if the connection is currently pending (i.e. in the state between connecting to the server, and being actually connected to it)
Returns:
Returns true if the connection is in the 'disconnecting' state, otherwise returns false
bool IrcConnection::IsDisconnecting ()
Determines if the connection is currently pending (i.e. in the state between connecting to the server, and being actually connected to it)
Returns:
Returns true if the connection is in the 'disconnecting' state, otherwise returns false
Definition at line 1020 of file IrcConnection.cc.
References CS_Disconnecting.
{
        return (_state & CS_Disconnecting) != 0;
}
std::string IrcConnection::NetworkName () const
Retrieves the name of the network, as reported within its ISUPPORT response.
See Also:
IrcNetwork::Name
Returns:
A copy of the server network name; if ISUPPORT (005) has not yet being received & processed, the string will be empty.
std::string IrcConnection::NetworkName () const
Retrieves the name of the network, as reported within its ISUPPORT response.
See Also:
IrcNetwork::Name
Returns:
A copy of the server network name; if ISUPPORT (005) has not yet being received & processed, the string will be empty.
Definition at line 1028 of file IrcConnection.cc.
{
        std::lock_guard<std::mutex> lock(_mutex);
        std::shared_ptr<IrcNetwork> net = _owner.lock();
        return net == nullptr ? "" : net->_server.network;
}
IrcConnection::NO_CLASS_ASSIGNMENT (IrcConnection) [private]
IrcConnection::NO_CLASS_ASSIGNMENT (IrcConnection) [private]
IrcConnection::NO_CLASS_COPY (IrcConnection) [private]
IrcConnection::NO_CLASS_COPY (IrcConnection) [private]
IrcNetwork* IrcConnection::Owner ()
Retrieves the pointer for the IrcNetwork that owns this connection.
Warning:
Increments the reference counter for the network; you must call Dereference on it when finished using it!
Return values:
A pointer to an IrcNetwork
IrcNetwork * IrcConnection::Owner ()
Retrieves the pointer for the IrcNetwork that owns this connection.
Warning:
Increments the reference counter for the network; you must call Dereference on it when finished using it!
Return values:
A pointer to an IrcNetwork
Definition at line 1038 of file IrcConnection.cc.
{
        return _owner.lock();
}
void IrcConnection::SendAway (const char *message = nullptr)
Sends a message to the server to set our 'AWAY' state.
Parameters:
message The message to report back
void IrcConnection::SendAway (const char *message = nullptr)
Sends a message to the server to set our 'AWAY' state.
Parameters:
message The message to report back
Definition at line 1046 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( message != nullptr )
        {
                str_format(buffer, sizeof(buffer),
                        "AWAY :%s",
                        message);
                return AddToSendQueue(buffer);
        }
        else
        {
                return AddToSendQueue("AWAY : ");
        }
}
void IrcConnection::SendBack ()
Sends a message to the server to clear a previously set 'AWAY' state.
void IrcConnection::SendBack ()
Sends a message to the server to clear a previously set 'AWAY' state.
Definition at line 1069 of file IrcConnection.cc.
{
        // unset our away status
        return AddToSendQueue("AWAY");
}
int32_t IrcConnection::SendBypass (const char *data_format, ...) [private]
Sends data across the wire through the socket, without doing any form of flood protection - the data is sent immediately.
Called by AddToSendQueue after flood protection has been taken into account.
Parameters:
data_format The format-string of the data to send
... Variable number of parameters as determined within data_format
Returns:
The return value is that of BIO_puts. Error handling is already processed when the function returns, if necessary.
int32_t IrcConnection::SendBypass (const char *data_format, ...) [private]
Sends data across the wire through the socket, without doing any form of flood protection - the data is sent immediately.
Called by AddToSendQueue after flood protection has been taken into account.
Parameters:
data_format The format-string of the data to send
... Variable number of parameters as determined within data_format
Returns:
The return value is that of BIO_puts. Error handling is already processed when the function returns, if necessary.
Definition at line 1078 of file IrcConnection.cc.
References Debug, fg_magenta(), LOG, MAX_BUF_IRC_MSG_CRLF, MissingParameter, OK, and OpenSSLError.
Referenced by IrcParser::HandlePrivmsg().
{
        char buf[MAX_BUF_IRC_MSG_CRLF];
        va_list args;
        int32_t ret = 0;
        if ( data_format == nullptr )
                goto no_format;
        // the following is mostly a copy of the str_format utility function
        va_start(args, data_format);
#if MSVC_IS_VS8_OR_LATER
# pragma warning ( push )
# pragma warning ( disable : 4996 ) // variable or function may be unsafe
#endif
        // vsnprintf is fine when the buffer size is provided with -1 (for nul)
        ret = vsnprintf(buf, (sizeof(buf) - 1), data_format, args);
#if MSVC_IS_VS8_OR_LATER
# pragma warning ( pop )
#endif
        va_end(args);
        /* if truncated, there will be no crlf and the server won't process it
         * until the next one is provided! */
        if ( ret == -1 )
        {
                // destination text has been truncated
                buf[sizeof(buf)-1] = '\0';
                buf[sizeof(buf)-2] = '\n';
                buf[sizeof(buf)-3] = '\r';
                std::cout << fg_magenta << "Sending buffer truncated to read: " << buf << "\n";
        }
        else
        {
                /* to ensure nul-termination */
                buf[ret] = '\0';
        }
#if defined(USING_OPENSSL_NET)
        ret = BIO_puts(_socket.get(), buf);
        if ( ret <= 0 )
                goto openssl;
#else
#endif
        // Debug log, remove the cr+lf! (-2, not -3, array pos by strlen)
        buf[strlen(buf)-2] = '\0';
        LOG(ELogLevel::Debug) << "Sent on " << this << ": " << buf << "\n";
        _bytes_sent += ret;
        return EIrcStatus::OK;
no_format:
        std::cerr << fg_red << "The supplied data format was a nullptr\n";
        return EIrcStatus::MissingParameter;
#if defined(USING_OPENSSL_NET)
openssl:
        std::cerr << fg_red << "OpenSSL send error: " << ERR_error_string(ERR_get_error(), nullptr) << "\n";
        return EIrcStatus::OpenSSLError;
#endif
}
void IrcConnection::SendCTCP (const char *target, const char *message)
The contents of message are surrounded [prefix+suffix] by the CTCP codes (\001), and sent off via a PRIVMSG to the supplied target.
void IrcConnection::SendCTCP (const char *target, const char *message)
The contents of message are surrounded [prefix+suffix] by the CTCP codes (\001), and sent off via a PRIVMSG to the supplied target.
Definition at line 1156 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( target == nullptr )
                goto no_target;
        if ( message == nullptr )
                goto no_message;
        str_format(buffer, sizeof(buffer),
                "PRIVMSG %s :\001%s\001",
                target, message);
        return AddToSendQueue(buffer);
no_target:
        return EIrcStatus::MissingParameter;
no_message:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendCTCPNotice (const char *destination, const char *message)
void IrcConnection::SendCTCPNotice (const char *destination, const char *message)
Definition at line 1183 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( destination == nullptr )
                goto no_dest;
        if ( message == nullptr )
                goto no_message;
        str_format(buffer, sizeof(buffer),
                "NOTICE %s :\001%s\001",
                destination, message);
        return AddToSendQueue(buffer);
no_dest:
        return EIrcStatus::MissingParameter;
no_message:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendIdentify (const char *service, const char *pass)
void IrcConnection::SendIdentify (const char *service, const char *pass)
Definition at line 1417 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
Referenced by IrcParser::HandleNotice().
{
#if 0 // useful code, might need to use some of these format strings for full support. Think this was from xchat
        // are all ircd authors idiots?
        switch (serv->nickservtype)
        {
        case 0:
                tcp_sendf (serv, "PRIVMSG NICKSERV :%s %s%s%s\r\n", cmd, arg1, arg2, arg3);
                break;
        case 1:
                tcp_sendf (serv, "NICKSERV %s %s%s%s\r\n", cmd, arg1, arg2, arg3);
                break;
        case 2:
                tcp_sendf (serv, "NS %s %s%s%s\r\n", cmd, arg1, arg2, arg3);
                break;
        case 3:
                tcp_sendf (serv, "PRIVMSG NS :%s %s%s%s\r\n", cmd, arg1, arg2, arg3);
                break;
        case 4:
                // why couldn't QuakeNet implement one of the existing ones?
                tcp_sendf (serv, "AUTH %s%s%s\r\n", cmd, arg1, arg2, arg3);
        }
#endif
        char buffer[MAX_BUF_IRC_MSG];
        if ( service == nullptr )
                goto no_service;
        if ( pass == nullptr )
                goto no_pass;
        str_format(buffer, sizeof(buffer),
                "%s IDENTIFY %s",
                service, pass);
        return AddToSendQueue(buffer);
no_service:
        return EIrcStatus::MissingParameter;
no_pass:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendInit ()
Sends the client standard initialization (nick and user, plus any capabilities with newer servers). Some servers WE have to trigger this, as they wait for our first data whereas most others simply start the 439 straight away.
void IrcConnection::SendInit ()
Sends the client standard initialization (nick and user, plus any capabilities with newer servers). Some servers WE have to trigger this, as they wait for our first data whereas most others simply start the 439 straight away.
Todo
we should wait here, receive the replys, and REQ in response...
Definition at line 1210 of file IrcConnection.cc.
References IrcNetwork::_client, IrcNetwork::_profile_config, CS_InitSent, config_profile::ident, MAX_BUF_IRC_MSG, config_profile::mode, irc_client::nickname, config_profile::nicknames, OK, config_profile::real_name, strlcat(), and strlcpy().
Referenced by IrcParser::ParseNextRecvQueueItem().
{
        char response[MAX_BUF_IRC_MSG];
        const char* capabilities[] = { "multi-prefix", "uhnames" };
        const uint32_t num_cap = sizeof(capabilities)/sizeof(char*);
        IrcNetwork* network = std::shared_ptr<IrcNetwork>(_owner).get();
        uint32_t len;
        uint32_t i;
        char* p = nullptr;
        EIrcStatus retval;
        /* send our nick, user, and capability requests. If the server doesn't
         * support them, there's not much we can do about it, so just dump all
         * our initial requirements and handle the responses as best as possible. */
        _state |= CS_InitSent;
        if (( retval = SendBypass("CAP LIST\r\n")) != EIrcStatus::OK )
                return retval;
        /* use our copy/append trick to save using str_format for each
         * capability */
        p = &response[(len = strlcpy(response, "CAP REQ ", sizeof(response)))];
        for ( i = 0; i < num_cap; i++ )
        {
                response[len] = '\0';
                strlcat(p, capabilities[i], sizeof(response)-len);
                // function will log all errors itself
                if (( retval = SendBypass("%s\r\n", response)) != EIrcStatus::OK )
                        return retval;
        }
        if (( retval = SendBypass("CAP END\r\n")) != EIrcStatus::OK )
                return retval;
        /* use the first nickname in the profile configuration, unless
         * we're reconnecting, in which case this is already set */
        if ( network->_client.nickname.empty() )
                network->_client.nickname = network->_profile_config.nicknames[0];
        /* We will not support 'PASS', as automatically sending a password
         * across the wire is dangerous, especially so if we're not using SSL;
         * put it down to the user if they want to send their pass plaintext */
        if (( retval = SendNick(network->_client.nickname.c_str())) != EIrcStatus::OK )
                return retval;
        /* user fields are non-modifiable once connected, so they are
         * loaded from the profile configuration */
        return SendUser(
                network->_profile_config.ident.c_str(),
                network->_profile_config.mode,
                network->_profile_config.real_name.c_str());
}
void IrcConnection::SendInvite (const char *channel_name, const char *nickname)
void IrcConnection::SendInvite (const char *channel_name, const char *nickname)
Definition at line 1272 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( channel_name == nullptr )
                goto no_channel;
        if ( nickname == nullptr )
                goto no_nickname;
        str_format(buffer, sizeof(buffer),
                "INVITE %s %s",
                nickname, channel_name);
        return AddToSendQueue(buffer);
no_channel:
        return EIrcStatus::MissingParameter;
no_nickname:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendJoin (const char *channel_name, const char *channel_key = nullptr)
void IrcConnection::SendJoin (const char *channel_name, const char *channel_key = nullptr)
Definition at line 1299 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
Referenced by IrcParser::HandleKick(), and IrcParser::HandleNotice().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( channel_name == nullptr )
                goto no_channel;
        if ( channel_key == nullptr )
        {
                str_format(buffer, sizeof(buffer),
                        "JOIN %s",
                        channel_name);
        }
        else
        {
                str_format(buffer, sizeof(buffer),
                        "JOIN %s %s",
                        channel_name);
        }
        return AddToSendQueue(buffer);
no_channel:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendKick (const char *channel_name, const char *nickname, const char *msg = nullptr)
void IrcConnection::SendKick (const char *channel_name, const char *nickname, const char *msg = nullptr)
Definition at line 1331 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( channel_name == nullptr )
                goto no_channel;
        if ( nickname == nullptr )
                goto no_nickname;
        if ( msg == nullptr )
        {
                str_format(buffer, sizeof(buffer),
                        "KICK %s %s",
                        channel_name, nickname);
        }
        else
        {
                str_format(buffer, sizeof(buffer),
                        "KICK %s %s :%s",
                        channel_name, nickname, msg);
        }
        return AddToSendQueue(buffer);
no_channel:
        return EIrcStatus::MissingParameter;
no_nickname:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendMode (const char *target, const char *mode)
void IrcConnection::SendMode (const char *target, const char *mode)
Definition at line 1368 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( target == nullptr )
                goto no_target;
        if ( mode == nullptr )
                goto no_mode;
        str_format(buffer, sizeof(buffer),
                "MODE %s %s",
                target, mode);
        return AddToSendQueue(buffer);
no_target:
        return EIrcStatus::MissingParameter;
no_mode:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendNick (const char *nickname)
void IrcConnection::SendNick (const char *nickname)
Definition at line 1395 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( nickname == nullptr )
                goto no_nick;
        str_format(buffer, sizeof(buffer),
                "NICK %s",
                nickname);
        return AddToSendQueue(buffer);
no_nick:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendNotice (const char *target, const char *message)
void IrcConnection::SendNotice (const char *target, const char *message)
Definition at line 1466 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( target == nullptr )
                goto no_target;
        if ( message == nullptr )
                goto no_message;
        str_format(buffer, sizeof(buffer),
                "NOTICE %s :%s",
                target, message);
        return AddToSendQueue(buffer);
no_target:
        return EIrcStatus::MissingParameter;
no_message:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendPart (const char *channel_name, const char *msg = nullptr)
void IrcConnection::SendPart (const char *channel_name, const char *msg = nullptr)
Definition at line 1493 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( channel_name == nullptr )
                goto no_channel;
        if ( msg == nullptr )
        {
                str_format(buffer, sizeof(buffer),
                        "PART %s",
                        channel_name);
        }
        else
        {
                str_format(buffer, sizeof(buffer),
                        "PART %s :%s",
                        channel_name, msg);
        }
        return AddToSendQueue(buffer);
no_channel:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendPrivmsg (const char *target, const char *privmsg)
void IrcConnection::SendPrivmsg (const char *target, const char *privmsg)
Definition at line 1525 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        // do not support blank entries
        if ( target == nullptr )
                goto no_target;
        if ( privmsg == nullptr )
                goto no_message;
        str_format(buffer, sizeof(buffer),
                "PRIVMSG %s :%s",
                target, privmsg);
        // populate activity, notify? can't do this though, what if we're passing
        // a message through from the parser at the same time...
        return AddToSendQueue(buffer);
no_target:
        return EIrcStatus::MissingParameter;
no_message:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendQuit (const char *msg = nullptr)
void IrcConnection::SendQuit (const char *msg = nullptr)
Definition at line 1566 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, str_format(), and strlcpy().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( msg == nullptr )
        {
                // embed our own quit message if none provided
                strlcpy(buffer, "QUIT :http://www.trezanik.org/", sizeof(buffer));
        }
        else
        {
                str_format(buffer, sizeof(buffer),
                        "QUIT :%s",
                        msg);
        }
        return AddToSendQueue(buffer);
}
void IrcConnection::SendRaw (const char *data)
void IrcConnection::SendRaw (const char *data)
Definition at line 1556 of file IrcConnection.cc.
Referenced by IrcParser::HandleNotice().
{
        return AddToSendQueue(data);
}
void IrcConnection::SendTopic (const char *channel_name, const char *message = nullptr)
void IrcConnection::SendTopic (const char *channel_name, const char *message = nullptr)
Definition at line 1590 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( channel_name == nullptr )
                goto no_channel;
        if ( topic == nullptr )
        {
                // remove the channel topic
                str_format(buffer, sizeof(buffer),
                        "TOPIC %s :\r\n",
                        channel_name);
        }
        else if ( topic[0] != '\0' )
        {
                // set the channel topic
                str_format(buffer, sizeof(buffer),
                        "TOPIC %s :%s\r\n",
                        channel_name, topic);
        }
        else
        {
                // request the topic for the channel
                str_format(buffer, sizeof(buffer),
                        "TOPIC %s\r\n",
                        channel_name);
        }
        return AddToSendQueue(buffer);
no_channel:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SendUser (const char *username, const uint16_tmode = 8, const char *realname = nullptr)
void IrcConnection::SendUser (const char *username, const uint16_tmode = 8, const char *realname = nullptr)
Definition at line 1631 of file IrcConnection.cc.
References MAX_BUF_IRC_MSG, MissingParameter, and str_format().
{
        char buffer[MAX_BUF_IRC_MSG];
        if ( username == nullptr )
                goto no_username;
        // if not set, real name is the same as the user/ident name
        if ( realname == nullptr )
                realname = username;
        /*
        rfc 1419 ::
        <username> <hostname> <servername> :<realname>
        rfc 2812 ::
        <user> <mode> <unused> :<realname>
        */
        str_format(buffer, sizeof(buffer),
                "USER %s %d * :%s",
                username, mode, realname);
        return AddToSendQueue(buffer);
no_username:
        return EIrcStatus::MissingParameter;
}
void IrcConnection::SetActiveChannel (IrcChannel *channel)
Activates the supplied channel as the currently active IrcChannel in the connection. If no channels exist, and AddChannel() adds a new channel, this is automatically called to make it active.
Dereferences any channel that was previously set to active, before referencing the supplied one, and setting it active.
Parameters:
channel The IrcChannel to set as active
EIrcStatus IrcConnection::SetActiveChannel (const char *channel_name)
Activates the supplied channel as the currently active IrcChannel in the connection. If no channels exist, and AddChannel() adds a new channel, this is automatically called to make it active.
Dereferences any channel that was previously set to active, before referencing the supplied one, and setting it active.
Parameters:
channel The channel name to set as active
bool IrcConnection::Setup (IrcNetwork *network, std::shared_ptr< config_server >server_config)
Creates an irc_connection struct, ready for a call to connect_to_server. This also performs the DNS lookup, sockaddr creation, etc. This should be the only outbound data at this stage; we won't touch the specified server until the actual connect function is called.
Populates the classes parameters struct, required before calling EstablishConnection
The OpenSSL library will also be used to create the BIO (socket) in preparation for usage before returning.
If using SSL, this creates the SSL struct and its context too.
Parameters:
network A pointer to this connections network; obtained from a prior call to ???
server_config A pointer to the XML element for the server to connect to
Returns:
On success, a pointer to the dynamically allocated struct is returned; this must be freed when no longer in usage.
Any failure results in the function returning false
Todo
these should be pre-validated from reading the config; are these extra checks still needed?
Definition at line 1561 of file bak/IrcConnection.cc.
References IrcNetwork::_network_config, _params, irc_connection_params::allow_invalid_cert, config_network::allow_invalid_cert, irc_connection_params::conn_str, irc_connection_params::data, irc_connection_params::host, host_to_ipv4(), irc_connection_params::ip, irc_connection_params::ip_addr, ipv4_to_host(), irc_connection_params::port, str_format(), IrcNetwork::UpdateServerInfo(), and irc_connection_params::use_ssl.
{
        int32_t i;
        char buffer[NI_MAXHOST];
        /* if a prior conn_str exists, we're reconnecting, so the network and
         * server_config pointers are expected to be null. In case the IP has
         * changed, we do want to do fresh lookups though, so don't skip this
         * function! */
        if ( _params.conn_str[0] != '\0' )
                goto params_set;
        if ( network == nullptr )
                goto invalid_network;
        if ( server_config == nullptr )
                goto no_server;
        /* Child elements (optionally) consist of the 'port' and 'ssl', with
         * int and bool types respectively. If not supplied, they will default
         * to port = 6667, and ssl = false. */
        // validate settings
        if ( server_config->port < 1 || server_config->port > 65535 )
        {
                // generate an error, but don't cease processing
                std::cerr << fg_red << "The port specified for "
                        << server_config->hostname << " ("
                        << server_config->port
                        << ") is outside the applicable range; defaulting to 6667\n";
                server_config->port = 6667;
        }
        // copy the server data into the connection parameters
        _params.use_ssl = server_config->ssl;
        _params.port = server_config->port;
        _params.host = server_config->hostname;
        _params.ip_addr = server_config->ip_address;
params_set:
        // check if a host is specified first
        if ( _params.host.length() > 0 )
        {
                // setup the connection string to pass to OpenSSL
                str_format(buffer, sizeof(buffer),
                        "%s:%u", _params.host.c_str(), _params.port);
                _params.conn_str = buffer;
                // verify we can identify an IP address for the host
#if defined(USING_POCO_NET)
#else
                i = host_to_ipv4(_params.host.c_str(), -1, buffer, sizeof(buffer));
                if ( i == -1 )
                        goto lookup_failed;
                _params.data = buffer;
#endif
        }
        else if ( _params.ip_addr.length() > 0 )
        {
                str_format(buffer, sizeof(buffer),
                        "%s:%u", _params.ip_addr.c_str(), _params.port);
                _params.conn_str = buffer;
                /* reverse lookup for additional information */
#if defined(USING_POCO_NET)
#else
                ipv4_to_host(_params.ip_addr.c_str(), buffer, sizeof(buffer));
                _params.data = buffer;
#endif
        }
        else
                goto no_server;
        /* reaching here, we must know an IP to connect to */
        inet_pton(AF_INET, _params.ip_addr.c_str(), &_params.ip);
        /* copy the data into the networks connection information */
        network->UpdateServerInfo();
        if ( _params.use_ssl )
        {
#if defined(USING_OPENSSL)
                // SSL connection requested
                SSL_CTX* ssl_ctx = SSL_CTX_new(SSLv23_client_method());
                SSL* ssl = nullptr;
                BIO* socket = nullptr;
                if ( ssl_ctx == nullptr )
                        goto openssl_context_failed;
                _ssl_context = std::unique_ptr<SSL_CTX>(ssl_ctx);
                socket = BIO_new_ssl_connect(ssl_ctx);
                if ( socket == nullptr )
                        goto openssl_ssl_bio_failed;
                _socket = std::unique_ptr<BIO>(socket);
                BIO_get_ssl(_socket.get(), &ssl);
                _ssl = std::unique_ptr<SSL>(ssl);
                SSL_set_mode(_ssl.get(), SSL_MODE_AUTO_RETRY);
                BIO_set_conn_hostname(_socket.get(), _params.conn_str.c_str());
        }
        else
        {
                // non-SSL connection requested
                BIO* socket = BIO_new_connect(const_cast<char*>(_params.conn_str.c_str()));
                if ( socket == nullptr )
                        goto openssl_bio_failed;
                _socket.reset(socket);
#else
#endif
        }
        // and anything else that needs putting across
        _params.allow_invalid_cert = network->_network_config.allow_invalid_cert;
        return true;
invalid_network:
        std::cerr << fg_red << "The supplied irc_network was a nullptr\n";
        return false;
no_server:
        std::cerr << fg_red << "There is no server specified by the input xml element\n";
        return false;
lookup_failed:
        // already logged in function call
        return false;
#if defined(USING_OPENSSL)
openssl_context_failed:
        std::cerr << fg_red << "Failed to create the OpenSSL SSL context\n";
        return false;
openssl_ssl_bio_failed:
        std::cerr << fg_red << "Failed to create the OpenSSL SSL BIO\n";
        SSL_CTX_free(_ssl_context.release());
        return false;
openssl_bio_failed:
        std::cerr << fg_red << "Failed to create the OpenSSL BIO\n";
        return false;
#endif
}
EIrcStatus IrcConnection::Setup (std::shared_ptr< IrcNetwork >network, std::shared_ptr< config_server >server_config)
Creates an irc_connection struct, ready for a call to connect_to_server. This also performs the DNS lookup, sockaddr creation, etc. This should be the only outbound data at this stage; we won't touch the specified server until the actual connect function is called.
Populates the classes parameters struct, required before calling EstablishConnection
The OpenSSL library will also be used to create the BIO (socket) in preparation for usage before returning.
If using SSL, this creates the SSL struct and its context too.
Parameters:
network A pointer to this connections network; obtained from a prior call to ???
server_config A pointer to the XML element for the server to connect to
Returns:
On success, a pointer to the dynamically allocated struct is returned; this must be freed when no longer in usage.
Any failure results in the function returning false
Todo
these should be pre-validated from reading the config; are these extra checks still needed?
Definition at line 1665 of file IrcConnection.cc.
References host_to_ipv4(), InvalidData, ipv4_to_host(), LookupFailed, MissingParameter, OK, OpenSSLError, and str_format().
{
        int32_t i;
        char buffer[NI_MAXHOST];
        /* if a prior conn_str exists, we're reconnecting, so the network and
         * server_config pointers are expected to be null. In case the IP has
         * changed, we do want to do fresh lookups though, so don't skip this
         * function! */
        if ( _params.conn_str[0] != '\0' )
                goto params_set;
        if ( network == nullptr )
                goto invalid_network;
        if ( server_config == nullptr )
                goto no_server;
        /* Child elements (optionally) consist of the 'port' and 'ssl', with
         * int and bool types respectively. If not supplied, they will default
         * to port = 6667, and ssl = false. */
        // validate settings
        if ( server_config->port < 1 || server_config->port > 65535 )
        {
                // generate an error, but don't cease processing
                std::cerr << fg_red << "The port specified for "
                        << server_config->hostname << " ("
                        << server_config->port
                        << ") is outside the applicable range; defaulting to 6667\n";
                server_config->port = 6667;
        }
        // copy the server data into the connection parameters
        _params.use_ssl = server_config->ssl;
        _params.port = server_config->port;
        _params.host = server_config->hostname;
        _params.ip_addr = server_config->ip_address;
params_set:
        // check if a host is specified first
        if ( _params.host.length() > 0 )
        {
                // setup the connection string to pass to OpenSSL
                str_format(buffer, sizeof(buffer),
                        "%s:%u", _params.host.c_str(), _params.port);
                _params.conn_str = buffer;
                // verify we can identify an IP address for the host
#if defined(USING_BOOST_NET)
                io_service io_service;
                ip::tcp::resolver resolver(io_service);
                ip::tcp::resolver::query query(_params.host);
                ip::tcp::endpoint ep;
                /* we're only interested in one IP lookup, not all, so just
                 * use the first one that we resolve. */
                ep = *resolver.resolve(query);
                _params.data = ep.address().to_string();
#else
                i = host_to_ipv4(_params.host.c_str(), -1, buffer, sizeof(buffer));
                if ( i == -1 )
                        goto lookup_failed;
                _params.data = buffer;
#endif
        }
        else if ( _params.ip_addr.length() > 0 )
        {
                str_format(buffer, sizeof(buffer),
                        "%s:%u", _params.ip_addr.c_str(), _params.port);
                _params.conn_str = buffer;
                // reverse lookup for additional information
#if defined(USING_BOOST_NET)
                ip::tcp::endpoint ep;
                ip::address_v4 ip = ip::address_v4::from_string(_params.ip_addr);
                io_service ios;
                ip::tcp::resolver res(ios);
                ip::tcp::resolver::iterator dest;
                ep.address(ip);
                /* we're only interested in one hostname reverse lookup, not
                 * all, so just use the first one that we receive. */
                dest = res.resolve(ep);
                _params.data = dest->host_name();
#else
                ipv4_to_host(_params.ip_addr.c_str(), buffer, sizeof(buffer));
                _params.data = buffer;
#endif
        }
        else
        {
                goto no_server;
        }
        // reaching here, we must know an IP to connect to
        inet_pton(AF_INET, _params.ip_addr.c_str(), &_params.ip);
        // copy the data into the networks connection information
        network->UpdateServerInfo();
        if ( _params.use_ssl )
        {
#if defined(USING_OPENSSL_NET)
                // SSL connection requested
                SSL_CTX* ssl_ctx = SSL_CTX_new(SSLv23_client_method());
                SSL* ssl = nullptr;
                BIO* socket = nullptr;
                if ( ssl_ctx == nullptr )
                        goto openssl_context_failed;
                _ssl_context = std::unique_ptr<SSL_CTX>(ssl_ctx);
                socket = BIO_new_ssl_connect(ssl_ctx);
                if ( socket == nullptr )
                        goto openssl_ssl_bio_failed;
                _socket = std::unique_ptr<BIO>(socket);
                BIO_get_ssl(_socket.get(), &ssl);
                _ssl = std::unique_ptr<SSL>(ssl);
                SSL_set_mode(_ssl.get(), SSL_MODE_AUTO_RETRY);
                BIO_set_conn_hostname(_socket.get(), _params.conn_str.c_str());
        }
        else
        {
                // non-SSL connection requested
                BIO* socket = BIO_new_connect(const_cast<char*>(_params.conn_str.c_str()));
                if ( socket == nullptr )
                        goto openssl_bio_failed;
                _socket.reset(socket);
#elif defined(USING_BOOST_NET)
                // SSL connection requested
        }
        else
        {
                // non-SSL connection requested
#else
#endif
        }
        // and anything else that needs putting across
        _params.allow_invalid_cert = network->_network_config.allow_invalid_cert;
        return EIrcStatus::OK;
invalid_network:
        std::cerr << fg_red << "The supplied irc_network was a nullptr\n";
        return EIrcStatus::MissingParameter;
no_server:
        std::cerr << fg_red << "There is no server specified by the input\n";
        return EIrcStatus::InvalidData;
lookup_failed:
        // already logged in function call
        return EIrcStatus::LookupFailed;
#if defined(USING_OPENSSL_NET)
openssl_context_failed:
        std::cerr << fg_red << "Failed to create the OpenSSL SSL context\n";
        return EIrcStatus::OpenSSLError;
openssl_ssl_bio_failed:
        std::cerr << fg_red << "Failed to create the OpenSSL SSL BIO\n";
        SSL_CTX_free(_ssl_context.release());
        return EIrcStatus::OpenSSLError;
openssl_bio_failed:
        std::cerr << fg_red << "Failed to create the OpenSSL BIO\n";
        return EIrcStatus::OpenSSLError;
#endif
}
Friends And Related Function Documentation
IrcNetwork [friend]
Definition at line 81 of file IrcConnection.h.
IrcParser [friend]
Definition at line 79 of file IrcConnection.h.
Member Data Documentation
irc_activity IrcConnection::_activity [private]
The last parsed activity
Definition at line 121 of file IrcConnection.h.
uint64_t IrcConnection::_bytes_recv [private]
stats tracking - bytes received
Definition at line 91 of file IrcConnection.h.
uint64_t IrcConnection::_bytes_sent [private]
stats tracking - bytes sent
Definition at line 92 of file IrcConnection.h.
std::vector< std::string > IrcConnection::_cap_ack [private]
Servers confirmed CAP support
Definition at line 117 of file IrcConnection.h.
Referenced by IrcParser::HandleCap().
std::vector< std::string > IrcConnection::_cap_ls [private]
Servers listed CAP support
Definition at line 119 of file IrcConnection.h.
Referenced by IrcParser::HandleCap().
std::vector< std::string > IrcConnection::_cap_nak [private]
Servers confirmed CAP no support
Definition at line 118 of file IrcConnection.h.
Referenced by IrcParser::HandleCap().
std::set<IrcChannel*> IrcConnection::_channel_list [private]
The connections channel list
Definition at line 101 of file bak/IrcConnection.h.
std::set<std::string> IrcConnection::_channel_list [private]
The connections channel list
Definition at line 103 of file IrcConnection.h.
Referenced by DeleteChannel(), IrcParser::HandleNick(), and IrcParser::HandleQuit().
uint32_t IrcConnection::_id [private]
Unique id
Definition at line 123 of file IrcConnection.h.
time_t IrcConnection::_lag_sent [private]
The time 'LAG' was sent
Definition at line 90 of file IrcConnection.h.
Referenced by IrcParser::HandlePong().
time_t IrcConnection::_last_data [private]
The time data was last received
Definition at line 89 of file IrcConnection.h.
std::mutex IrcConnection::_mutex [mutable], [private]
Synchronization lock; mutable to enable constness for retrieval functions
Definition at line 95 of file IrcConnection.h.
Referenced by DeleteChannel(), and IrcParser::ParseNextRecvQueueItem().
std::weak_ptr<IrcNetwork> IrcConnection::_owner [private]
the network we reside in
Definition at line 115 of file IrcConnection.h.
irc_connection_params IrcConnection::_params [private]
The parameters used for the last server connection
Definition at line 122 of file IrcConnection.h.
Referenced by Setup(), and IrcNetwork::UpdateServerInfo().
IrcNetwork* IrcConnection::_parent_network [private]
the network we reside in
Definition at line 109 of file bak/IrcConnection.h.
Referenced by IrcParser::Handle001(), IrcParser::Handle002(), IrcParser::Handle005(), IrcParser::Handle353(), IrcParser::HandleJoin(), IrcParser::HandleKick(), IrcParser::HandleKill(), IrcParser::HandleMode(), IrcParser::HandleNick(), IrcParser::HandleNotice(), IrcParser::HandlePart(), IrcParser::HandleQuit(), IrcParser::HasChannelPrefix(), and IrcParser::ModeHasArgument().
std::queue< std::string > IrcConnection::_recv_queue [private]
The connections unprocessed receive queue
Definition at line 98 of file IrcConnection.h.
Referenced by IrcParser::ParseNextRecvQueueItem().
std::queue< std::string > IrcConnection::_send_queue [private]
The connections unprocessed send queue
Definition at line 100 of file IrcConnection.h.
Referenced by IrcParser::ProcessNextSendQueueItem().
uint32_t IrcConnection::_state [private]
flag-based connection state
Definition at line 88 of file IrcConnection.h.
Referenced by IrcParser::Handle001(), and IrcParser::ParseNextRecvQueueItem().
uint32_t IrcConnection::_thread [private]
ID of the connection preservation thread
Definition at line 126 of file IrcConnection.h.
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.