IrcChannel
NAME
IrcChannel -
SYNOPSIS
#include <IrcChannel.h>
Inherits IrcObject, and IrcObject.
Public Member Functions
IrcChannel (std::shared_ptr< IrcConnection > connection, const char *channel_name)
~IrcChannel ()
EIrcStatus AddNamesUser (const char *name, const char *ident, const char *hostmask, const mode_update *modes)
EIrcStatus Cleanup ()
EIrcStatus DeleteUser (std::shared_ptr< IrcUser > user)
std::shared_ptr< IrcUser > GetUser (const char *nickname)
bool IsActive () const
bool IsAuthorized (const char *nickname, const uint8_t mode) const
bool IsAuthorized (const std::shared_ptr< IrcUser > user, const uint8_t mode) const
std::string Name () const
uint32_t NumberOfUsers () const
std::shared_ptr< IrcConnection > Owner ()
EIrcStatus PopulateUserlist ()
std::string Topic () const
EIrcStatus UpdateTopic (const char *topic)
std::set< std::string > & Users ()
IrcChannel (IrcConnection *parent_connection, const char *channel_name)
~IrcChannel ()
bool AddNamesUser (const char *name, const char *ident, const char *hostmask, const mode_update *modes)
bool AddUser (const char *name, const char *ident, const char *hostmask)
void Cleanup ()
bool DeleteUser (IrcUser *user)
IrcUser * GetUser (const char *nickname)
bool IsActive () const
bool IsAuthorized (const char *nickname, const uint8_t mode) const
bool IsAuthorized (const IrcUser *user, const uint8_t mode) const
std::string Name () const
uint32_t NumberOfUsers () const
IrcConnection * Owner ()
void PopulateUserlist ()
std::string Topic () const
void UpdateTopic (const char *topic)
std::set< IrcUser * > & Users ()
Private Member Functions
NO_CLASS_ASSIGNMENT (IrcChannel)
NO_CLASS_COPY (IrcChannel)
EIrcStatus EraseNameslist ()
EIrcStatus EraseUserlist ()
NO_CLASS_ASSIGNMENT (IrcChannel)
NO_CLASS_COPY (IrcChannel)
void EraseNameslist ()
void EraseUserlist ()
Private Attributes
uint32_t _flags
uint16_t _limit
std::string _key
std::string _name
std::string _topic
std::weak_ptr< IrcConnection > _owner
std::set< std::string > _userlist
std::set< IrcUser * > _nameslist
std::recursive_mutex _mutex
IrcConnection * _parent_connection
std::set< IrcUser * > _userlist
Friends
class IrcParser
Additional Inherited Members
Detailed Description
Definition at line 36 of file IrcChannel.h.
Constructor & Destructor Documentation
IrcChannel::IrcChannel (std::shared_ptr< IrcConnection >connection, const char *channel_name)
Constructs the channel. This is the only opportunity to set the name of it (why would you change it afterwards?).
Should only be created (and therefore called) from the IrcParser.
Parameters:
connection The IrcConnection this channel was created for
channel_name The name of the channel for
Definition at line 33 of file IrcChannel.cc.
  : _flags(0), _limit(0), _owner(connection)
{
        // userlist, nameslist, etc., start empty
        _name = channel_name;
}
IrcChannel::~IrcChannel ()
Definition at line 45 of file IrcChannel.cc.
References Cleanup().
{
        Cleanup();
}
IrcChannel::IrcChannel (IrcConnection *parent_connection, const char *channel_name)
Constructs the channel. This is the only opportunity to set the name of it (why would you change it afterwards?).
Should only be created (and therefore called) from the IrcParser.
Parameters:
parent_connection The connection this channel was created for
channel_name The name of the channel for
Definition at line 32 of file bak/IrcChannel.cc.
  : _flags(0), _limit(0), _parent_connection(parent_connection)
{
        // userlist, nameslist, etc., start empty
        _name = channel_name;
}
IrcChannel::~IrcChannel ()
Member Function Documentation
bool IrcChannel::AddNamesUser (const char *name, const char *ident, const char *hostmask, const mode_update *modes)
Adds the supplied user details into a new IrcUser class which is added to the receiving 353 NAMES list.
Identical to that of AddUser excepting the list the user is added to, and not calling a UI update
Parameters:
name The users nickname
ident The users ident
hostmask The users hostmask
modes The users channel modes
Returns:
true if the user is created and added to the list
false on an invalid parameter or addition failure
bool IrcChannel::AddNamesUser (const char *name, const char *ident, const char *hostmask, const mode_update *modes)
Adds the supplied user details into a new IrcUser class which is added to the receiving 353 NAMES list.
Identical to that of AddUser excepting the list the user is added to, and not calling a UI update
Parameters:
name The users nickname
ident The users ident
hostmask The users hostmask
modes The users channel modes
Returns:
true if the user is created and added to the list
false on an invalid parameter or addition failure
Todo
we must have a better method than this, this is awful. could always get CreateXx to return object, shouldn't affect lifetimes
Definition at line 53 of file IrcChannel.cc.
References IrcObject::_irc_engine, _mutex, _nameslist, IrcEngine::CreateUser(), fg_red(), IrcPool::GetUser(), MissingParameter, Name(), OK, Owner(), and IrcEngine::Pools().
Referenced by IrcParser::Handle353().
{
        IrcUser* user;
        if ( name == nullptr )
                goto no_name;
        if ( ident == nullptr )
                goto no_ident;
        if ( hostmask == nullptr )
                goto no_hostmask;
        {
                std::lock_guard<std::recursive_mutex> lock(_mutex);
                _irc_engine->CreateUser(Owner()->Id(), Name().c_str(), name, ident, hostmask);
                if ( modes != nullptr )
                {
                        // since we have the modes, update now
                        _irc_engine->Pools()->GetUser(Owner()->Id(), Name().c_str(), name)->Update(nullptr, nullptr, nullptr, modes);
                }
                _nameslist.insert(user);
                // no notification, this is a temporary holder
        }
        return EIrcStatus::OK;
no_name:
        std::cerr << fg_red << "The supplied nickname was a nullptr\n";
        return EIrcStatus::MissingParameter;
no_ident:
        std::cerr << fg_red << "The supplied ident was a nullptr\n";
        return EIrcStatus::MissingParameter;
no_hostmask:
        std::cerr << fg_red << "The supplied hostmask was a nullptr\n";
        return EIrcStatus::MissingParameter;
}
bool IrcChannel::AddUser (const char *name, const char *ident, const char *hostmask)
Adds the supplied user details into a new IrcUser class which is added directly to the active userlist. Called primarily from receiving a 'JOIN' on an active channel.
Identical to that of AddNamesUser excepting the list the user is added to, and calling a UI update on completion.
Parameters:
name The users nickname
ident The users ident
hostmask The users hostmask
Returns:
true if the user is created and added to the list
false on an invalid parameter or addition failure
Definition at line 100 of file bak/IrcChannel.cc.
References IrcObject::_irc_engine, _mutex, _userlist, IrcFactory::CreateIrcUser(), IrcEngine::Factory(), and fg_red().
Referenced by IrcParser::HandleJoin().
{
        IrcUser* user;
        if ( name == nullptr )
                goto no_name;
        if ( ident == nullptr )
                goto no_ident;
        if ( hostmask == nullptr )
                goto no_hostmask;
        {
                std::lock_guard<std::recursive_mutex> lock(_mutex);
                _irc_engine->Factory()->CreateIrcUser(this, name, ident, hostmask);
                _userlist.insert(user);
        }
        return true;
no_name:
        std::cerr << fg_red << "The supplied nickname was a nullptr\n";
        return false;
no_ident:
        std::cerr << fg_red << "The supplied ident was a nullptr\n";
        return false;
no_hostmask:
        std::cerr << fg_red << "The supplied hostmask was a nullptr\n";
        return false;
}
void IrcChannel::Cleanup ()
Definition at line 104 of file IrcChannel.cc.
References _mutex, EraseNameslist(), EraseUserlist(), and OK.
Referenced by ~IrcChannel().
{
        EIrcStatus retval;
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        if (( retval = EraseNameslist()) != EIrcStatus::OK )
                return retval;
        if (( retval = EraseUserlist()) != EIrcStatus::OK )
                return retval;
        return EIrcStatus::OK;
}
void IrcChannel::Cleanup ()
EIrcStatus IrcChannel::DeleteUser (std::shared_ptr< IrcUser >user)
Unlinks the supplied user from the userlist, if not already done (usually via ReleaseUser), and decrements its reference count.
Note this function does not get called on the userlist or names list cleanups, as they unlink and release the user directly.
Parameters:
user The user to delete
Returns:
Returns true if the user is unlinked and released
false is returned if the user is a nullptr, or an integer underflow is triggered on the linked list.
Definition at line 121 of file IrcChannel.cc.
References IrcObject::_irc_engine, fg_red(), ObjectPool< T >::FreeObject(), IrcPool::IrcUsers(), MissingParameter, ObjectFreeError, OK, and IrcEngine::Pools().
Referenced by IrcParser::HandleKick(), and IrcParser::HandlePart().
{
        if ( user == nullptr )
                goto no_user;
        return _irc_engine->Pools()->IrcUsers()->FreeObject(user) ?
                EIrcStatus::OK : EIrcStatus::ObjectFreeError;
        
no_user:
        std::cerr << fg_red << "The supplied user was a nullptr\n";
        return EIrcStatus::MissingParameter;
}
bool IrcChannel::DeleteUser (IrcUser *user)
Unlinks the supplied user from the userlist, if not already done (usually via ReleaseUser), and decrements its reference count.
Note this function does not get called on the userlist or names list cleanups, as they unlink and release the user directly.
Parameters:
user The user to delete
Returns:
Returns true if the user is unlinked and released
false is returned if the user is a nullptr, or an integer underflow is triggered on the linked list.
Definition at line 151 of file bak/IrcChannel.cc.
References IrcObject::_irc_engine, _mutex, _userlist, IrcFactory::DeleteIrcObject(), IrcEngine::Factory(), and fg_red().
{
        if ( user == nullptr )
                goto no_user;
        {
                std::lock_guard<std::recursive_mutex> lock(_mutex);
                for ( auto u : _userlist )
                {
                        if ( u == user )
                        {
                                // users are created by a factory, needs matching delete
                                _irc_engine->Factory()->DeleteIrcObject(user);
                                _userlist.erase(u);
                                // must break out of the loop, iterator invalid
                                return true;
                        }
                }
        }
        std::cerr << fg_red << "The supplied user was not found in the userlist\n";
        return false;
no_user:
        std::cerr << fg_red << "The supplied user was a nullptr\n";
        return false;
}
void IrcChannel::EraseNameslist () [private]
Deletes all the IrcUser objects in the names list.
The protection mutex is recursive, so we can call this safely from other class functions so long as they're on the same thread.
void IrcChannel::EraseNameslist () [private]
Deletes all the IrcUser objects in the names list.
The protection mutex is recursive, so we can call this safely from other class functions so long as they're on the same thread.
Definition at line 139 of file IrcChannel.cc.
References IrcObject::_irc_engine, _mutex, _nameslist, ObjectPool< T >::FreeObject(), GetUser(), IrcPool::IrcUsers(), OK, and IrcEngine::Pools().
Referenced by Cleanup().
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        for ( auto u : _nameslist )
        {
                _irc_engine->Pools()->IrcUsers()->FreeObject(
                        GetUser(u->Nickname().c_str())
                );
        }
        _nameslist.clear();
        return EIrcStatus::OK;
}
void IrcChannel::EraseUserlist () [private]
Deletes all the IrcUser objects in the active userlist.
The protection mutex is recursive, so we can call this safely from other class functions so long as they're on the same thread.
void IrcChannel::EraseUserlist () [private]
Deletes all the IrcUser objects in the active userlist.
The protection mutex is recursive, so we can call this safely from other class functions so long as they're on the same thread.
Definition at line 157 of file IrcChannel.cc.
References _mutex, _userlist, and OK.
Referenced by Cleanup(), IrcParser::HandleKick(), IrcParser::HandlePart(), and PopulateUserlist().
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        _userlist.clear();
        return EIrcStatus::OK;
}
IrcUser * IrcChannel::GetUser (const char *nickname)
Gets the IrcUser object from the specified connection, whose name matches nickname.
Will not generate an error if the specified user is not found, as this can be used for a simple search; raise your own error if this is undesired.
Warning:
Increments the reference counter for the user; you must call Dereference on it when finished using it, or pass it to a function that does!
Parameters:
nickname The name of the user to locate
Returns:
If the user is not found, a nullptr is returned.
A pointer to the IrcUser called nickname.
Definition at line 169 of file IrcChannel.cc.
References IrcObject::_irc_engine, _name, IrcPool::GetUser(), Owner(), and IrcEngine::Pools().
Referenced by EraseNameslist(), IrcParser::HandleKick(), IrcParser::HandleMode(), and IrcParser::HandlePart().
{
        return _irc_engine->Pools()->GetUser(Owner()->Id(), _name.c_str(), nickname);
}
IrcUser* IrcChannel::GetUser (const char *nickname)
Gets the IrcUser object from the specified connection, whose name matches nickname.
Will not generate an error if the specified user is not found, as this can be used for a simple search; raise your own error if this is undesired.
Warning:
Increments the reference counter for the user; you must call Dereference on it when finished using it, or pass it to a function that does!
Parameters:
nickname The name of the user to locate
Returns:
If the user is not found, a nullptr is returned.
A pointer to the IrcUser called nickname.
bool IrcChannel::IsActive () const
Definition at line 179 of file IrcChannel.cc.
References _flags, _mutex, and CHANFLAG_ACTIVE.
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        return (_flags & CHANFLAG_ACTIVE);
}
bool IrcChannel::IsActive () const
bool IrcChannel::IsAuthorized (const char *nickname, const uint8_tmode) const
Looks up the IrcUser with a nickname of nickname, and checks if it is 'authorized' - its mode equal to or greater than that of mode.
Parameters:
nickname The nickname to lookup and check
mode The mode to check
Returns:
true if the nickname was found and has sufficient access.
false if the nickname isn't found, mode does not exist, or the user simply doesn't have the specified mode.
bool IrcChannel::IsAuthorized (const std::shared_ptr< IrcUser >user, const uint8_tmode) const
Checks if the IrcUser object user has its mode equal to or greater than that of mode.
Parameters:
user The IrcUser object to check
mode The mode to check
Returns:
true if the user object has sufficient access.
false if the mode does not exist, or the user simply doesn't have the specified mode.
bool IrcChannel::IsAuthorized (const char *nickname, const uint8_tmode) const
Looks up the IrcUser with a nickname of nickname, and checks if it is 'authorized' - its mode equal to or greater than that of mode.
Parameters:
nickname The nickname to lookup and check
mode The mode to check
Returns:
true if the nickname was found and has sufficient access.
false if the nickname isn't found, mode does not exist, or the user simply doesn't have the specified mode.
bool IrcChannel::IsAuthorized (const IrcUser *user, const uint8_tmode) const
Checks if the IrcUser object user has its mode equal to or greater than that of mode.
Parameters:
user The IrcUser object to check
mode The mode to check
Returns:
true if the user object has sufficient access.
false if the mode does not exist, or the user simply doesn't have the specified mode.
std::string IrcChannel::Name () const
Retrieves a copy.
Definition at line 188 of file IrcChannel.cc.
References _mutex, and _name.
Referenced by AddNamesUser(), and IrcConnection::DeleteChannel().
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        return _name;
}
std::string IrcChannel::Name () const
Retrieves a copy.
IrcChannel::NO_CLASS_ASSIGNMENT (IrcChannel) [private]
IrcChannel::NO_CLASS_ASSIGNMENT (IrcChannel) [private]
IrcChannel::NO_CLASS_COPY (IrcChannel) [private]
IrcChannel::NO_CLASS_COPY (IrcChannel) [private]
uint32_t IrcChannel::NumberOfUsers () const [inline]
Definition at line 221 of file IrcChannel.h.
        {
                return _userlist.size();
        }
uint32_t IrcChannel::NumberOfUsers () const [inline]
Definition at line 242 of file bak/IrcChannel.h.
        {
                return _userlist.size();
        }
IrcConnection * IrcChannel::Owner ()
Definition at line 197 of file IrcChannel.cc.
References _mutex, and _owner.
Referenced by AddNamesUser(), and GetUser().
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        return _owner.lock();
}
IrcConnection* IrcChannel::Owner ()
void IrcChannel::PopulateUserlist ()
Definition at line 207 of file IrcChannel.cc.
References _mutex, _nameslist, _userlist, EraseUserlist(), and OK.
Referenced by IrcParser::Handle366().
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        // wipe out the existing userlist
        EraseUserlist();
        // replace it with the pre-built names list
        for ( auto n : _nameslist )
        {
                _userlist.insert(_userlist.begin(), n->Nickname());
        }
        return EIrcStatus::OK;
}
void IrcChannel::PopulateUserlist ()
std::string IrcChannel::Topic () const
Definition at line 225 of file IrcChannel.cc.
References _mutex, and _topic.
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        return _topic;
}
std::string IrcChannel::Topic () const
void IrcChannel::UpdateTopic (const char *topic)
Sets the channel topic
Parameters:
topic The new topic, complete with colour codes, special chars
Definition at line 234 of file IrcChannel.cc.
References _mutex, _topic, and OK.
Referenced by IrcParser::Handle332(), and IrcParser::HandleTopic().
{
        std::lock_guard<std::recursive_mutex> lock(_mutex);
        // we allow setting a null topic
        _topic = topic;
        return EIrcStatus::OK;
}
void IrcChannel::UpdateTopic (const char *topic)
Sets the channel topic
Parameters:
topic The new topic, complete with colour codes, special chars
std::set<std::string>& IrcChannel::Users () [inline]
should probably return the pool addresses rather than the strings..
Definition at line 263 of file IrcChannel.h.
        {
                return _userlist;
        }
std::set<IrcUser*>& IrcChannel::Users () [inline]
Definition at line 284 of file bak/IrcChannel.h.
        {
                return _userlist;
        }
Friends And Related Function Documentation
IrcParser [friend]
Definition at line 39 of file IrcChannel.h.
Member Data Documentation
uint32_t IrcChannel::_flags [private]
Channel flags
Definition at line 44 of file IrcChannel.h.
Referenced by IrcParser::HandleJoin(), IrcParser::HandleKick(), IrcParser::HandlePart(), and IsActive().
std::string IrcChannel::_key [private]
Channel password, aka 'Key'
Definition at line 46 of file IrcChannel.h.
uint16_t IrcChannel::_limit [private]
User limit (max 65535 users in a channel seems fair/accurate?)
Definition at line 45 of file IrcChannel.h.
std::recursive_mutex IrcChannel::_mutex [mutable], [private]
Synchronization lock; mutable to enable constness for retrieval functions
Definition at line 57 of file IrcChannel.h.
Referenced by AddNamesUser(), AddUser(), Cleanup(), DeleteUser(), EraseNameslist(), EraseUserlist(), IsActive(), Name(), Owner(), PopulateUserlist(), Topic(), and UpdateTopic().
std::string IrcChannel::_name [private]
Channel name, including any prefixes
Definition at line 47 of file IrcChannel.h.
Referenced by GetUser(), and Name().
std::set< IrcUser * > IrcChannel::_nameslist [private]
Channel userlist for receiving 353 NAMES entries
Definition at line 54 of file IrcChannel.h.
Referenced by AddNamesUser(), EraseNameslist(), and PopulateUserlist().
std::weak_ptr<IrcConnection> IrcChannel::_owner [private]
Pointer to the owning connection
Definition at line 49 of file IrcChannel.h.
Referenced by Owner().
IrcConnection* IrcChannel::_parent_connection [private]
Pointer to the owning connection
Definition at line 48 of file bak/IrcChannel.h.
std::string IrcChannel::_topic [private]
Channel topic (will contain colour codes)
Definition at line 48 of file IrcChannel.h.
Referenced by Topic(), and UpdateTopic().
std::set<IrcUser*> IrcChannel::_userlist [private]
Active channel userlist
Definition at line 51 of file bak/IrcChannel.h.
std::set<std::string> IrcChannel::_userlist [private]
Active channel userlist
Definition at line 52 of file IrcChannel.h.
Referenced by AddUser(), DeleteUser(), EraseUserlist(), and PopulateUserlist().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.