IrcEngine
NAME
IrcEngine -
SYNOPSIS
#include <IrcEngine.h>
Public Member Functions
~IrcEngine ()
std::shared_ptr< IrcChannel > ActiveChannel ()
std::shared_ptr< IrcConnection > ActiveConnection ()
void AttachListener (IrcListener *listener)
EIrcStatus CreateChannel (const uint32_t connection_id, const char *name)
EIrcStatus CreateConnection (const char *network)
EIrcStatus CreateNetwork (const char *name)
EIrcStatus CreateUser (const uint32_t connection_id, const char *channel, const char *name, const char *ident, const char *hostmask)
void DetachListener (IrcListener *listener)
IrcParser * Parser () const
IrcPool * Pools () const
~IrcEngine ()
IrcChannel * ActiveChannel ()
IrcConnection * ActiveConnection ()
void AttachListener (IrcListener *listener)
std::vector< IrcConnection * > Connections () const
void DetachListener (IrcListener *listener)
IrcFactory * Factory () const
std::vector< IrcNetwork * > Networks () const
void NotifyDeleteObject (IrcObject *object)
void NotifyDeleteConnection (IrcConnection *connection)
void NotifyDeleteNetwork (IrcNetwork *network)
void NotifyNewConnection (IrcConnection *connection)
void NotifyNewNetwork (IrcNetwork *network)
void NotifyNewObject (IrcObject *object)
IrcParser * Parser () const
IrcPool * Pools () const
Private Member Functions
friend int::spawn_interface ()
NO_CLASS_ASSIGNMENT (IrcEngine)
NO_CLASS_COPY (IrcEngine)
IrcEngine ()
IrcFactory * Factory () const
void NotifyListeners (E_IRC_LISTENER_NOTIFICATION event_type, std::shared_ptr< IrcConnection > connection) const
NO_CLASS_ASSIGNMENT (IrcEngine)
NO_CLASS_COPY (IrcEngine)
IrcEngine ()
void NotifyListeners (E_IRC_LISTENER_NOTIFICATION event_type, IrcConnection *connection) const
Private Attributes
std::set< IrcListener * > _listeners
std::string _active_connection
std::string _active_channel
std::unique_ptr< IrcFactory > _ircobject_factory
std::vector< IrcObject * > _objects
std::vector< IrcConnection * > _connections
std::vector< IrcNetwork * > _networks
std::unique_ptr< IrcConnection > _active_connection
std::unique_ptr< IrcChannel > _active_channel
Friends
class IrcConnection
class IrcParser
void * instance (void *params)
Detailed Description
Todo
Try to get NotifyNewObject() working again with RTTI/dynamic_cast - when I first created it, it did work, but since pooling + factory creation this no longer works, hence I've had to create NotifyNewConnection(), network, etc. These can be deleted if this is fixable! (CRTP looks interesting but unsuitable)
Definition at line 107 of file IrcEngine.h.
Constructor & Destructor Documentation
IrcEngine::IrcEngine () [private]
Definition at line 28 of file IrcEngine.cc.
{
        _ircobject_factory.reset(new IrcFactory(this));
}
IrcEngine::~IrcEngine ()
Definition at line 35 of file IrcEngine.cc.
References _ircobject_factory.
{
        _ircobject_factory.release();
}
IrcEngine::IrcEngine () [private]
IrcEngine::~IrcEngine ()
Member Function Documentation
IrcChannel* IrcEngine::ActiveChannel () [inline]
Retrieves the 'active' IrcChannel (the one the user has requested to set focus to, or the only one present on the connection).
Todo
Reference + Dereference needed?
Definition at line 183 of file bak/IrcEngine.h.
        { return _active_channel.get(); }
std::shared_ptr<IrcChannel> IrcEngine::ActiveChannel ()
Retrieves the 'active' IrcChannel (the one the user has requested to set focus to, or the only one present on the connection).
IrcConnection* IrcEngine::ActiveConnection () [inline]
Retrieves the 'active' IrcConnection (the one the user has requested to set focus to, or the only one present on creation/closure).
Todo
Reference + Dereference needed?
Definition at line 194 of file bak/IrcEngine.h.
        { return _active_connection.get(); }
std::shared_ptr<IrcConnection> IrcEngine::ActiveConnection ()
Retrieves the 'active' IrcConnection (the one the user has requested to set focus to, or the only one present on creation/closure).
void IrcEngine::AttachListener (IrcListener *listener)
Attaches an IrcListener to receive notifications of NotifyData() - it must be detached when it is finished.
See Also:
DetachListener(), NotifyData()
Parameters:
listener The IrcListener to add
void IrcEngine::AttachListener (IrcListener *listener)
Attaches an IrcListener to receive notifications of NotifyData() - it must be detached when it is finished.
Never fails.
See Also:
DetachListener(), NotifyData()
Parameters:
listener The IrcListener to add
Definition at line 43 of file IrcEngine.cc.
References _listeners.
{
        assert(listener != nullptr);
        _listeners.insert(listener);
}
std::vector< IrcConnection * > IrcEngine::Connections () const
Retrieves the vector for all known IrcConnection objects; the list is a copy, and makes no guarantee as to the lifetime of each connection.
Returns:
Returns a vector of IrcConnection pointers
Definition at line 54 of file bak/IrcEngine.cc.
References _connections.
{
        return _connections;
}
EIrcStatus IrcEngine::CreateChannel (const uint32_tconnection_id, const char *name)
Definition at line 55 of file IrcEngine.cc.
References IrcFactory::CreateIrcChannel(), Factory(), ObjectAddError, OK, and Pools().
Referenced by IrcParser::HandleJoin().
{
        return Factory()->CreateIrcChannel(
                Pools()->GetConnection(connection_id),
                name
        ) == nullptr ? EIrcStatus::ObjectAddError : EIrcStatus::OK;
}
EIrcStatus IrcEngine::CreateConnection (const char *network)
Definition at line 69 of file IrcEngine.cc.
References IrcFactory::CreateIrcConnection(), Factory(), ObjectAddError, OK, and Pools().
Referenced by IrcNetwork::Setup().
{
        return Factory()->CreateIrcConnection(
                Pools()->GetNetwork(network)
        ) == nullptr ? EIrcStatus::ObjectAddError : EIrcStatus::OK;
}
EIrcStatus IrcEngine::CreateNetwork (const char *name)
Definition at line 81 of file IrcEngine.cc.
References IrcFactory::CreateIrcNetwork(), Factory(), ObjectAddError, and OK.
{
        return Factory()->CreateIrcNetwork(
                name
        ) == nullptr ? EIrcStatus::ObjectAddError : EIrcStatus::OK;
}
EIrcStatus IrcEngine::CreateUser (const uint32_tconnection_id, const char *channel, const char *name, const char *ident, const char *hostmask)
Definition at line 93 of file IrcEngine.cc.
References IrcFactory::CreateIrcUser(), Factory(), ObjectAddError, OK, and Pools().
Referenced by IrcChannel::AddNamesUser(), and IrcParser::HandleJoin().
{
        return Factory()->CreateIrcUser(
                Pools()->GetChannel(connection_id, channel),
                name, ident, hostmask
        ) == nullptr ? EIrcStatus::ObjectAddError : EIrcStatus::OK;
}
void IrcEngine::DetachListener (IrcListener *listener)
Detaches an IrcListener previously attached. Once removed, the object will not longer receive notifications of new data on connections.
See Also:
AttachListener(), NotifyData()
Parameters:
listener The IrcListener to remove
void IrcEngine::DetachListener (IrcListener *listener)
Detaches an IrcListener previously attached. Once removed, the object will not longer receive notifications of new data on connections.
See Also:
AttachListener(), NotifyData()
Parameters:
listener The IrcListener to remove
Definition at line 110 of file IrcEngine.cc.
References _listeners.
{
        assert(listener != nullptr);
        _listeners.erase(_listeners.find(listener));
}
IrcFactory * IrcEngine::Factory () const [private]
Retrieves a pointer to the IRC Object Factory, used for creating new channels, users, connections, etc. - they are all allocated via a pool for efficiency purposes.
Private as only the engine itself can be authorized to create new IrcObjects.
Warning:
Always access through this function, and not the raw pointer, as the factory is not created/constructed until this has been called for the first time.
Return values:
IrcFactory*
Definition at line 122 of file IrcEngine.cc.
References _ircobject_factory.
Referenced by IrcConnection::AddChannel(), IrcChannel::AddUser(), CreateChannel(), CreateConnection(), CreateNetwork(), CreateUser(), IrcConnection::DeleteChannel(), and IrcChannel::DeleteUser().
{
        return _ircobject_factory.get();
}
IrcFactory* IrcEngine::Factory () const
Retrieves a pointer to the IRC Object Factory, used for creating new channels, users, connections, etc. - they are all allocated via a pool for efficiency purposes.
IrcEngine::int::spawn_interface () [private]
std::vector< IrcNetwork * > IrcEngine::Networks () const
Retrieves the vector for all known IrcNetwork objects; the list is a copy, and makes no guarantee as to the lifetime of each connection.
Returns:
Returns a vector of IrcNetwork pointers
Definition at line 80 of file bak/IrcEngine.cc.
References _networks.
{
        return _networks;
}
IrcEngine::NO_CLASS_ASSIGNMENT (IrcEngine) [private]
IrcEngine::NO_CLASS_ASSIGNMENT (IrcEngine) [private]
IrcEngine::NO_CLASS_COPY (IrcEngine) [private]
IrcEngine::NO_CLASS_COPY (IrcEngine) [private]
void IrcEngine::NotifyDeleteConnection (IrcConnection *connection)
Definition at line 151 of file bak/IrcEngine.cc.
References _active_connection, _connections, and UNREFERENCE_OBJECT.
{
        if ( connection == _active_connection.get() )
                _active_connection.reset(nullptr);
        
        UNREFERENCE_OBJECT(connection);
        _connections.erase(std::find(_connections.begin(), _connections.end(), connection));
}
void IrcEngine::NotifyDeleteNetwork (IrcNetwork *network)
Definition at line 166 of file bak/IrcEngine.cc.
References _networks, and UNREFERENCE_OBJECT.
{
        UNREFERENCE_OBJECT(network);
        _networks.erase(std::find(_networks.begin(), _networks.end(), network));
}
void IrcEngine::NotifyDeleteObject (IrcObject *object)
Warning:
Called within the destructor for IrcObject - do not call manually.
See Also:
NotifyNewObject()
Parameters:
object The Object deleted
Definition at line 141 of file bak/IrcEngine.cc.
References _objects.
{
        _objects.erase(std::find(_objects.begin(), _objects.end(), object));
}
void IrcEngine::NotifyListeners (E_IRC_LISTENER_NOTIFICATIONevent_type, IrcConnection *connection) const [private]
Called within IrcConnection whenever it successfully adds data to its receive queue; the event_type will be LN_NewData.
Also called from the IrcParser whenever a supported event is parsed out; a '001' results in LN_001, another user joining results in LN_Join, and so forth.
This informs all the _listeners by triggering their own notification handlers, ready for optional processing.
See Also:
AttachListener(), DetachListener()
Parameters:
event_type The event that triggered this notification
connection The IrcConnection this event occurred in
Definition at line 88 of file bak/IrcEngine.cc.
References _listeners, fg_red(), IrcConnection::GetActivity(), LN_001, LN_002, LN_003, LN_004, LN_005, LN_331, LN_332, LN_353, LN_366, LN_Cap, LN_ConnectionReady, LN_GotChannelMode, LN_GotKicked, LN_GotKilled, LN_GotNickChanged, LN_GotUserMode, LN_Invite, LN_Join, LN_Kick, LN_Kill, LN_Mode, LN_NewData, LN_Nick, LN_Notice, LN_Part, LN_Privmsg, LN_Quit, LN_SentInvite, LN_SentPrivmsg, LN_Topic, LN_WeJoined, LN_WeKicked, LN_WeParted, and LN_WeQuit.
{
        for ( auto l : _listeners )
        {
                switch ( event_type )
                {
                case LN_NewData: l->OnData(connection); break;
                case LN_001: l->On001(connection, connection->GetActivity()); break;
                case LN_002: l->On002(connection, connection->GetActivity()); break;
                case LN_003: l->On003(connection, connection->GetActivity()); break;
                case LN_004: l->On004(connection, connection->GetActivity()); break;
                case LN_005: l->On005(connection, connection->GetActivity()); break;
                case LN_331: l->On331(connection, connection->GetActivity()); break;
                case LN_332: l->On332(connection, connection->GetActivity()); break;
                case LN_353: l->On353(connection, connection->GetActivity()); break;
                case LN_366: l->On366(connection, connection->GetActivity()); break;
                case LN_ConnectionReady: /* what to do? */break;
                case LN_Cap: l->OnCap(connection, connection->GetActivity()); break;
                case LN_Invite: l->OnInvite(connection, connection->GetActivity()); break;
                case LN_Join: l->OnJoin(connection, connection->GetActivity()); break;
                case LN_Kick: l->OnKick(connection, connection->GetActivity()); break;
                case LN_Kill: l->OnKill(connection, connection->GetActivity()); break;
                case LN_Mode: l->OnMode(connection, connection->GetActivity()); break;
                case LN_Nick: l->OnNick(connection, connection->GetActivity()); break;
                case LN_Notice: l->OnNotice(connection, connection->GetActivity()); break;
                case LN_Part: l->OnPart(connection, connection->GetActivity()); break;
                case LN_Privmsg: l->OnPrivmsg(connection, connection->GetActivity()); break;
                case LN_Quit: l->OnQuit(connection, connection->GetActivity()); break;
                case LN_Topic: l->OnTopic(connection, connection->GetActivity()); break;
                case LN_SentInvite: l->OnOurInvite(connection, connection->GetActivity()); break;
                case LN_WeJoined: l->OnOurJoin(connection, connection->GetActivity()); break;
                case LN_WeKicked: l->OnOurKick(connection, connection->GetActivity()); break;
                case LN_GotKicked: l->OnOurKicked(connection, connection->GetActivity()); break;
                case LN_GotNickChanged: l->OnOurNick(connection, connection->GetActivity()); break;
                case LN_SentPrivmsg: l->OnOurPrivmsg(connection, connection->GetActivity()); break;
                case LN_GotUserMode: l->OnOurServerMode(connection, connection->GetActivity()); break;
                case LN_GotChannelMode: l->OnOurMode(connection, connection->GetActivity()); break;
                case LN_GotKilled: l->OnOurKilled(connection, connection->GetActivity()); break;
                case LN_WeParted: l->OnOurPart(connection, connection->GetActivity()); break;
                case LN_WeQuit: l->OnOurQuit(connection, connection->GetActivity()); break;
                default:
                        std::cerr << fg_red << "Unhandled event type received (" << event_type << ")";
                        break;
                }
        }
}
void IrcEngine::NotifyListeners (E_IRC_LISTENER_NOTIFICATIONevent_type, std::shared_ptr< IrcConnection >connection) const [private]
Called within IrcConnection whenever it successfully adds data to its receive queue; the event_type will be LN_NewData.
Also called from the IrcParser whenever a supported event is parsed out; a '001' results in LN_001, another user joining results in LN_Join, and so forth.
This informs all the _listeners by triggering their own notification handlers, ready for optional processing.
See Also:
AttachListener(), DetachListener()
Parameters:
event_type The event that triggered this notification
connection The IrcConnection this event occurred in
Definition at line 130 of file IrcEngine.cc.
References _listeners, fg_red(), LN_001, LN_002, LN_003, LN_004, LN_005, LN_331, LN_332, LN_353, LN_366, LN_Cap, LN_ConnectionReady, LN_GotChannelMode, LN_GotKicked, LN_GotKilled, LN_GotNickChanged, LN_GotUserMode, LN_Invite, LN_Join, LN_Kick, LN_Kill, LN_Mode, LN_NewData, LN_Nick, LN_Notice, LN_Part, LN_Privmsg, LN_Quit, LN_SentInvite, LN_SentPrivmsg, LN_Topic, LN_WeJoined, LN_WeKicked, LN_WeParted, and LN_WeQuit.
Referenced by IrcConnection::EstablishConnection(), IrcParser::Handle001(), IrcParser::Handle002(), IrcParser::Handle003(), IrcParser::Handle004(), IrcParser::Handle005(), IrcParser::Handle332(), IrcParser::Handle353(), IrcParser::Handle366(), IrcParser::HandleCap(), IrcParser::HandleInvite(), IrcParser::HandleJoin(), IrcParser::HandleKick(), IrcParser::HandleKill(), IrcParser::HandleNick(), IrcParser::HandlePart(), IrcParser::HandlePrivmsg(), IrcParser::HandleQuit(), and IrcParser::HandleTopic().
{
        for ( auto l : _listeners )
        {
                switch ( event_type )
                {
                case LN_NewData: l->OnData(connection); break;
                case LN_001: l->On001(connection, connection->GetActivity()); break;
                case LN_002: l->On002(connection, connection->GetActivity()); break;
                case LN_003: l->On003(connection, connection->GetActivity()); break;
                case LN_004: l->On004(connection, connection->GetActivity()); break;
                case LN_005: l->On005(connection, connection->GetActivity()); break;
                case LN_331: l->On331(connection, connection->GetActivity()); break;
                case LN_332: l->On332(connection, connection->GetActivity()); break;
                case LN_353: l->On353(connection, connection->GetActivity()); break;
                case LN_366: l->On366(connection, connection->GetActivity()); break;
                case LN_ConnectionReady: /* what to do? */break;
                case LN_Cap: l->OnCap(connection, connection->GetActivity()); break;
                case LN_Invite: l->OnInvite(connection, connection->GetActivity()); break;
                case LN_Join: l->OnJoin(connection, connection->GetActivity()); break;
                case LN_Kick: l->OnKick(connection, connection->GetActivity()); break;
                case LN_Kill: l->OnKill(connection, connection->GetActivity()); break;
                case LN_Mode: l->OnMode(connection, connection->GetActivity()); break;
                case LN_Nick: l->OnNick(connection, connection->GetActivity()); break;
                case LN_Notice: l->OnNotice(connection, connection->GetActivity()); break;
                case LN_Part: l->OnPart(connection, connection->GetActivity()); break;
                case LN_Privmsg: l->OnPrivmsg(connection, connection->GetActivity()); break;
                case LN_Quit: l->OnQuit(connection, connection->GetActivity()); break;
                case LN_Topic: l->OnTopic(connection, connection->GetActivity()); break;
                case LN_SentInvite: l->OnOurInvite(connection, connection->GetActivity()); break;
                case LN_WeJoined: l->OnOurJoin(connection, connection->GetActivity()); break;
                case LN_WeKicked: l->OnOurKick(connection, connection->GetActivity()); break;
                case LN_GotKicked: l->OnOurKicked(connection, connection->GetActivity()); break;
                case LN_GotNickChanged: l->OnOurNick(connection, connection->GetActivity()); break;
                case LN_SentPrivmsg: l->OnOurPrivmsg(connection, connection->GetActivity()); break;
                case LN_GotUserMode: l->OnOurServerMode(connection, connection->GetActivity()); break;
                case LN_GotChannelMode: l->OnOurMode(connection, connection->GetActivity()); break;
                case LN_GotKilled: l->OnOurKilled(connection, connection->GetActivity()); break;
                case LN_WeParted: l->OnOurPart(connection, connection->GetActivity()); break;
                case LN_WeQuit: l->OnOurQuit(connection, connection->GetActivity()); break;
                default:
                        std::cerr << fg_red << "Unhandled event type received (" << event_type << ")";
                        break;
                }
        }
}
void IrcEngine::NotifyNewConnection (IrcConnection *connection)
Definition at line 178 of file bak/IrcEngine.cc.
References _active_connection, _connections, and REFERENCE_OBJECT.
Referenced by IrcConnection::IrcConnection().
{
        if ( _active_connection == nullptr )
                _active_connection.reset(connection);
        REFERENCE_OBJECT(connection);
        
        _connections.push_back(connection);
}
void IrcEngine::NotifyNewNetwork (IrcNetwork *network)
Definition at line 193 of file bak/IrcEngine.cc.
References _networks, and REFERENCE_OBJECT.
{
        REFERENCE_OBJECT(network);
        _networks.push_back(network);
}
void IrcEngine::NotifyNewObject (IrcObject *object)
Enables the engine to keep track and iterate through all the created objects.
Warning:
Called within the constructor for IrcObject - do not call manually.
See Also:
NotifyDeleteObject()
Parameters:
object The Object created
Definition at line 205 of file bak/IrcEngine.cc.
References _connections, _networks, _objects, fg_cyan(), and fg_white().
{
        _objects.push_back(object);
#if 0 // Code Removed: No longer works - did when i first created it though!
        IrcNetwork* rtti_network;
        IrcConnection* rtti_connection;
        //IrcChannel* rtti_channel;
        // etc.
        std::cout << fg_cyan << object << fg_white << " is a " << typeid(object).name() << "\n";
        if (( rtti_connection = dynamic_cast<IrcConnection*>(object)) != nullptr )
        {
                _connections.push_back(rtti_connection);
        }
        else if (( rtti_network = dynamic_cast<IrcNetwork*>(object)) != nullptr )
        {
                _networks.push_back(rtti_network);
        }
#endif
}
IrcParser* IrcEngine::Parser () const
Retrieves the IrcParser.
Return values:
A pointer to the IrcParser
IrcParser * IrcEngine::Parser () const
Retrieves the IrcParser. Never fails - created on the stack as a static variable.
Return values:
A pointer to the IrcParser
Definition at line 183 of file IrcEngine.cc.
Referenced by IrcConnection::EstablishConnection().
{
        static IrcParser parser;
        return &parser;
}
IrcPool* IrcEngine::Pools () const
Gets the IrcObject pool allocator.
Returns:
A pointer to the static instance within the class.
IrcPool * IrcEngine::Pools () const
Gets the IrcObject pool allocator. Never fails - created on the stack as a static variable.
Returns:
A pointer to the IrcPool
Definition at line 193 of file IrcEngine.cc.
Referenced by IrcConnection::AddChannel(), IrcChannel::AddNamesUser(), CreateChannel(), CreateConnection(), IrcFactory::CreateIrcChannel(), IrcFactory::CreateIrcConnection(), IrcFactory::CreateIrcNetwork(), IrcFactory::CreateIrcUser(), CreateUser(), IrcConnection::DeleteChannel(), IrcFactory::DeleteIrcObject(), IrcChannel::DeleteUser(), IrcConnection::EraseChannelList(), IrcChannel::EraseNameslist(), IrcConnection::EstablishConnection(), IrcConnection::GetChannel(), IrcChannel::GetUser(), IrcParser::HandleQuit(), and IrcParser::RunParser().
{
        static IrcPool pools;
        return &pools;
}
Friends And Related Function Documentation
void* instance (void *params) [friend]
Returns a pointer to the interface instance. Return type must be void as the api/runtime cannot know what object the instance will be, since it's compiled with no knowledge of the interface.
Warning:
Assumes spawn_interface() has been called before now as part of the loading procedure, which creates the object this refers to. Third-party interfaces can do this however they want, but is useful to know what to expect.
Definition at line 35 of file interface.cc.
{
        // unused
        params;
        return irc_engine.get();
}
IrcConnection [friend]
Definition at line 114 of file IrcEngine.h.
IrcParser [friend]
Definition at line 115 of file IrcEngine.h.
Member Data Documentation
std::string IrcEngine::_active_channel [private]
The 'active' IrcChannel
Definition at line 138 of file IrcEngine.h.
std::unique_ptr<IrcChannel> IrcEngine::_active_channel [private]
Definition at line 141 of file bak/IrcEngine.h.
std::string IrcEngine::_active_connection [private]
The 'active' IrcConnection
Definition at line 136 of file IrcEngine.h.
Referenced by NotifyDeleteConnection(), and NotifyNewConnection().
std::unique_ptr<IrcConnection> IrcEngine::_active_connection [private]
The 'active' IrcConnection
Definition at line 140 of file bak/IrcEngine.h.
std::vector<IrcConnection*> IrcEngine::_connections [private]
Connections tracking
Definition at line 135 of file bak/IrcEngine.h.
Referenced by Connections(), NotifyDeleteConnection(), NotifyNewConnection(), and NotifyNewObject().
std::unique_ptr< IrcFactory > IrcEngine::_ircobject_factory [private]
IrcObject creation factory
Definition at line 141 of file IrcEngine.h.
Referenced by Factory(), and ~IrcEngine().
std::set< IrcListener * > IrcEngine::_listeners [private]
The listeners receive all data on every connection; the first member is always the parser, while subsequent members are usually the user interface(s) and any plugins present
Definition at line 124 of file IrcEngine.h.
Referenced by AttachListener(), DetachListener(), and NotifyListeners().
std::vector<IrcNetwork*> IrcEngine::_networks [private]
Networks tracking
Definition at line 137 of file bak/IrcEngine.h.
Referenced by Networks(), NotifyDeleteNetwork(), NotifyNewNetwork(), and NotifyNewObject().
std::vector<IrcObject*> IrcEngine::_objects [private]
Keeps knowledge of every IRC object created
Definition at line 133 of file bak/IrcEngine.h.
Referenced by NotifyDeleteObject(), and NotifyNewObject().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.