.TH "IrcEngine.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IrcEngine.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'IrcListener\&.h'\fP
.br
\fC#include 'interface\&.h'\fP
.br
\fC#include 'IrcFactory\&.h'\fP
.br
\fC#include 'irc_status\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIrcEngine\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIRC_MODULE_NAME\fP   'libirc'"
.br
.ti -1c
.RI "#define \fBIRC_RUNTIME_MODULE\fP   \fBIrcEngine\fP* zxcvbnm = static_cast<\fBIrcEngine\fP*>(runtime\&.GetObjectFromModule(\fBIRC_MODULE_NAME\fP));zxcvbnm"
.br
.ti -1c
.RI "#define \fBIRC_ENGINE\fP   (static_cast<\fBIrcEngine\fP*>(\fBinstance\fP(nullptr)))"
.br
.ti -1c
.RI "#define \fBMAX_BUF_IRC_MSG_CRLF\fP   513"
.br
.ti -1c
.RI "#define \fBMAX_BUF_IRC_MSG\fP   (\fBMAX_BUF_IRC_MSG_CRLF\fP - 2)"
.br
.ti -1c
.RI "#define \fBMAX_LEN_IRC_MSG_CRLF\fP   (\fBMAX_BUF_IRC_MSG_CRLF\fP - 1)"
.br
.ti -1c
.RI "#define \fBMAX_LEN_IRC_MSG\fP   (\fBMAX_BUF_IRC_MSG_CRLF\fP - 3)"
.br
.ti -1c
.RI "#define \fBX509_MAX_ATTRIBUTE_LENGTH\fP   256"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBE_CONNECTION_STATE\fP { \fBCS_Unknown\fP = 0x00, \fBCS_Disconnected\fP = 0x01, \fBCS_Disconnecting\fP = 0x02, \fBCS_Connecting\fP = 0x04, \fBCS_Active\fP = 0x08, \fBCS_InitSent\fP = 0x10, \fBCS_RecvNames\fP = 0x80, \fBCS_Unknown\fP = 0x00, \fBCS_Disconnected\fP = 0x01, \fBCS_Disconnecting\fP = 0x02, \fBCS_Connecting\fP = 0x04, \fBCS_Active\fP = 0x08, \fBCS_InitSent\fP = 0x10, \fBCS_RecvNames\fP = 0x80 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IRC_ENGINE   (static_cast<\fBIrcEngine\fP*>(\fBinstance\fP(nullptr)))"
Same purpose as IRC_RUNTIME_MODULE, but localized to this project, as we can access the variable without touching the runtime\&. Most IrcObjects have the _irc_engine available already, but this is for those that don't\&. 
.PP
Definition at line 62 of file IrcEngine\&.h\&.
.SS "#define IRC_MODULE_NAME   'libirc'"
Module name accessor for the runtime 
.PP
Definition at line 53 of file IrcEngine\&.h\&.
.PP
Referenced by IrcObject::IrcObject()\&.
.SS "#define IRC_RUNTIME_MODULE   \fBIrcEngine\fP* zxcvbnm = static_cast<\fBIrcEngine\fP*>(runtime\&.GetObjectFromModule(\fBIRC_MODULE_NAME\fP));zxcvbnm"
Shorthand version of module accessor for cleaner looking code 
.PP
Definition at line 56 of file IrcEngine\&.h\&.
.SS "#define MAX_BUF_IRC_MSG   (\fBMAX_BUF_IRC_MSG_CRLF\fP - 2)"
Max size for an IRC message buffer without the CRLF 
.PP
Definition at line 69 of file IrcEngine\&.h\&.
.PP
Referenced by IrcConnection::AddToRecvQueue(), IrcConnection::SendAway(), IrcConnection::SendCTCP(), IrcConnection::SendCTCPNotice(), IrcConnection::SendIdentify(), IrcConnection::SendInit(), IrcConnection::SendInvite(), IrcConnection::SendJoin(), IrcConnection::SendKick(), IrcConnection::SendMode(), IrcConnection::SendNick(), IrcConnection::SendNotice(), IrcConnection::SendPart(), IrcConnection::SendPrivmsg(), IrcConnection::SendQuit(), IrcConnection::SendTopic(), and IrcConnection::SendUser()\&.
.SS "#define MAX_BUF_IRC_MSG_CRLF   513"
Max size for an IRC message buffer; 512, + terminating nul 
.PP
Definition at line 66 of file IrcEngine\&.h\&.
.PP
Referenced by IrcConnection::EstablishConnection(), and IrcConnection::SendBypass()\&.
.SS "#define MAX_LEN_IRC_MSG   (\fBMAX_BUF_IRC_MSG_CRLF\fP - 3)"
Max length for an IRC message without the CRLF 
.PP
Definition at line 75 of file IrcEngine\&.h\&.
.SS "#define MAX_LEN_IRC_MSG_CRLF   (\fBMAX_BUF_IRC_MSG_CRLF\fP - 1)"
Max length for an IRC message 
.PP
Definition at line 72 of file IrcEngine\&.h\&.
.SS "#define X509_MAX_ATTRIBUTE_LENGTH   256"
Maximum length of a X\&.509 attribute; 
.PP
\fBWarning:\fP
.RS 4
the rfc does NOT specify this! 
.RE
.PP

.PP
Definition at line 78 of file IrcEngine\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBE_CONNECTION_STATE\fP"
An enumeration for all the variable connection states that a connection can be in - naturally these are different from the socket TCP/IP states\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICS_Unknown \fP\fP
Default connection state (invalid) 
.TP
\fB\fICS_Disconnected \fP\fP
Connection has become disconnected 
.TP
\fB\fICS_Disconnecting \fP\fP
In the process of disconnecting 
.TP
\fB\fICS_Connecting \fP\fP
In the process of connecting 
.TP
\fB\fICS_Active \fP\fP
Connected and established 
.TP
\fB\fICS_InitSent \fP\fP
Init (nick, user) sent to server 
.TP
\fB\fICS_RecvNames \fP\fP
Currently receiving a 353 NAMES 
.TP
\fB\fICS_Unknown \fP\fP
Default connection state (invalid) 
.TP
\fB\fICS_Disconnected \fP\fP
Connection has become disconnected 
.TP
\fB\fICS_Disconnecting \fP\fP
In the process of disconnecting 
.TP
\fB\fICS_Connecting \fP\fP
In the process of connecting 
.TP
\fB\fICS_Active \fP\fP
Connected and established 
.TP
\fB\fICS_InitSent \fP\fP
Init (nick, user) sent to server 
.TP
\fB\fICS_RecvNames \fP\fP
Currently receiving a 353 NAMES 
.PP
Definition at line 88 of file IrcEngine\&.h\&.
.PP
.nf
89 {
90         CS_Unknown = 0x00,              
91         CS_Disconnected = 0x01,         
92         CS_Disconnecting = 0x02,        
93         CS_Connecting = 0x04,           
94         CS_Active = 0x08,               
95         CS_InitSent = 0x10,             
96         CS_RecvNames = 0x80,            
97 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
