IrcFactory
NAME
IrcFactory -
SYNOPSIS
#include <IrcFactory.h>
Public Member Functions
~IrcFactory ()
std::shared_ptr< IrcChannel > CreateIrcChannel (std::shared_ptr< IrcConnection > parent_connection, const char *channel_name)
std::shared_ptr< IrcConnection > CreateIrcConnection (std::shared_ptr< IrcNetwork > parent_network)
std::shared_ptr< IrcNetwork > CreateIrcNetwork (const char *group_name)
std::shared_ptr< IrcUser > CreateIrcUser (std::shared_ptr< IrcChannel > channel, const char *nickname, const char *ident, const char *hostmask)
~IrcFactory ()
IrcChannel * CreateIrcChannel (IrcConnection *parent_connection, const char *channel_name)
IrcConnection * CreateIrcConnection (IrcNetwork *parent_network)
IrcNetwork * CreateIrcNetwork (const char *group_name)
IrcUser * CreateIrcUser (IrcChannel *channel, const char *nickname, const char *ident, const char *hostmask)
void DeleteIrcObject (IrcObject *object)
Private Member Functions
NO_CLASS_ASSIGNMENT (IrcFactory)
NO_CLASS_COPY (IrcFactory)
IrcFactory (IrcEngine *engine)
NO_CLASS_ASSIGNMENT (IrcFactory)
NO_CLASS_COPY (IrcFactory)
IrcFactory (IrcEngine *engine)
Private Attributes
IrcEngine * _engine
Friends
class IrcEngine
Detailed Description
Plugins should have no need to create any of the objects we supply, so all the rules regarding referencing and deletion functions should only apply to our own internal code.
Our memory debugging macros make this classes function declarations look peculiar at best, definitely violating our own style guidelines - but it's the only way to get the functionality we desire without hardcoding, or adding huge duplicated 'if' preprocessor blocks.
Definition at line 41 of file IrcFactory.h.
Constructor & Destructor Documentation
IrcFactory::IrcFactory (IrcEngine *engine) [private]
Definition at line 29 of file IrcFactory.cc.
: _engine(engine)
{
}
IrcFactory::~IrcFactory ()
Definition at line 38 of file IrcFactory.cc.
{
}
IrcFactory::IrcFactory (IrcEngine *engine) [private]
IrcFactory::~IrcFactory ()
Member Function Documentation
IrcChannel * IrcFactory::CreateIrcChannel (IrcConnection *parent_connection, const char *channel_name)
Creates and constructs a new IrcChannel.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcChannel()
Definition at line 51 of file bak/IrcFactory.cc.
References _engine, ObjectPool< T >::Get(), IrcPool::IrcChannels(), IRCPOOL_GET_ARGS, and IrcEngine::Pools().
{
        // obtain an IrcChannel from the object pool
        IrcChannel* channel = _engine->Pools()->IrcChannels()->Get(IRCPOOL_GET_ARGS);
        
        // placement new with constructor arguments
        channel = ::new (channel) IrcChannel(parent_connection, channel_name);
        /* the constructors for the Irc objects notify the IrcEngine of their
         * creation, in turn referencing them. As such, we don't need to do so
         * here. */
        return channel;
}
std::shared_ptr< IrcChannel > IrcFactory::CreateIrcChannel (std::shared_ptr< IrcConnection >parent_connection, const char *channel_name)
Creates and constructs a new IrcChannel.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcChannel()
Definition at line 51 of file IrcFactory.cc.
References _engine, ObjectPool< T >::GetObject(), IrcPool::IrcChannels(), IRCPOOL_GET_ARGS, and IrcEngine::Pools().
Referenced by IrcConnection::AddChannel(), and IrcEngine::CreateChannel().
{
        // obtain an IrcChannel from the object pool
        std::shared_ptr<IrcChannel> channel = _engine->Pools()->IrcChannels()->GetObject(IRCPOOL_GET_ARGS);
        // as we're dealing with a shared_ptr, we need the raw type for the next step
        IrcChannel* c = channel.get();
        // placement new with constructor arguments, using raw type
        c = ::new (c) IrcChannel(parent_connection, channel_name);
        
        // return the shared_ptr, internal object constructed
        return channel;
}
IrcConnection * IrcFactory::CreateIrcConnection (IrcNetwork *parent_network)
Creates and constructs a new IrcConnection.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcConnection()
Definition at line 72 of file bak/IrcFactory.cc.
References _engine, ObjectPool< T >::Get(), IrcPool::IrcConnections(), IRCPOOL_GET_ARGS, and IrcEngine::Pools().
{
        IrcConnection* connection = _engine->Pools()->IrcConnections()->Get(IRCPOOL_GET_ARGS);
        
        connection = ::new (connection) IrcConnection(parent_network);
        return connection;
}
std::shared_ptr< IrcConnection > IrcFactory::CreateIrcConnection (std::shared_ptr< IrcNetwork >parent_network)
Creates and constructs a new IrcConnection.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcConnection()
Definition at line 71 of file IrcFactory.cc.
References _engine, ObjectPool< T >::GetObject(), IrcPool::IrcConnections(), IRCPOOL_GET_ARGS, and IrcEngine::Pools().
Referenced by IrcEngine::CreateConnection().
{
        std::shared_ptr<IrcConnection> connection = _engine->Pools()->IrcConnections()->GetObject(IRCPOOL_GET_ARGS);
        IrcConnection* c = connection.get();
        c = ::new (c) IrcConnection(parent_network);
        return connection;
}
IrcNetwork* IrcFactory::CreateIrcNetwork (const char *group_name)
Creates and constructs a new IrcNetwork.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcNetwork()
IrcNetwork * IrcFactory::CreateIrcNetwork (const char *group_name)
Creates and constructs a new IrcNetwork.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcNetwork()
Definition at line 86 of file IrcFactory.cc.
References _engine, ObjectPool< T >::GetObject(), IrcPool::IrcNetworks(), IRCPOOL_GET_ARGS, and IrcEngine::Pools().
Referenced by IrcEngine::CreateNetwork().
{
        std::shared_ptr<IrcNetwork> network = _engine->Pools()->IrcNetworks()->GetObject(IRCPOOL_GET_ARGS);
        IrcNetwork* n = network.get();
        n = ::new (n) IrcNetwork(group_name);
        return network;
}
IrcUser * IrcFactory::CreateIrcUser (IrcChannel *channel, const char *nickname, const char *ident, const char *hostmask)
Creates and constructs a new IrcUser.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcUser()
Definition at line 101 of file bak/IrcFactory.cc.
References _engine, ObjectPool< T >::Get(), IRCPOOL_GET_ARGS, IrcPool::IrcUsers(), and IrcEngine::Pools().
{
        IrcUser* user = _engine->Pools()->IrcUsers()->Get(IRCPOOL_GET_ARGS);
        
        user = ::new (user) IrcUser(channel, nickname, ident, hostmask);
        return user;
}
std::shared_ptr< IrcUser > IrcFactory::CreateIrcUser (std::shared_ptr< IrcChannel >channel, const char *nickname, const char *ident, const char *hostmask)
Creates and constructs a new IrcUser.
The object is actually returned from a memory pool, and constructed via placement new.
The function arguments match those of the normal constructor. If memory debugging is enabled for the build, the debug info is also supplied in at the same time.
Warning:
Do not use standard deletion functions/macros to free the object; it must be passed into DeleteIrcObject(), which handles the freeing of the memory directly from its pool.
The object is referenced before it is returned, so do not call it manually. In turn, when you want to delete it, do not dereference it; just call DeleteIrcObject()
See Also:
Pool::Get()
DeleteIrcObject()
IrcUser()
Definition at line 101 of file IrcFactory.cc.
References _engine, ObjectPool< T >::GetObject(), IRCPOOL_GET_ARGS, IrcPool::IrcUsers(), and IrcEngine::Pools().
Referenced by IrcChannel::AddUser(), and IrcEngine::CreateUser().
{
        std::shared_ptr<IrcUser> user = _engine->Pools()->IrcUsers()->GetObject(IRCPOOL_GET_ARGS);
        IrcUser* u = user.get();
        u = ::new (u) IrcUser(channel, nickname, ident, hostmask);
        return user;
}
void IrcFactory::DeleteIrcObject (IrcObject *object)
To be used for deleting an IRC object returned from this factorys methods.
Yes, we could have a separate function for each IRC object type; but they would all do the same thing as this, just with a little less runtime overhead, in return for less code duplication.
Parameters:
object The IRC object to return to its respective pool
Definition at line 118 of file bak/IrcFactory.cc.
References _engine, fg_red(), ObjectPool< T >::Free(), IrcPool::IrcChannels(), IrcPool::IrcConnections(), IrcPool::IrcNetworks(), IrcPool::IrcUsers(), LOG, and IrcEngine::Pools().
Referenced by IrcConnection::DeleteChannel(), and IrcChannel::DeleteUser().
{
        IrcChannel* rtti_channel;
        IrcConnection* rtti_connection;
        IrcNetwork* rtti_network;
        IrcUser* rtti_user;
        // Pools' Free() executes a Dereference(), we don't need to
        if (( rtti_channel = dynamic_cast<IrcChannel*>(object)) != nullptr )
        {
                _engine->Pools()->IrcChannels()->Free(rtti_channel);
        }
        else if (( rtti_connection = dynamic_cast<IrcConnection*>(object)) != nullptr )
        {
                _engine->Pools()->IrcConnections()->Free(rtti_connection);
        }
        else if (( rtti_network = dynamic_cast<IrcNetwork*>(object)) != nullptr )
        {
                _engine->Pools()->IrcNetworks()->Free(rtti_network);
        }
        else if (( rtti_user = dynamic_cast<IrcUser*>(object)) != nullptr )
        {
                _engine->Pools()->IrcUsers()->Free(rtti_user);
        }
        else
        {
                std::cerr << fg_red << "The object " << std::hex << object << " did not match an IRC type\n";
                LOG(LL_Error) << "The object " << std::hex << object << " did not match an IRC type\n";
        }
}
IrcFactory::NO_CLASS_ASSIGNMENT (IrcFactory) [private]
IrcFactory::NO_CLASS_ASSIGNMENT (IrcFactory) [private]
IrcFactory::NO_CLASS_COPY (IrcFactory) [private]
IrcFactory::NO_CLASS_COPY (IrcFactory) [private]
Friends And Related Function Documentation
IrcEngine [friend]
Definition at line 44 of file IrcFactory.h.
Member Data Documentation
IrcEngine * IrcFactory::_engine [private]
A pointer to the IRC engine; saves having to access it through the runtime constantly. Owns this class, so will always exist as long as this factory does.
Definition at line 58 of file IrcFactory.h.
Referenced by CreateIrcChannel(), CreateIrcConnection(), CreateIrcNetwork(), CreateIrcUser(), and DeleteIrcObject().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.