.TH "IrcPool.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IrcPool.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <mutex>\fP
.br
\fC#include <stack>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <api/Log\&.h>\fP
.br
\fC#include 'IrcChannel\&.h'\fP
.br
\fC#include 'IrcConnection\&.h'\fP
.br
\fC#include 'IrcNetwork\&.h'\fP
.br
\fC#include 'IrcUser\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObjectPool< T >\fP"
.br
.ti -1c
.RI "class \fBIrcPool\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIRCPOOL_GET_DECL\fP"
.br
.ti -1c
.RI "#define \fBIRCPOOL_GET_ARGS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IRCPOOL_GET_ARGS"

.PP
Definition at line 60 of file IrcPool\&.h\&.
.PP
Referenced by IrcFactory::CreateIrcChannel(), IrcFactory::CreateIrcConnection(), IrcFactory::CreateIrcNetwork(), and IrcFactory::CreateIrcUser()\&.
.SS "#define IRCPOOL_GET_DECL"

.PP
Definition at line 59 of file IrcPool\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
