IrcPool
NAME
IrcPool -
SYNOPSIS
#include <IrcPool.h>
Public Member Functions
~IrcPool ()
ObjectPool< IrcChannel > *const IrcChannels ()
ObjectPool< IrcConnection > *const IrcConnections ()
ObjectPool< IrcNetwork > *const IrcNetworks ()
ObjectPool< IrcUser > *const IrcUsers ()
std::shared_ptr< IrcChannel > GetChannel (const uint32_t connection_id, const char *channel_name)
std::shared_ptr< IrcConnection > GetConnection (const uint32_t connection_id)
std::shared_ptr< IrcNetwork > GetNetwork (const char *network_name)
std::shared_ptr< IrcUser > GetUser (const uint32_t connection_id, const char *channel_name, const char *user_name)
~IrcPool ()
ObjectPool< IrcChannel > * IrcChannels ()
ObjectPool< IrcConnection > * IrcConnections ()
ObjectPool< IrcNetwork > * IrcNetworks ()
ObjectPool< IrcUser > * IrcUsers ()
Private Member Functions
NO_CLASS_ASSIGNMENT (IrcPool)
NO_CLASS_COPY (IrcPool)
IrcPool ()
NO_CLASS_ASSIGNMENT (IrcPool)
NO_CLASS_COPY (IrcPool)
IrcPool ()
Private Attributes
ObjectPool< IrcUser > _users
ObjectPool< IrcChannel > _channels
ObjectPool< IrcConnection > _connections
ObjectPool< IrcNetwork > _networks
Friends
class IrcEngine
Detailed Description
Definition at line 445 of file IrcPool.h.
Constructor & Destructor Documentation
IrcPool::IrcPool () [private]
Definition at line 16 of file IrcPool.cc.
{
}
IrcPool::~IrcPool ()
Definition at line 22 of file IrcPool.cc.
{
}
IrcPool::IrcPool () [private]
IrcPool::~IrcPool ()
Member Function Documentation
std::shared_ptr< IrcChannel > IrcPool::GetChannel (const uint32_tconnection_id, const char *channel_name)
Definition at line 29 of file IrcPool.cc.
References _channels, and ObjectPool< T >::Allocated().
Referenced by IrcConnection::DeleteChannel(), and IrcConnection::GetChannel().
{
        if ( connection_id == 0 )
                return nullptr;
        if ( channel_name == nullptr )
                return nullptr;
        for ( auto c : _channels.Allocated() )
        {
                if ( c->Name().compare(channel_name) == 0 )
                {
                        if ( c->Owner()->Id() == connection_id )
                        {
                                return c;
                        }
                }
        }
        return nullptr;
}
std::shared_ptr< IrcConnection > IrcPool::GetConnection (const uint32_tconnection_id)
Definition at line 56 of file IrcPool.cc.
References _connections, and ObjectPool< T >::Allocated().
Referenced by IrcConnection::AddChannel(), and IrcConnection::EstablishConnection().
{
        if ( connection_id == 0 )
                return nullptr;
        for ( auto c : _connections.Allocated() )
        {
                if ( c->Id() == connection_id )
                {
                        return c;
                }
        }
        return nullptr;
}
std::shared_ptr< IrcNetwork > IrcPool::GetNetwork (const char *network_name)
Definition at line 77 of file IrcPool.cc.
References _networks, and ObjectPool< T >::Allocated().
{
        if ( name == nullptr )
                return nullptr;
        for ( auto n : _networks.Allocated() )
        {
                if ( n->Name().compare(name) == 0 )
                {
                        return n;
                }
        }
        return nullptr;
}
std::shared_ptr< IrcUser > IrcPool::GetUser (const uint32_tconnection_id, const char *channel_name, const char *user_name)
Definition at line 98 of file IrcPool.cc.
References _users, and ObjectPool< T >::Allocated().
Referenced by IrcChannel::AddNamesUser(), and IrcChannel::GetUser().
{
        if ( connection_id == 0 )
                return nullptr;
        if ( channel_name == nullptr )
                return nullptr;
        if ( nickname == nullptr )
                return nullptr;
        for ( auto u : _users.Allocated() )
        {
                if ( u->Nickname().compare(nickname) == 0 )
                {
                        if ( u->Owner()->Name().compare(channel_name) == 0 )
                        {
                                if ( u->Owner()->Owner()->Id() == connection_id )
                                {
                                        return u;
                                }
                        }
                }
        }
        return nullptr;
}
ObjectPool<IrcChannel>* IrcPool::IrcChannels () [inline]
Definition at line 460 of file bak/IrcPool.h.
References _channels.
        { return &_channels; }
ObjectPool<IrcChannel>* const IrcPool::IrcChannels () [inline]
Definition at line 467 of file IrcPool.h.
References _channels.
Referenced by IrcFactory::CreateIrcChannel(), IrcConnection::DeleteChannel(), IrcFactory::DeleteIrcObject(), IrcConnection::EraseChannelList(), and IrcParser::HandleQuit().
        {
                return &_channels;
        }
ObjectPool<IrcConnection>* IrcPool::IrcConnections () [inline]
Definition at line 462 of file bak/IrcPool.h.
References _connections.
        { return &_connections; }
ObjectPool<IrcConnection>* const IrcPool::IrcConnections () [inline]
Definition at line 473 of file IrcPool.h.
References _connections.
Referenced by IrcFactory::CreateIrcConnection(), IrcFactory::DeleteIrcObject(), and IrcParser::RunParser().
        {
                return &_connections;
        }
ObjectPool<IrcNetwork>* IrcPool::IrcNetworks () [inline]
Definition at line 464 of file bak/IrcPool.h.
References _networks.
        { return &_networks; }
ObjectPool<IrcNetwork>* const IrcPool::IrcNetworks () [inline]
Definition at line 479 of file IrcPool.h.
References _networks.
Referenced by IrcFactory::CreateIrcNetwork(), and IrcFactory::DeleteIrcObject().
        {
                return &_networks;
        }
ObjectPool<IrcUser>* IrcPool::IrcUsers () [inline]
Definition at line 466 of file bak/IrcPool.h.
References _users.
        { return &_users; }
ObjectPool<IrcUser>* const IrcPool::IrcUsers () [inline]
Definition at line 485 of file IrcPool.h.
References _users.
Referenced by IrcFactory::CreateIrcUser(), IrcFactory::DeleteIrcObject(), IrcChannel::DeleteUser(), and IrcChannel::EraseNameslist().
        {
                return &_users;
        }
IrcPool::NO_CLASS_ASSIGNMENT (IrcPool) [private]
IrcPool::NO_CLASS_ASSIGNMENT (IrcPool) [private]
IrcPool::NO_CLASS_COPY (IrcPool) [private]
IrcPool::NO_CLASS_COPY (IrcPool) [private]
Friends And Related Function Documentation
IrcEngine [friend]
we are created on the stack in IrcEngine::Pools()
we are created on the stack in IrcEngine::Pool()
Definition at line 448 of file IrcPool.h.
Member Data Documentation
ObjectPool< IrcChannel > IrcPool::_channels [private]
Definition at line 458 of file IrcPool.h.
Referenced by GetChannel(), and IrcChannels().
ObjectPool< IrcConnection > IrcPool::_connections [private]
Definition at line 459 of file IrcPool.h.
Referenced by GetConnection(), and IrcConnections().
ObjectPool< IrcNetwork > IrcPool::_networks [private]
Definition at line 460 of file IrcPool.h.
Referenced by GetNetwork(), and IrcNetworks().
ObjectPool< IrcUser > IrcPool::_users [private]
Definition at line 457 of file IrcPool.h.
Referenced by GetUser(), and IrcUsers().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.