.TH "IrcParser.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IrcParser.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <api/Runtime\&.h>\fP
.br
\fC#include 'IrcObject\&.h'\fP
.br
\fC#include 'IrcListener\&.h'\fP
.br
\fC#include 'irc_structs\&.h'\fP
.br
\fC#include 'irc_status\&.h'\fP
.br
\fC#include 'nethelper\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIrcParser\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
