Log
NAME
Log -
SYNOPSIS
#include <Log.h>
Public Member Functions
void Append (const CHARSTRINGTYPE &append_string)
void Close ()
void Flush ()
CHARSTREAMTYPE & LogWithLevel (ELogLevel log_level, const char *file=nullptr, const char *function=nullptr, const uint32_t line=0)
ELogLevel LogLevel ()
bool Open (char *filename)
void SetLogLevel (ELogLevel loglevel)
Private Member Functions
NO_CLASS_ASSIGNMENT (Log)
NO_CLASS_COPY (Log)
Log ()
~Log ()
Private Attributes
CHARSTREAMTYPE _next_log
CHARSTREAMTYPE _null_log
FILE * _file
ELogLevel _log_level
Friends
class Runtime
Detailed Description
Todo
consider using a ChainOfResponsibility style for this; will enable us to have a single LOG() line of code, with all errors always being output to cerr, but only certain things going to a physical file. The complications will be multi-line and immediate or delayed flush...
Definition at line 42 of file Log.h.
Constructor & Destructor Documentation
Log::Log () [private]
Definition at line 33 of file Log.cc.
References _log_level, and Warn.
{
         // operations append to the stream, and don't replace it
         //_next_log.setstate(std::ios_base::app);
         // logging at debug level by default
        _log_level = ELogLevel::Warn;
}
Log::~Log () [private]
Definition at line 43 of file Log.cc.
References _file, and Close().
{
        // if it hasn't already been closed, do it
        if ( _file != nullptr )
                Close();
}
Member Function Documentation
void Log::Append (const CHARSTRINGTYPE &append_string)
Used for inserting data when desiring a custom layout going to the log file. This bypasses any LogLevel, file/line info, and accesses the stream directly.
It's usage should be limited to formatting within the file, such as printing out a list of memory addresses with text - having a file + line for each at the start would be detrimental to legibility.
Use LogWithLevel(...) to get a similar result, and should be preferred where possible.
Parameters:
append_string The string to append to the stream
Definition at line 53 of file Log.cc.
References _next_log, Flush(), and STREAM_FLUSH_THRESHOLD.
Referenced by Configuration::Dump().
{
        _next_log << append_string;
        if ( _next_log.gcount() > STREAM_FLUSH_THRESHOLD )
                Flush();
}
void Log::Close ()
Closes the file previously opened by Open(), if any. Will Flush() before the file is closed, with a notification suffix line.
Will cause _file to be a nullptr after execution.
Definition at line 66 of file Log.cc.
References _file, Flush(), Force, and LogWithLevel().
Referenced by main(), and ~Log().
{
        if ( _file != nullptr )
        {
                // don't print file/line info, call direct
                LogWithLevel(ELogLevel::Force) << "*** Log file closed ***\n";
                Flush();
                fclose(_file);
                _file = nullptr;
        }
}
void Log::Flush ()
Forces the current contents of the logging stream to be written to file, if it's open.
If the file is not open, the stream is reset, just like if there was data to write.
Todo
temp; implement with chain of responsibility instead
Definition at line 82 of file Log.cc.
References _file, _next_log, fg_red(), and RESET_STREAM.
Referenced by app_exec(), app_stop(), Append(), Close(), and LogWithLevel().
{
        if ( _file == nullptr )
        {
                // don't keep the data
                RESET_STREAM(_next_log);
                return;
        }
        CHARSTRINGTYPE writing = _next_log.str();
        size_t written;
        int32_t flush_res;
        if ( writing.empty() )
                return;
        written = fwrite(writing.c_str(), sizeof(CHARTYPE), writing.length(), _file);
        if ( (flush_res = fflush(_file)) != 0 )
        {
                char errmsg[256];
                strerror_s(errmsg, sizeof(errmsg), ferror(_file));
                std::cerr << fg_red << "fflush failed; " << errmsg << "\n";
        }
        // also output to console
        std::cout << writing.c_str();
        RESET_STREAM(_next_log);
}
ELogLevel Log::LogLevel () [inline]
Retrieves the logging level currently set.
Returns:
The logging level, as an ELogLevel, currently set
Definition at line 164 of file Log.h.
        {
                return _log_level;
        }
CHARSTREAMTYPE & Log::LogWithLevel (ELogLevellog_level, const char *file = nullptr, const char *function = nullptr, const uint32_tline = 0)
Writes to the logging stream, preparing for the input from a runtime file. Returns the actual stream, so game code can perform logging in a single, non-descriptive line:
LOG(ELogLevel::Warn) << "This operation should have succeeded: ") << info_detail;
Newlines are not automatically added (since the caller has the stream on return), so must be provided.
If the logging level would not write the supplied data, it is redirected to a unused stream.
While all other parameters are optional, if you supply a filename, then the function + line are mandatory to be supplied. This is why, amongst clarity, the LOG() macro should be used for all output, unless you need fine grained control.
The file and function parameters are always passed in as ANSI-style strings due to the way they're provided by the compiler. They are converted, if need be, at runtime.
Parameters:
log_level The criticality level at which the incoming entry is deemed
file Optional pointer to the filename this log entry will contain
function Optional pointer to the function this log entry will contain
line Optional line number of the filename this log entry will contain
Returns:
A reference to the logging stream
Todo
provide a utility function for time acquisition, this gets so nasty inline
Definition at line 118 of file Log.cc.
References _log_level, _next_log, _null_log, Debug, Error, Flush(), Force, Info, PATH_CHAR, STREAM_FLUSH_THRESHOLD, and Warn.
Referenced by Close(), and Open().
{
        if ( log_level != ELogLevel::Force && log_level > _log_level )
        {
                /* ugly, ugly, nasty hack. Returns another stringstream that is
                 * used temporarily, and cleared at every opportunity. */
                _null_log.clear();
                return _null_log;
        }
        // force log flushing if too much data is buffered
        if ( _next_log.gcount() > STREAM_FLUSH_THRESHOLD )
                Flush();
        if ( file != nullptr )
        {
                time_t cur_time = time(NULL);
                tm tms;
#if _WIN32
                localtime_s(&tms, &cur_time);
#else
                localtime_r(&cur_time, &tms);
#endif
                const char* p;
                char cur_datetime[32];
                
                // requires C++11 (always multibyte)
                // ISO 8601 : %F %T
                std::strftime(cur_datetime, sizeof(cur_datetime), "%F %T", &tms);
                _next_log << cur_datetime << "\t";
                switch ( log_level )
                {
                case ELogLevel::Debug: _next_log << "[DEBUG] "; break;
                case ELogLevel::Error: _next_log << "[ERROR] "; break;
                case ELogLevel::Warn: _next_log << "[WARNING] "; break;
                case ELogLevel::Info: _next_log << "[INFO] "; break;
                case ELogLevel::Force: _next_log << "[FORCED] "; break;
                default:
                        // no custom text by default
                        break;
                }
                // we don't want the full path that some compilers set
                if ( (p = strrchr(file, PATH_CHAR)) != nullptr )
                        file = (p + 1);
                _next_log << function << " (" << file << ":" << line << "): ";
        }
        return _next_log;
}
Log::NO_CLASS_ASSIGNMENT (Log) [private]
Log::NO_CLASS_COPY (Log) [private]
bool Log::Open (char *filename)
Opens the file name specified for writing, erasing any prior data in the log file. This is opened in such a way that other processes may not write anything to the file, but are free to read it.
This is useful for checking for an event at runtime, when we don't want to have to close the application to check, while still stopping another process from being able to wipe our data out.
Parameters:
filename The name of the file to open
Returns:
true if the file is opened with a restricted share mode
false if the file could not be opened with the desired share mode
Definition at line 181 of file Log.cc.
References _file, fg_red(), Force, and LogWithLevel().
Referenced by app_init().
{
        /* allow others to open the log file at runtime, but not for writing.
         * This is implementation and operating system dependant as to what
         * action is taken, if errors are forwarded (e.g. cpp streams setting
         * errno, and win32 being able to use GetLastError()), and what errors
         * we can actually retrieve (beyond just knowing an error occurred).
         * Until there is a standard for doing this, back to the nice C-style
         * methods here */
#if defined(_WIN32)
        if ( (_file = _fsopen(filename, "wb", _SH_DENYWR)) == nullptr )
        {
                std::cerr << fg_red << "Failed to open log file:\n\n" << filename << "\n\nerrno = " << errno << "\n";
                return false;
        }
#else
        int fd;
        if ( (fd = open(LOG_NAME, O_WRONLY | O_CREAT, O_NOATIME | S_IRWXU | S_IRGRP | S_IROTH)) == -1 )
        {
                std::cerr << fg_red << "Could not open the log file " << LOG_NAME << "; errno " << errno << "\n";
                return false;
        }
        if ( (_file = fdopen(fd, "w")) == nullptr )
        {
                std::cerr << fg_red << "fdopen failed on the file descriptor for " << LOG_NAME << "; errno " << errno << "\n";
                return false;
        }
#endif
        // Default log message (verifies path used); don't print file/line info, call direct
        LogWithLevel(ELogLevel::Force) << "*** Log File '" << filename << "' opened ***\n";
        return true;
}
void Log::SetLogLevel (ELogLevelloglevel) [inline]
Changes what level of events will be logged, and those that will be sent to /dev/null.
Parameters:
loglevel The new log level to use
Definition at line 196 of file Log.h.
Referenced by app_init().
        {
                _log_level = loglevel;
        }
Friends And Related Function Documentation
friend class Runtime [friend]
Definition at line 45 of file Log.h.
Member Data Documentation
FILE* Log::_file [private]
we need error handling beyond that of 'an error occurred' so we need to call into the platforms APIs to retain control; hence the usage of the C-style FILE and not a std::ofstream
Definition at line 67 of file Log.h.
Referenced by Close(), Flush(), Open(), and ~Log().
ELogLevel Log::_log_level [private]
The active logging level; log requests with a lower rating will not log those with higher levels unless set here.
Definition at line 71 of file Log.h.
Referenced by Log(), and LogWithLevel().
CHARSTREAMTYPE Log::_next_log [private]
This holds all of the data written into the stream inbetween calls to the flush function, which actually writes out to file
Definition at line 57 of file Log.h.
Referenced by Append(), Flush(), and LogWithLevel().
CHARSTREAMTYPE Log::_null_log [private]
A stream to hold logging events that don't reach the required level to be put to the normal stream. Nasty hack, as all the data is still written to the stream, where it then gets wiped straight away.
Definition at line 62 of file Log.h.
Referenced by LogWithLevel().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.