.TH "Log.cc" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include 'Terminal\&.h'\fP
.br
\fC#include 'Log\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTREAM_FLUSH_THRESHOLD\fP   1024"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP
\fBCopyright:\fP
.RS 4
James Warren, 2013-2014 
.RE
.PP
\fBLicense:\fP
.RS 4
Zlib (see license\&.txt or http://opensource.org/licenses/Zlib) 
.RE
.PP

.PP
Definition in file \fBLog\&.cc\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define STREAM_FLUSH_THRESHOLD   1024"
number of bytes the stream can contain before it will be flushed 
.PP
\fBBug\fP
.RS 4
threshold appears to make no difference - see if fixable 
.RE
.PP

.PP
Definition at line 28 of file Log\&.cc\&.
.PP
Referenced by Log::Append(), and Log::LogWithLevel()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
