.TH "Log.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log.h \- 
.PP
\fBLog\fP file writing for the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'char_helper\&.h'\fP
.br
\fC#include 'Runtime\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLog\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG\fP(LogLevel)   runtime\&.Logger()->LogWithLevel(LogLevel, __FILE__, \fB__func__\fP, __LINE__)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBELogLevel\fP { \fBELogLevel::None\fP = 0, \fBELogLevel::Error\fP, \fBELogLevel::Warn\fP, \fBELogLevel::Info\fP, \fBELogLevel::Debug\fP, \fBELogLevel::Force\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLog\fP file writing for the application\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBLog\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG(LogLevel)   runtime\&.Logger()->LogWithLevel(LogLevel, __FILE__, \fB__func__\fP, __LINE__)"

.PP
Definition at line 207 of file Log\&.h\&.
.PP
Referenced by IrcObject::AddReference(), IrcConnection::AddToRecvQueue(), app_exec(), app_init(), IrcFactory::DeleteIrcObject(), Configuration::Dump(), ObjectPool< IrcUser >::Free(), ObjectPool< IrcUser >::Get(), ObjectPool< IrcUser >::GetObject(), host_to_ipv4(), ipv4_to_host(), Configuration::LoadUI(), main(), net_startup(), ObjectPool< IrcUser >::ReallyFreeObject(), IrcObject::RemoveReference(), IrcConnection::SendBypass(), Runtime::ThreadStopping(), and Runtime::WaitThenKillThread()\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBELogLevel\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
no logging at all 
.TP
\fB\fIError \fP\fP
logging errors 
.TP
\fB\fIWarn \fP\fP
logging warnings + above 
.TP
\fB\fIInfo \fP\fP
logging info + above 
.TP
\fB\fIDebug \fP\fP
logging debug (all) 
.TP
\fB\fIForce \fP\fP
logging forced; statement WILL be logged 
.PP
Definition at line 21 of file Log\&.h\&.
.PP
.nf
22 {
23         None = 0,       
24         Error,          
25         Warn,           
26         Info,           
27         Debug,          
28         Force           
29 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
