.TH "ModuleInformation" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModuleInformation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utils_win\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wchar_t \fBname\fP [512]"
.br
.ti -1c
.RI "\fBfile_version_info\fP \fBfvi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a module (DLL) 
.PP
Definition at line 37 of file utils_win\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfile_version_info\fP ModuleInformation::fvi"

.PP
Definition at line 40 of file utils_win\&.h\&.
.PP
Referenced by get_loaded_modules()\&.
.SS "wchar_t ModuleInformation::name[512]"
Module name (full path) 
.PP
Definition at line 39 of file utils_win\&.h\&.
.PP
Referenced by get_loaded_modules()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
