.TH "ModulesLoadDialog.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModulesLoadDialog.h \- 
.PP
Qt5GUI 'Load Module' dialog\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <QtWidgets/QDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModulesLoadDialog\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Qt5GUI 'Load Module' dialog\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBModulesLoadDialog\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
