ObjectPool< T >
NAME
ObjectPool< T > -
SYNOPSIS
#include <IrcPool.h>
Public Member Functions
ObjectPool ()
~ObjectPool ()
std::vector< std::shared_ptr
< T > > & Allocated ()"
bool FreeObject (std::shared_ptr< T > object)
std::shared_ptr< T > GetObject (IRCPOOL_GET_DECL)
bool GrandAlloc (uint32_t num_objects)
void TotalErase ()
ObjectPool ()
~ObjectPool ()
bool Free (T *object)
T * Get (IRCPOOL_GET_DECL)
bool GrandAlloc (uint32_t num_objects)
void TotalErase ()
Private Member Functions
NO_CLASS_ASSIGNMENT (ObjectPool)
NO_CLASS_COPY (ObjectPool)
void OutputMemoryInfo (const char *out_filename)
void ReallyFreeObject (std::shared_ptr< T > object)
NO_CLASS_ASSIGNMENT (ObjectPool)
NO_CLASS_COPY (ObjectPool)
void OutputMemoryInfo (char *file_name, bool destruction)
void ReportReferencedObject (T *object)
Private Attributes
void * _pool
std::vector< std::shared_ptr< T > > _objects
std::vector< std::shared_ptr< T > > _delete_later
std::stack< T > _used_list
std::stack< T > _free_list
uint32_t _get_count
uint32_t _max_alive
std::mutex _mutex
std::stack< T * > _used_list
std::stack< T * > _free_list
Detailed Description
template<class T>class ObjectPool< T >
A simple memory pool
Definition at line 81 of file IrcPool.h.
Constructor & Destructor Documentation
template<class T> ObjectPool< T >::ObjectPool () [inline]
Definition at line 197 of file IrcPool.h.
                     : _pool(nullptr), _get_count(0)
        {
        }
template<class T> ObjectPool< T >::~ObjectPool () [inline]
Definition at line 200 of file IrcPool.h.
        {
                /* Mandatory output; allows us to see the amount of allocations
                 * per object, useful for future optimization - such as a more
                 * suitable amount for GrandAlloc */
                OutputMemoryInfo(BUILD_STRING(typeid(T).name(), ".log").c_str());
                // ensure we're not leaving anything allocated
                TotalErase();
        }
template<class T> ObjectPool< T >::ObjectPool () [inline]
Definition at line 199 of file bak/IrcPool.h.
                     : _pool(nullptr), _get_count(0)
        {
        }
template<class T> ObjectPool< T >::~ObjectPool () [inline]
Definition at line 202 of file bak/IrcPool.h.
        {
                /* Mandatory output; allows us to see the amount of allocations
                 * per object, useful for future optimization - such as a more
                 * suitable amount for GrandAlloc */
                OutputMemoryInfo("object_pool.log", true);
                // ensure we're not leaving anything allocated
                TotalErase();
        }
Member Function Documentation
template<class T> std::vector<std::shared_ptr<T> >& ObjectPool< T >::Allocated () [inline]
Returns the list of allocated objects currently live
Definition at line 215 of file IrcPool.h.
Referenced by IrcPool::GetChannel(), IrcPool::GetConnection(), IrcPool::GetNetwork(), IrcPool::GetUser(), IrcParser::HandleQuit(), and IrcParser::RunParser().
        {
                return _objects;
        }
template<class T> bool ObjectPool< T >::Free (T *object) [inline]
Returns the supplied object to the pool, and calls the destructor.
Definition at line 217 of file bak/IrcPool.h.
Referenced by IrcFactory::DeleteIrcObject().
        {
                // validate it came from our pool?
                _mutex.lock();
                /* Destructor is called by ourselves; this means that we must do
                 * all checks before that point, which in this case, is reporting
                 * if the object still has outstanding references.
                 * The objects notify the Engine of their creation and
                 * deletion in its constructor/destructor respectively. As such,
                 * when freeing the object in our code, this should be the only
                 * remaining reference, since we can't check the reference count
                 * AFTER we've deleted it. If it's still got more than 1, then
                 * somethings wrong. */
                if ( object->RefCount() != 0 )
                {
                        ReportReferencedObject(object);
                }
                /* in order to call the destructor here, we must have a pointer
                 * to the object type (is deemed non-trivial otherwise).
                 * We must call the destructor manually, as letting the Object
                 * Dereference call do it will NOT invoke any derived destructors
                 * at the same time. */
                T* obj = object;
                obj->~T();
                LOG(LL_Debug) << "Object " << object << " given back to the pool\n";
                // add the address back to the free pool
                _free_list.push(static_cast<T*>(object));
                // pop it off the used list
                _used_list.pop();
#if defined(USING_MEMORY_DEBUGGING)
                // auto fail!
                for ( std::vector<pool_object_meminfo>::iterator info = _infovect.begin();
                        info != _infovect.end();
                        info++ )
                {
                        if ( (info)->object == (void*)object )
                        {
                                _infovect.erase(info);
                                break;
                        }
                }
#endif
                _mutex.unlock();
                return true;
        }
template<class T> bool ObjectPool< T >::FreeObject (std::shared_ptr< T >object) [inline]
Returns the supplied object to the pool, and calls the destructor.
Definition at line 225 of file IrcPool.h.
Referenced by IrcConnection::DeleteChannel(), IrcChannel::DeleteUser(), IrcConnection::EraseChannelList(), and IrcChannel::EraseNameslist().
        {
                // validate it came from our pool?
                _mutex.lock();
                /* If the object is still referenced by more than just this
                 * current function (and our _object list), we cannot add it
                 * back to the free list, as it could be reallocated and screw
                 * things up.
                 * At the same time, we can't keep checking references in caller
                 * code or waiting for objects to die, so we add it to the
                 * 'delete-later' list, so it can be reclaimed later.
                 */
                if ( object.use_count() > 2 )
                {
                        // still referenced; reattempt delete later
                        _delete_later.push_back(object);
                        return true;
                }
                
                /* release the actual resources it's using and provide the
                 * pointers back to the lists */
                ReallyFreeObject(object);
                _mutex.unlock();
                // IrcObject destructor called on this functions return!!
                return true;
        }
template<class T> T* ObjectPool< T >::Get (IRCPOOL_GET_DECL) [inline]
Returns the next available pointer
Todo
implement GrandAlloc dynamic expansion
Definition at line 277 of file bak/IrcPool.h.
Referenced by IrcFactory::CreateIrcChannel(), IrcFactory::CreateIrcConnection(), and IrcFactory::CreateIrcUser().
        {
                _mutex.lock();
                if ( _free_list.empty() )
                {
                        /* argh.. we've breached our allocation limit - we need to do a
                         * fresh set to bring us up - the policy is 50% of the current
                         * max (i.e. GrandAlloc(10) means if we breach, an extra 5
                         * elements will be added - a second breach adds 8, and so on) */
                        //uint32_t additional = _used_list.size() / 2;
                }
                
                T* object = _free_list.top();
                // remove one of the free elements from the stack
                _free_list.pop();
#if defined(USING_MEMORY_DEBUGGING)
                pool_object_meminfo info;
# if IS_DEBUG_BUILD && IS_VISUAL_STUDIO
                // we don't want the full path information that VS sets in debug mode
                file = (strrchr(file, PATH_CHAR) + 1);
# endif
                info.object = object;
                info.line = line;
                strlcpy(info.file, file, sizeof(info.file));
                strlcpy(info.function, function, sizeof(info.function));
                _infovect.push_back(info);
#endif
#if 0 // Code Removed: ObjectPool class performs placement new to support multiple parameters
                /* construct the object - no arguments! Achievable with some variadic
                 * templates, but good luck following and maintaining the code... */
                //new (object) T;
#endif
                // push our created object onto the used elements
                _used_list.push(object);
                // update stats
                _get_count++;
                if ( _used_list.size() > _max_alive )
                        _max_alive = _used_list.size();
                LOG(LL_Debug) << "Object " << object << " acquired from the pool\n";
                _mutex.unlock();
                return object;
        }
template<class T> std::shared_ptr<T> ObjectPool< T >::GetObject (IRCPOOL_GET_DECL) [inline]
Returns the next available pointer
Todo
implement GrandAlloc dynamic expansion
Definition at line 263 of file IrcPool.h.
Referenced by IrcFactory::CreateIrcChannel(), IrcFactory::CreateIrcConnection(), IrcFactory::CreateIrcNetwork(), and IrcFactory::CreateIrcUser().
        {
                _mutex.lock();
                /* seems an opportune time to check the delete_later
                 * list and actually delete the old objects */
                {
                }
                if ( _free_list.empty() )
                {
                        /* argh.. we've breached our allocation limit - we need to do a
                         * fresh set to bring us up - the policy is 50% of the current
                         * max (i.e. GrandAlloc(10) means if we breach, an extra 5
                         * elements will be added - a second breach adds 8, and so on) */
                        //uint32_t additional = _used_list.size() / 2;
                }
                
                T* object = _free_list.top();
                // remove one of the free elements from the stack
                _free_list.pop();
#if 0 // Code Removed: no manual reference tracking done anymore, using std::shared_ptr
#if defined(USING_MEMORY_DEBUGGING)
                pool_object_meminfo info;
# if IS_DEBUG_BUILD && IS_VISUAL_STUDIO
                // we don't want the full path information that VS sets in debug mode
                file = (strrchr(file, PATH_CHAR) + 1);
# endif
                info.object = object;
                info.line = line;
                strlcpy(info.file, file, sizeof(info.file));
                strlcpy(info.function, function, sizeof(info.function));
                _infovect.push_back(info);
#endif
#endif
                // push our created object onto the used elements
                _used_list.push(object);
                // update stats
                _get_count++;
                if ( _used_list.size() > _max_alive )
                        _max_alive = _used_list.size();
                LOG(ELogLevel::Debug) << "Object " << object << " acquired from the pool\n";
                std::shared_ptr<T> ptr;
                /* assign the object pointer as shared; no constructors yet! The
                 * caller, factory, will utilize placement new for this task */
                ptr.reset(object);
                /* store this pointer until requested to free it; by default,
                 * nothing retains a pointer to one of these objects, so it will
                 * hit a reference count of 0 upon scope exit where created */
                _objects.push_back(ptr);
                _mutex.unlock();
                return ptr;
        }
template<class T> bool ObjectPool< T >::GrandAlloc (uint32_tnum_objects) [inline]
Allocates the requested number of objects.
The goal is not to call this at all, while the game is active; if the requested amount exceeds the current available, a large memory allocation will be performed, potentially causing contention.
Designed to be called once, based on the game specs and options, until the game finishes, where all objects are released.
If USING_MEMORY_DEBUGGING, space will be reserved at the end of each object (essentially no-mans land), which will store the details of the caller of Get()
Parameters:
num_objects The number of Objects of type T to allocate
Returns:
Returns true if all of the objects were allocated; if num_objects is 0, or allocation fails, the function returns false
Todo
throw nullptr or runtime_error on malloc failure?
Definition at line 351 of file IrcPool.h.
        {
                T* offset;
                uint32_t to_alloc = sizeof(T) * num_objects;
                if ( num_objects == 0 )
                        return false;
                _mutex.lock();
#if defined(USING_MEMORY_DEBUGGING)
                // since we know how many objects there will be
                _infovect.reserve(num_objects);
#endif
                // one 'huge' heap allocation
                _pool = MALLOC(to_alloc);
                if ( _pool == nullptr )
                {
                        _mutex.unlock();
                        return false;
                }
                offset = static_cast<T*>(_pool);
                for ( uint32_t i = 0; i < num_objects; i++ )
                {
                        // push each object offset into the free list
                        _free_list.push(offset);
                        offset++;
                }
                _mutex.unlock();
                return true;
        }
template<class T> bool ObjectPool< T >::GrandAlloc (uint32_tnum_objects) [inline]
Allocates the requested number of objects.
The goal is not to call this at all, while the game is active; if the requested amount exceeds the current available, a large memory allocation will be performed, potentially causing contention.
Designed to be called once, based on the game specs and options, until the game finishes, where all objects are released.
If USING_MEMORY_DEBUGGING, space will be reserved at the end of each object (essentially no-mans land), which will store the details of the caller of Get()
Parameters:
num_objects The number of Objects of type T to allocate
Returns:
Returns true if all of the objects were allocated; if num_objects is 0, or allocation fails, the function returns false
Todo
throw nullptr or runtime_error on malloc failure?
Definition at line 355 of file bak/IrcPool.h.
        {
                T* offset;
                uint32_t to_alloc = sizeof(T) * num_objects;
                if ( num_objects == 0 )
                        return false;
                _mutex.lock();
#if defined(USING_MEMORY_DEBUGGING)
                // since we know how many objects there will be
                _infovect.reserve(num_objects);
#endif
                // one 'huge' heap allocation
                _pool = MALLOC(to_alloc);
                if ( _pool == nullptr )
                {
                        _mutex.unlock();
                        return false;
                }
                offset = static_cast<T*>(_pool);
                for ( uint32_t i = 0; i < num_objects; i++ )
                {
                        // push each object offset into the free list
                        _free_list.push(offset);
                        offset++;
                }
                _mutex.unlock();
                return true;
        }
template<class T> ObjectPool< T >::NO_CLASS_ASSIGNMENT (ObjectPool< T >) [private]
template<class T> ObjectPool< T >::NO_CLASS_ASSIGNMENT (ObjectPool< T >) [private]
template<class T> ObjectPool< T >::NO_CLASS_COPY (ObjectPool< T >) [private]
template<class T> ObjectPool< T >::NO_CLASS_COPY (ObjectPool< T >) [private]
template<class T> void ObjectPool< T >::OutputMemoryInfo (char *file_name, booldestruction) [inline], [private]
Same style as the OutputMemoryInfo() from Allocator, where this was adapted from originally.
Definition at line 112 of file bak/IrcPool.h.
        {
                FILE* leak_file;
                bool close_file = true;
                if ( (leak_file = _fsopen(file_name, "wb", _SH_DENYWR)) == nullptr )
                {
                        leak_file = stdout;
                        close_file = false;
                }
                
                if ( destruction )
                {
                        fprintf(leak_file, "\n[Pool Destruction]\n");
                }
                _mutex.lock();
                fprintf(leak_file,
                        "# Details\n"
                        "Object Type...: %s\n"
                        "Object Size...: %lu\n"
                        "\n"
                        "# Code Stats\n"
                        "Created.......: %lu\n"
                        "Requested.....: %lu\n"
                        "Released......: %lu\n"
                        "Unreleased....: %lu\n"
                        "\n"
                        "##################\n",
                        typeid(T).name(),
                        sizeof(T),
                        // free_list size is valid only if there's no leaks!
                        (_used_list.size() + _free_list.size()),
                        _get_count,
                        (_get_count - _used_list.size()),
                        _used_list.size()
                );
#if defined(USING_MEMORY_DEBUGGING)
                for ( auto meminfo : _infovect )
                {
                        fprintf(leak_file, "%s object at " PRINT_POINTER " (%s @ %s:%u, %u bytes)\n",
                                destruction ? "Unfreed" : "Allocated",
                                (uintptr_t)meminfo.object,
                                meminfo.function,
                                meminfo.file,
                                meminfo.line,
                                sizeof(T));
                }
#endif // USING_MEMORY_DEBUGGING
                _mutex.unlock();
                if ( close_file )
                        fclose(leak_file);
        }
template<class T> void ObjectPool< T >::OutputMemoryInfo (const char *out_filename) [inline], [private]
Same style as the OutputMemoryInfo() from Allocator, where this was adapted from originally.
Definition at line 116 of file IrcPool.h.
        {
                        FILE* out_file;
                        bool close_file = true;
                        if (( out_file = _fsopen(out_filename, "wb", _SH_DENYWR)) == nullptr )
                        {
                                out_file = stdout;
                                close_file = false;
                        }
                        _mutex.lock();
                        fprintf(out_file,
                                "# Details\n"
                                "Object Type...: %s\n"
                                "Object Size...: %lu\n"
                                "\n"
                                "# Code Stats\n"
                                "Created.......: %lu\n"
                                "Requested.....: %u\n"
                                "Released......: %lu\n"
                                "Unreleased....: %lu\n"
                                "Most Alive....: %u\n"
                                "\n"
                                "##################\n",
                                typeid(T).name(),
                                sizeof(T),
                                // free_list size is valid only if there's no leaks!
                                (_used_list.size() + _free_list.size()),
                                _get_count,
                                (_get_count - _used_list.size()),
                                _used_list.size(),
                                _max_alive
                                );
#if 0 // Code Removed: no manual reference tracking done anymore, using std::shared_ptr
#if defined(USING_MEMORY_DEBUGGING)
                        for ( auto meminfo : _infovect )
                        {
                                fprintf(out_file, "%s object at " PRINT_POINTER " (%s @ %s:%u, %lu bytes)\n",
                                        destruction ? "Unfreed" : "Allocated",
                                        (uintptr_t)meminfo.object,
                                        meminfo.function,
                                        meminfo.file,
                                        meminfo.line,
                                        sizeof(T));
                        }
#endif // USING_MEMORY_DEBUGGING
#endif
                _mutex.unlock();
                if ( close_file )
                {
                        fclose(out_file);
                }
        }
template<class T> void ObjectPool< T >::ReallyFreeObject (std::shared_ptr< T >object) [inline], [private]
Definition at line 180 of file IrcPool.h.
        {
                LOG(ELogLevel::Debug) << "Object " << object << " given back to the pool\n";
                // add the address back to the free pool
                _free_list.push(object);
                // pop it off the used list
                _used_list.pop();
                // and remove our reference to it
                _objects.erase(std::find(_objects.begin(), _objects.end(), object));
        }
template<class T> void ObjectPool< T >::ReportReferencedObject (T *object) [inline], [private]
Definition at line 177 of file bak/IrcPool.h.
        {
                char buffer[MAX_LEN_GENERIC];
                str_format(buffer, sizeof(buffer),
                           "Referenced Object Freed\n\n"
                           "Object:\t\t " PRINT_POINTER "\n"
                           "Type:\t\t %s\n"
                           "References:\t %lu\n\n"
                           "Further accesses to this object will cause a crash",
                        (uintptr_t)object,
                        typeid(T).name(),
                        object->RefCount()
                );
                runtime.Report(buffer, "Error");
        }
template<class T> void ObjectPool< T >::TotalErase () [inline]
Used for wiping out any existing pool items (which yes, will cause a crash if these are still referenced and valid objects); generally shouldn't be called out of the destructor, but this leaves the option open for cleanup functions.
Definition at line 400 of file IrcPool.h.
        {
                /* recursive mutex, so we can have the same thread locking
                 * multiple times without a problem */
                _mutex.lock();
                while ( !_used_list.empty() )
                {
                        FreeObject(_used_list.top());
                }
                // wait until all shared pointers are actually destroyed
                while ( !_delete_later.empty() )
                {
                        SLEEP_MILLISECONDS(100);
                }
                if ( !_objects.empty() )
                {
                        throw std::runtime_error("Objects still exist on pool deletion");
                }
                if ( _pool != nullptr )
                {
                        FREE(_pool);
                        _pool = nullptr;
                }
                _mutex.unlock();
        }
template<class T> void ObjectPool< T >::TotalErase () [inline]
Used for wiping out any existing pool items (which yes, will cause a crash if these are still referenced and valid objects); generally shouldn't be called out of the destructor, but this leaves the option open for cleanup functions.
Definition at line 403 of file bak/IrcPool.h.
        {
                /* recursive mutex, so we can have the same thread locking
                 * multiple times without a problem */
                _mutex.lock();
                while ( !_used_list.empty() )
                {
                        Free(_used_list.top());
                }
                if ( _pool != nullptr )
                {
                        FREE(_pool);
                        _pool = nullptr;
                }
#if defined(USING_MEMORY_DEBUGGING)
                _infovect.clear();
#endif
                _mutex.unlock();
        }
Member Data Documentation
template<class T> std::vector<std::shared_ptr<T> > ObjectPool< T >::_delete_later [private]
Definition at line 93 of file IrcPool.h.
template<class T> std::stack<T*> ObjectPool< T >::_free_list [private]
A stack of addresses available to use from the _pool
Definition at line 87 of file bak/IrcPool.h.
template<class T> std::stack<T> ObjectPool< T >::_free_list [private]
A stack of addresses available to use from the _pool
Definition at line 98 of file IrcPool.h.
template<class T> uint32_t ObjectPool< T >::_get_count [private]
Stats; the number of objects requested via Get() in total
Definition at line 101 of file IrcPool.h.
template<class T> uint32_t ObjectPool< T >::_max_alive [private]
Stats; the maximum number of objects requested and still used via Get() at a single point in time
Definition at line 104 of file IrcPool.h.
template<class T> std::mutex ObjectPool< T >::_mutex [private]
The lock for making modifications per pool
Definition at line 107 of file IrcPool.h.
template<class T> std::vector<std::shared_ptr<T> > ObjectPool< T >::_objects [private]
Definition at line 91 of file IrcPool.h.
template<class T> void * ObjectPool< T >::_pool [private]
The address of the allocated memory
Definition at line 88 of file IrcPool.h.
template<class T> std::stack<T*> ObjectPool< T >::_used_list [private]
A stack of addresses used from the _pool
Definition at line 85 of file bak/IrcPool.h.
template<class T> std::stack<T> ObjectPool< T >::_used_list [private]
A stack of addresses used from the _pool
Definition at line 96 of file IrcPool.h.
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.