.TH "Pool.cc" 3 "Wed Jun 18 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pool.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Pool\&.h'\fP
.br
\fC#include 'IrcUser\&.h'\fP
.br
\fC#include 'IrcChannel\&.h'\fP
.br
\fC#include 'IrcConnection\&.h'\fP
.br
\fC#include 'IrcNetwork\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP
\fBCopyright:\fP
.RS 4
James Warren, 2013-2014 
.RE
.PP
\fBLicense:\fP
.RS 4
Zlib (see license\&.txt or http://opensource.org/licenses/Zlib)
.RE
.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP
\fBCopyright:\fP
.RS 4
James Warren, 2013 
.RE
.PP
\fBLicense:\fP
.RS 4
Zlib (see license\&.txt or http://opensource.org/licenses/Zlib) 
.RE
.PP
\fBTodo\fP
.RS 4
race conditions with \fBObjectPool\fP, sort out the mutex 
.RE
.PP

.PP
Definition in file \fBPool\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
