.TH "Pool.h" 3 "Wed Jun 18 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pool.h \- 
.PP
Memory pools for the game objects\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <mutex>\fP
.br
\fC#include <stack>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <api/Log\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObjectPool< T >\fP"
.br
.ti -1c
.RI "class \fBPool\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPOOL_GET\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Memory pools for the game objects\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBPool\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define POOL_GET"

.PP
Definition at line 418 of file Pool\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
