.TH "Pool" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pool \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IrcPool\&.h>\fP
.SH "Detailed Description"
.PP 
Resides within the IRC Engine and provides access to pre-allocated memory usable for well-known/common objects\&.
.PP
Reusable for specific implementations, with updating of the relevant types\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
