qrc_sbi.cc
NAME
qrc_sbi.cc -
SYNOPSIS
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE
Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int
QT_MANGLE_NAMESPACE() qInitResources_core ()"
int QT_MANGLE_NAMESPACE() qCleanupResources_core ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Function Documentation
int QT_MANGLE_NAMESPACE() qCleanupResources_core ()
Definition at line 8292 of file qrc_sbi.cc.
References qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
{
    QT_PREPEND_NAMESPACE(qUnregisterResourceData)
       (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_core ()
Definition at line 8283 of file qrc_sbi.cc.
References qRegisterResourceData(), qt_resource_data, qt_resource_name, and qt_resource_struct.
{
    QT_PREPEND_NAMESPACE(qRegisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qInitResources_core().
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qCleanupResources_core().
Variable Documentation
const unsigned char qt_resource_data[] [static]
Definition at line 11 of file qrc_sbi.cc.
Referenced by qCleanupResources_core(), and qInitResources_core().
const unsigned char qt_resource_name[] [static]
Definition at line 7916 of file qrc_sbi.cc.
Referenced by qCleanupResources_core(), and qInitResources_core().
const unsigned char qt_resource_struct[] [static]
Definition at line 8168 of file qrc_sbi.cc.
Referenced by qCleanupResources_core(), and qInitResources_core().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.