.TH "rfc1459.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rfc1459.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <api/char_helper\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRFC1459_CASEMAPPING\fP   'rfc1459')"
.br
.ti -1c
.RI "#define \fBRFC1459_CHANNEL_LEN\fP   200"
.br
.ti -1c
.RI "#define \fBRFC1459_CHAN_TYPES\fP   '#&')"
.br
.ti -1c
.RI "#define \fBRFC1459_MODES\fP   3"
.br
.ti -1c
.RI "#define \fBRFC1459_NICK_LEN\fP   9"
.br
.ti -1c
.RI "#define \fBRFC1459_PREFIX\fP   '(ov)@+')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RFC1459_CASEMAPPING   'rfc1459')"

.PP
Definition at line 18 of file rfc1459\&.h\&.
.SS "#define RFC1459_CHAN_TYPES   '#&')"

.PP
Definition at line 20 of file rfc1459\&.h\&.
.SS "#define RFC1459_CHANNEL_LEN   200"

.PP
Definition at line 19 of file rfc1459\&.h\&.
.SS "#define RFC1459_MODES   3"

.PP
Definition at line 21 of file rfc1459\&.h\&.
.PP
Referenced by IrcParser::Handle005()\&.
.SS "#define RFC1459_NICK_LEN   9"

.PP
Definition at line 22 of file rfc1459\&.h\&.
.SS "#define RFC1459_PREFIX   '(ov)@+')"

.PP
Definition at line 23 of file rfc1459\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
