.TH "runtime_object_accessor" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
runtime_object_accessor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Runtime\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBMAX_LEN_GENERIC\fP]"
.br
.ti -1c
.RI "\fBgetter\fP \fBget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file Runtime\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBgetter\fP runtime_object_accessor::get"

.PP
Definition at line 93 of file Runtime\&.h\&.
.PP
Referenced by Runtime::GetObjectFromModule()\&.
.SS "char runtime_object_accessor::name[\fBMAX_LEN_GENERIC\fP]"

.PP
Definition at line 92 of file Runtime\&.h\&.
.PP
Referenced by Runtime::FindModule(), and Runtime::GetObjectFromModule()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
