Runtime
NAME
Runtime -
SYNOPSIS
#include <Runtime.h>
Public Member Functions
Configuration * Config () const
void DoShutdown ()
void * GetObjectFromModule (const char *module_name)
bool IsQuitting ()
Log * Logger () const
void Report (const char *text_buffer, const char *title) const
void ThreadStopping (uint32_t thread_id, const char *function)
void WaitThenKillThread (uint32_t thread_id, uint32_t timeout_ms=1000)
Static Public Member Functions
static Runtime & Instance ()
Private Member Functions
NO_CLASS_ASSIGNMENT (Runtime)
NO_CLASS_COPY (Runtime)
Runtime ()
~Runtime ()
runtime_object_accessor * FindModule (runtime_object_accessor *search)
Private Attributes
bool _quitting
std::vector< thread_info > _manual_threads
std::set
< runtime_object_accessor * > _runtime_objects"
Detailed Description
Dedicated class for storing all 'global' variables. Meyers Singleton, so no memory leaks.
Globally accessible to any file including runtime.h, but only app_init() and app_free() have the ability to create and destroy the class, and access any other internals.
The classes returned are all created on the stack as static variables in their respective functions. This has much less overhead than having them as std::unique_ptr's that are allocated on the heap, and we can access the raw pointer directly.
While this is a technical misuse of a Singleton, since there can only ever be one runtime (which we can then use to interface with the host OS and also maintains if the app is quitting, for example), it seems somewhat appropriate and can easily be replaced, the way it has been designed.
Yes, this can be implemented in other ways - but this is clear and concise, without too many of the issues commonly associated with bad singleton use.
Definition at line 121 of file Runtime.h.
Constructor & Destructor Documentation
Runtime::Runtime () [private]
Definition at line 36 of file Runtime.cc.
{
}
Runtime::~Runtime () [private]
Definition at line 42 of file Runtime.cc.
{
}
Member Function Documentation
Configuration * Runtime::Config () const
Gets the configuration.
Returns:
A pointer to the static instance within the runtime.
Definition at line 49 of file Runtime.cc.
Referenced by app_exec(), app_init(), and spawn_interface().
{
        static Configuration config;
        return &config;
}
void Runtime::DoShutdown ()
Todo
how can we force objects to quit since we have no knowledge of what modules they are? Current proposal: have them export a 'quit' function that can be called from here now, that way they're all done and clean... similar to the functionality behind the get() getter
Definition at line 74 of file Runtime.cc.
References _manual_threads, _quitting, and WaitThenKillThread().
{
        /* some, not all, threads query with the runtime if the app is quitting
         * when synchronized, so they can quit cleanly (otherwise, the only way
         * to stop the thread is to kill it). */
        _quitting = true;
        // parser thread explicity waits for _quitting to be set
        //Irc()->Parser()->TriggerSync();
        // stop any existing threads still running
        while ( !_manual_threads.empty() )
                WaitThenKillThread(_manual_threads[0].thread);
}
runtime_object_accessor * Runtime::FindModule (runtime_object_accessor *search) [private]
Definition at line 58 of file Runtime.cc.
References _runtime_objects, and runtime_object_accessor::name.
Referenced by GetObjectFromModule().
{
        for ( auto iter : _runtime_objects )
        {
                if ( strcmp((*iter).name, search->name) == 0 )
                        return iter;
        }
        
        return nullptr;
}
void * Runtime::GetObjectFromModule (const char *module_name)
Loads an interface from a module name (e.g. 'libirc' will return a pointer to the IRC interface returned within the library).
Todo
Need a proper data type so we're not blindly casting
Definition at line 98 of file Runtime.cc.
References _runtime_objects, CONSTRUCT, FindModule(), runtime_object_accessor::get, get_function_address(), MALLOC, MAX_LEN_GENERIC, mb_to_utf8(), runtime_object_accessor::name, and strlcpy().
Referenced by IrcObject::IrcObject().
{
        bool could_not_load = true;
        runtime_object_accessor search;
        runtime_object_accessor* retval;
        strlcpy(search.name, module_name, sizeof(search.name));
        
        if (( retval = FindModule(&search)) == nullptr )
        {
                // not found, try to load the module
#if _WIN32
                wchar_t w_module_name[MAX_LEN_GENERIC];
                HANDLE mod = NULL;
                
                if ( mb_to_utf8(w_module_name, module_name, _countof(w_module_name)) )
                        mod = LoadLibrary(w_module_name);
                if ( mod != NULL )
                        could_not_load = false;
#else
#endif
                // if we couldn't load it, we'll have to abort
                if ( could_not_load )
                {
                        throw std::runtime_error("Failed to load required module");
                }
                retval = (runtime_object_accessor*)MALLOC(sizeof(runtime_object_accessor));
                CONSTRUCT(retval, runtime_object_accessor);
#if _WIN32
                retval->get = (getter)get_function_address("instance", w_module_name);
#else
#endif
                if ( retval->get == nullptr )
                {
                        throw std::runtime_error("Module did not export the required instance function");
                }
                // add the loaded module to the set
                _runtime_objects.insert(retval);
        }
        return retval->get(nullptr);
}
static Runtime& Runtime::Instance () [inline], [static]
Definition at line 155 of file Runtime.h.
        {
                static Runtime rtime;
                return rtime;
        }
bool Runtime::IsQuitting () [inline]
Gets whether DoShutdown() has been called; mostly used for threads and other sync objects to know when they should close down, or stop.
Definition at line 195 of file Runtime.h.
Referenced by IrcParser::RunParser().
        {
                return _quitting;
        }
class Log * Runtime::Logger () const
Gets the logging class.
Returns:
A pointer to the static instance within the runtime.
Definition at line 154 of file Runtime.cc.
Referenced by app_exec(), app_init(), app_stop(), Configuration::Dump(), and main().
{
        static class Log log;
        return &log;
}
Runtime::NO_CLASS_ASSIGNMENT (Runtime) [private]
only this function can expose created classes and only this function can access internals when shutting down
Runtime::NO_CLASS_COPY (Runtime) [private]
void Runtime::Report (const char *text_buffer, const char *title) const
Brings up a notification dialog for the windowing system the operating system provides.
On Windows, this calls MessageBox(), which steals focus and blocks the thread that triggered the execution. As such, should only be used when the application pause/user notification is essential, or if an error occurs that will trigger the app to be aborted anyway.
Currently no implementation on Linux/FreeBSD - investigating the best way to report a simple GUI message without having to connect to X, create atoms, etc. (and we're not using a framework for something so simple either - we're anti-bloat!)
Todo
Linux/Unix implementation
Parameters:
text_buffer The main body of the string to display
title The window title text
Definition at line 176 of file Runtime.cc.
References mb_to_utf8().
Referenced by ObjectPool< IrcUser >::ReportReferencedObject().
{
#if defined(_WIN32)
        wchar_t w_text[4096];
        wchar_t w_title[1024];
        mb_to_utf8(w_text, text_buffer, _countof(w_text));
        mb_to_utf8(w_title, title, _countof(w_title));
        ::MessageBox(GetDesktopWindow(), w_text, w_title, MB_OK);
#else
#endif
}
void Runtime::ThreadStopping (uint32_tthread_id, const char *function)
Causes the runtime to amend its _manual_threads storage - expected to be called BY the thread function, but can be executed externally if you're aware of abnormal/alternative termination.
Usually executed after breaking out of a loop, e.g. on Windows:
} // end loop/sync
runtime.ThreadStopping(GetCurrentThreadId(), __FUNCTION__);
While not mandatory to be called, on app closure the runtime will try to wait for all known threads to finish, then terminate them if they are taking too long. If the system responds to the handles in an unexpected way, this could cause a crash if this function has not been processed.
Parameters:
thread_id The ID of the executing thread that's stopping
function The name of the thread function itself
See Also:
CreateThread
Definition at line 194 of file Runtime.cc.
References _manual_threads, fg_red(), Info, and LOG.
Referenced by IrcConnection::EstablishConnection(), and IrcParser::RunParser().
{
        bool found = false;
        // search for the thread id
        for ( auto t : _manual_threads )
        {
                if ( t.thread == thread_id )
                {
                        LOG(ELogLevel::Info) << "Thread id " << thread_id << " (" << function << ") is ending execution\n";
                        _manual_threads.erase(std::find(_manual_threads.begin(), _manual_threads.end(), t));
                        found = true;
                        break;
                }
        }
        if ( !found )
        {
                std::cerr << fg_red << "The supplied thread id (" << thread_id << ") was not found in the list\n";
        }
}
void Runtime::WaitThenKillThread (uint32_tthread_id, uint32_ttimeout_ms = 1000)
Locates the supplied thread_id in the stored thread list, and if found, waits timeout_ms for it to finish before terminating it by force.
Should only be called after performing an action that would cause the thread to actually start its own cleanup routine, or just plain stop.
Primarily used for ensuring the IrcConnection class doesn't get deleted while its thread is still running, but can/will expand into other uses too.
When this function returns, the supplied thread_id is guaranteed to not exist (assuming it was spawned by our CreateThread); if it does not exist to begin with, the function returns immediately.
Parameters:
thread_id The ID of the thread to wait for
timeout_ms The time to wait in milliseconds before killing
Definition at line 223 of file Runtime.cc.
References _manual_threads, END_NAMESPACE, fg_red(), fg_yellow(), LOG, and Warn.
Referenced by IrcConnection::Cleanup(), and DoShutdown().
{
        thread_info* ti = nullptr;
        bool killed = false;
        bool success = true;
        for ( auto t : _manual_threads )
        {
#if defined(_WIN32)
                if ( t.thread == thread_id )
                {
                        ti = &t;
                        if ( t.thread_handle != nullptr && t.thread_handle != INVALID_HANDLE_VALUE )
                        {
                                DWORD exit_code = 0;
                                DWORD wait_ret;
                                wait_ret = WaitForSingleObject(t.thread_handle, timeout_ms);
                                if ( wait_ret != WAIT_OBJECT_0 || wait_ret != WAIT_TIMEOUT )
                                {
                                        if ( GetLastError() == ERROR_INVALID_HANDLE )
                                        {
                                                std::cerr << fg_red << "The thread handle " << t.thread_handle << " was reported as invalid by the system\n";
                                                // exit loop, just remove the thread_info
                                                success = false;
                                                break;
                                        }
                                }
                                if ( !GetExitCodeThread(t.thread_handle, &exit_code) || exit_code == STILL_ACTIVE )
                                {
                                        // tried to let the thread go peacefully - kill it
                                        if ( TerminateThread(t.thread_handle, EXIT_FAILURE) )
                                        {
                                                killed = true;
                                                std::cerr << fg_yellow << "Thread id " << thread_id << " has been forcibly killed after timing out\n";
                                        }
                                        else
                                        {
                                                success = false;
                                                std::cerr << fg_red << "Failed to terminate thread id " << thread_id << "; Win32 error " << GetLastError() << "\n";
                                        }
                                }
                                CloseHandle(t.thread_handle);
                        }
#else
                if ( t.thread == thread_id )
                {
                        int32_t rc;
                        timespec wait_time;
                        ti = &t;
                        wait_time.tv_nsec = (timeout_ms % 1000) * 1000000;
                        rc = pthread_timedjoin_np(t.thread, nullptr, &wait_time);
                        if ( rc == ETIMEDOUT )
                        {
                                /* tried to let the thread go peacefully - stop it */
                                pthread_cancel(t.thread);
                                /* wait again */
                                rc = pthread_timedjoin_np(t.thread, nullptr, &wait_time);
                                if ( rc == ETIMEDOUT )
                                {
                                        std::cerr << fg_yellow << "Thread " << t.thread << " has been forcibly killed after failing to finish on request\n";
                                        /* Just kill it and live with any resource leaks */
                                        pthread_kill(t.thread, SIGKILL);
                                        killed = true;
                                }
                                else if ( rc != 0 )
                                {
                                        std::cerr << fg_red << "Received errno " << rc << " after waiting for thread " << t.thread << " to finish\n";
                                }
                        }
#endif // _WIN32
                        break;
                }
        }
        /* the executing thread MUST call ThreadStopping(), in which case this
         * thread_info will have already be removed from the list, so there's
         * nothing to do.
         * If we had to kill it however, the function would never have been
         * called, so we need to remove it manually + notify */
        if ( ti != nullptr && killed )
        {
                LOG(ELogLevel::Warn) << "Thread id " << thread_id << " has been killed\n";
                _manual_threads.erase(std::find(_manual_threads.begin(), _manual_threads.end(), ti));
        }
        else if ( ti != nullptr && !success )
        {
                // not killed, waiting failed, error reported - just remove it
                _manual_threads.erase(std::find(_manual_threads.begin(), _manual_threads.end(), ti));
        }
        else
        {
                /* if the thread_info still exists, we've been told a lie, or
                * the thread function never called ThreadStopping */
                for ( auto t : _manual_threads )
                {
                        if ( t.thread == thread_id )
                        {
                                std::cerr << fg_red << "Thread id " << thread_id <<
                                        " still exists after a successful wait for the thread to finish;"
                                        " was Runtime::ThreadStopping() not executed or did the system lie?";
                                // best to remove it anyway
                                _manual_threads.erase(std::find(_manual_threads.begin(), _manual_threads.end(), t));
                                break;
                        }
                }
        }
}
Member Data Documentation
std::vector<thread_info> Runtime::_manual_threads [private]
Definition at line 137 of file Runtime.h.
Referenced by DoShutdown(), ThreadStopping(), and WaitThenKillThread().
bool Runtime::_quitting [private]
Definition at line 135 of file Runtime.h.
Referenced by DoShutdown().
std::set<runtime_object_accessor*> Runtime::_runtime_objects [private]
Definition at line 146 of file Runtime.h.
Referenced by FindModule(), and GetObjectFromModule().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.