Runtime.cc
NAME
Runtime.cc -
SYNOPSIS
#include <cassert>
#include <algorithm>
#include <Windows.h>
#include 'Runtime.h'
#include 'Allocator.h'
#include 'Log.h'
#include 'Configuration.h'
#include 'Terminal.h'
#include 'utils.h'
Macros
#define WIN32_LEAN_AND_MEAN
Variables
Runtime & runtime = Runtime::Instance()
Detailed Description
Author:
James Warren
Copyright:
James Warren, 2013-2014
License:
Zlib (see license.txt or http://opensource.org/licenses/Zlib)
Definition in file Runtime.cc.
Macro Definition Documentation
#define WIN32_LEAN_AND_MEAN
Definition at line 14 of file Runtime.cc.
Variable Documentation
Runtime& runtime = Runtime::Instance()
Definition at line 32 of file Runtime.cc.
Referenced by app_exec(), app_init(), app_stop(), IrcConnection::Cleanup(), Configuration::Dump(), IrcConnection::EstablishConnection(), IrcObject::IrcObject(), main(), ObjectPool< IrcUser >::ReportReferencedObject(), IrcParser::RunParser(), and spawn_interface().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.