.TH "Runtime.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime.h \- 
.PP
Application globally-accessible singleton\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'char_helper\&.h'\fP
.br
\fC#include 'definitions\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBthread_info\fP"
.br
.ti -1c
.RI "struct \fBruntime_object_accessor\fP"
.br
.ti -1c
.RI "class \fBRuntime\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBHANDLE\fP"
.br
.ti -1c
.RI "typedef void *(* \fBgetter\fP )(void *params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSBI_API\fP \fBRuntime\fP & \fBruntime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application globally-accessible singleton\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP
\fBTodo\fP
.RS 4
Try to think of a \fIclean\fP way to get Allocator in this file as a unique_ptr, working around the override limitations\&. Currently resides as a static member of the Memory() function as a simple but effective hack\&. Addendum: ditto for Engine, \fBPool\fP, now too! 
.RE
.PP

.PP
Definition in file \fBRuntime\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void*(* getter)(void *params)"

.PP
Definition at line 88 of file Runtime\&.h\&.
.SS "typedef void* \fBHANDLE\fP"

.PP
Definition at line 20 of file Runtime\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBSBI_API\fP \fBRuntime\fP& runtime"

.PP
Definition at line 32 of file Runtime\&.cc\&.
.PP
Referenced by app_exec(), app_init(), app_stop(), IrcConnection::Cleanup(), Configuration::Dump(), IrcConnection::EstablishConnection(), IrcObject::IrcObject(), main(), ObjectPool< IrcUser >::ReportReferencedObject(), IrcParser::RunParser(), and spawn_interface()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
