Terminal.h
NAME
Terminal.h -
Win32 console and Linux/Unix terminal colour output formatting.
SYNOPSIS
#include <iostream>
#include <iomanip>
#include <Windows.h>
#include <conio.h>
#include 'definitions.h'
#include 'types.h'
Classes
class Terminal
Macros
#define WIN32_LEAN_AND_MEAN
#define BG_MASK ( BACKGROUND_BLUE|BACKGROUND_GREEN|BACKGROUND_RED|BACKGROUND_INTENSITY )
#define FG_MASK ( FOREGROUND_BLUE|FOREGROUND_GREEN|FOREGROUND_RED|FOREGROUND_INTENSITY )
#define FG_BLACK 0
#define FG_RED FOREGROUND_RED
#define FG_GREEN FOREGROUND_GREEN
#define FG_BLUE FOREGROUND_BLUE
#define FG_CYAN (FG_GREEN|FG_BLUE)
#define FG_MAGENTA (FG_RED|FG_BLUE)
#define FG_YELLOW (FG_RED|FG_GREEN)
#define FG_WHITE (FG_RED|FG_GREEN|FG_BLUE)
#define FG_GREY (FG_BLACK|FOREGROUND_INTENSITY)
#define FG_BRIGHT_WHITE (FG_WHITE|FOREGROUND_INTENSITY)
#define FG_BRIGHT_RED (FOREGROUND_RED|FOREGROUND_INTENSITY)
#define FG_BRIGHT_GREEN (FOREGROUND_GREEN|FOREGROUND_INTENSITY)
#define FG_BRIGHT_BLUE (FOREGROUND_BLUE|FOREGROUND_INTENSITY)
#define FG_BRIGHT_CYAN (FG_GREEN|FG_BLUE|FOREGROUND_INTENSITY)
#define FG_BRIGHT_MAGENTA (FG_RED|FG_BLUE|FOREGROUND_INTENSITY)
#define FG_BRIGHT_YELLOW (FG_RED|FG_GREEN|FOREGROUND_INTENSITY)
#define BG_BLACK 0
#define BG_RED BACKGROUND_RED
#define BG_GREEN BACKGROUND_GREEN
#define BG_BLUE BACKGROUND_BLUE
#define BG_CYAN (BG_GREEN|BG_BLUE)
#define BG_MAGENTA (BG_RED|BG_BLUE)
#define BG_YELLOW (BG_RED|BG_GREEN)
#define BG_WHITE (BG_RED|BG_GREEN|BG_BLUE)
#define BG_GREY (BG_BLACK|BACKGROUND_INTENSITY)
#define BG_BRIGHT_WHITE (BG_WHITE|BACKGROUND_INTENSITY)
#define BG_BRIGHT_RED (BACKGROUND_RED|BACKGROUND_INTENSITY)
#define BG_BRIGHT_GREEN (BACKGROUND_GREEN|BACKGROUND_INTENSITY)
#define BG_BRIGHT_BLUE (BACKGROUND_BLUE|BACKGROUND_INTENSITY)
#define BG_BRIGHT_CYAN (BG_GREEN|BG_BLUE|BACKGROUND_INTENSITY)
#define BG_BRIGHT_MAGENTA (BG_RED|BG_BLUE|BACKGROUND_INTENSITY)
#define BG_BRIGHT_YELLOW (BG_RED|BG_GREEN|BACKGROUND_INTENSITY)
#define bg_default bgfg_default
#define fg_default bgfg_default
Functions
std::ostream & bg_black (std::ostream &os)
std::ostream & bg_blue (std::ostream &os)
std::ostream & bg_cyan (std::ostream &os)
std::ostream & bgfg_default (std::ostream &os)
std::ostream & bg_green (std::ostream &os)
std::ostream & bg_grey (std::ostream &os)
std::ostream & bg_magenta (std::ostream &os)
std::ostream & bg_red (std::ostream &os)
std::ostream & bg_white (std::ostream &os)
std::ostream & bg_yellow (std::ostream &os)
std::ostream & clear (std::ostream &os)
std::ostream & fg_black (std::ostream &os)
std::ostream & fg_blue (std::ostream &os)
std::ostream & fg_cyan (std::ostream &os)
std::ostream & fg_green (std::ostream &os)
std::ostream & fg_grey (std::ostream &os)
std::ostream & fg_magenta (std::ostream &os)
std::ostream & fg_red (std::ostream &os)
std::ostream & fg_white (std::ostream &os)
std::ostream & fg_yellow (std::ostream &os)
Variables
static class Terminal terminal
Detailed Description
Win32 console and Linux/Unix terminal colour output formatting.
Author:
James Warren
Todo
Win32 code complete, unix/linux needs doing
Definition in file Terminal.h.
Macro Definition Documentation
#define BG_BLACK 0
Definition at line 79 of file Terminal.h.
Referenced by bg_black().
#define BG_BLUE BACKGROUND_BLUE
Definition at line 82 of file Terminal.h.
#define BG_BRIGHT_BLUE (BACKGROUND_BLUE|BACKGROUND_INTENSITY)
Definition at line 91 of file Terminal.h.
Referenced by bg_blue().
#define BG_BRIGHT_CYAN (BG_GREEN|BG_BLUE|BACKGROUND_INTENSITY)
Definition at line 92 of file Terminal.h.
Referenced by bg_cyan().
#define BG_BRIGHT_GREEN (BACKGROUND_GREEN|BACKGROUND_INTENSITY)
Definition at line 90 of file Terminal.h.
Referenced by bg_green().
#define BG_BRIGHT_MAGENTA (BG_RED|BG_BLUE|BACKGROUND_INTENSITY)
Definition at line 93 of file Terminal.h.
Referenced by bg_magenta().
#define BG_BRIGHT_RED (BACKGROUND_RED|BACKGROUND_INTENSITY)
Definition at line 89 of file Terminal.h.
Referenced by bg_red().
#define BG_BRIGHT_WHITE (BG_WHITE|BACKGROUND_INTENSITY)
Definition at line 88 of file Terminal.h.
Referenced by bg_white().
#define BG_BRIGHT_YELLOW (BG_RED|BG_GREEN|BACKGROUND_INTENSITY)
Definition at line 94 of file Terminal.h.
Referenced by bg_yellow().
#define BG_CYAN (BG_GREEN|BG_BLUE)
Definition at line 83 of file Terminal.h.
#define bg_default bgfg_default
Definition at line 274 of file Terminal.h.
#define BG_GREEN BACKGROUND_GREEN
Definition at line 81 of file Terminal.h.
#define BG_GREY (BG_BLACK|BACKGROUND_INTENSITY)
Definition at line 87 of file Terminal.h.
Referenced by bg_grey().
#define BG_MAGENTA (BG_RED|BG_BLUE)
Definition at line 84 of file Terminal.h.
#define BG_MASK ( BACKGROUND_BLUE|BACKGROUND_GREEN|BACKGROUND_RED|BACKGROUND_INTENSITY )
Definition at line 59 of file Terminal.h.
Referenced by fg_black(), fg_blue(), fg_cyan(), fg_green(), fg_grey(), fg_magenta(), fg_red(), fg_white(), and fg_yellow().
#define BG_RED BACKGROUND_RED
Definition at line 80 of file Terminal.h.
#define BG_WHITE (BG_RED|BG_GREEN|BG_BLUE)
Definition at line 86 of file Terminal.h.
#define BG_YELLOW (BG_RED|BG_GREEN)
Definition at line 85 of file Terminal.h.
#define FG_BLACK 0
Definition at line 62 of file Terminal.h.
Referenced by fg_black().
#define FG_BLUE FOREGROUND_BLUE
Definition at line 65 of file Terminal.h.
#define FG_BRIGHT_BLUE (FOREGROUND_BLUE|FOREGROUND_INTENSITY)
Definition at line 74 of file Terminal.h.
Referenced by fg_blue().
#define FG_BRIGHT_CYAN (FG_GREEN|FG_BLUE|FOREGROUND_INTENSITY)
Definition at line 75 of file Terminal.h.
Referenced by fg_cyan().
#define FG_BRIGHT_GREEN (FOREGROUND_GREEN|FOREGROUND_INTENSITY)
Definition at line 73 of file Terminal.h.
Referenced by fg_green().
#define FG_BRIGHT_MAGENTA (FG_RED|FG_BLUE|FOREGROUND_INTENSITY)
Definition at line 76 of file Terminal.h.
Referenced by fg_magenta().
#define FG_BRIGHT_RED (FOREGROUND_RED|FOREGROUND_INTENSITY)
Definition at line 72 of file Terminal.h.
Referenced by fg_red().
#define FG_BRIGHT_WHITE (FG_WHITE|FOREGROUND_INTENSITY)
Definition at line 71 of file Terminal.h.
Referenced by fg_white().
#define FG_BRIGHT_YELLOW (FG_RED|FG_GREEN|FOREGROUND_INTENSITY)
Definition at line 77 of file Terminal.h.
Referenced by fg_yellow().
#define FG_CYAN (FG_GREEN|FG_BLUE)
Definition at line 66 of file Terminal.h.
#define fg_default bgfg_default
Definition at line 275 of file Terminal.h.
#define FG_GREEN FOREGROUND_GREEN
Definition at line 64 of file Terminal.h.
#define FG_GREY (FG_BLACK|FOREGROUND_INTENSITY)
Definition at line 70 of file Terminal.h.
Referenced by fg_grey().
#define FG_MAGENTA (FG_RED|FG_BLUE)
Definition at line 67 of file Terminal.h.
#define FG_MASK ( FOREGROUND_BLUE|FOREGROUND_GREEN|FOREGROUND_RED|FOREGROUND_INTENSITY )
Definition at line 60 of file Terminal.h.
Referenced by bg_black(), bg_blue(), bg_cyan(), bg_green(), bg_grey(), bg_magenta(), bg_red(), bg_white(), and bg_yellow().
#define FG_RED FOREGROUND_RED
Definition at line 63 of file Terminal.h.
#define FG_WHITE (FG_RED|FG_GREEN|FG_BLUE)
Definition at line 69 of file Terminal.h.
#define FG_YELLOW (FG_RED|FG_GREEN)
Definition at line 68 of file Terminal.h.
#define WIN32_LEAN_AND_MEAN
Definition at line 15 of file Terminal.h.
Function Documentation
std::ostream& bg_black (std::ostream &os) [inline]
Definition at line 280 of file Terminal.h.
References BG_BLACK, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BLACK, FG_MASK);
         return os;
}
std::ostream& bg_blue (std::ostream &os) [inline]
Definition at line 287 of file Terminal.h.
References BG_BRIGHT_BLUE, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BRIGHT_BLUE, FG_MASK);
         return os;
}
std::ostream& bg_cyan (std::ostream &os) [inline]
Definition at line 294 of file Terminal.h.
References BG_BRIGHT_CYAN, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BRIGHT_CYAN, FG_MASK);
         return os;
}
std::ostream& bg_green (std::ostream &os) [inline]
Definition at line 308 of file Terminal.h.
References BG_BRIGHT_GREEN, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BRIGHT_GREEN, FG_MASK);
         return os;
}
std::ostream& bg_grey (std::ostream &os) [inline]
Definition at line 315 of file Terminal.h.
References BG_GREY, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_GREY, FG_MASK);
         return os;
}
std::ostream& bg_magenta (std::ostream &os) [inline]
Definition at line 322 of file Terminal.h.
References BG_BRIGHT_MAGENTA, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BRIGHT_MAGENTA, FG_MASK);
         return os;
}
std::ostream& bg_red (std::ostream &os) [inline]
Definition at line 329 of file Terminal.h.
References BG_BRIGHT_RED, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BRIGHT_RED, FG_MASK);
         return os;
}
std::ostream& bg_white (std::ostream &os) [inline]
Definition at line 336 of file Terminal.h.
References BG_BRIGHT_WHITE, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BRIGHT_WHITE, FG_MASK);
         return os;
}
std::ostream& bg_yellow (std::ostream &os) [inline]
Definition at line 343 of file Terminal.h.
References BG_BRIGHT_YELLOW, FG_MASK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(BG_BRIGHT_YELLOW, FG_MASK);
         return os;
}
std::ostream& bgfg_default (std::ostream &os) [inline]
Definition at line 301 of file Terminal.h.
References Terminal::SetDefault(), and terminal.
{
         os.flush();
         terminal.SetDefault();
         return os;
}
std::ostream& clear (std::ostream &os) [inline]
Definition at line 352 of file Terminal.h.
References Terminal::Clear(), and terminal.
{
         os.flush();
         terminal.Clear();
         return os;
};
std::ostream& fg_black (std::ostream &os) [inline]
Definition at line 361 of file Terminal.h.
References BG_MASK, FG_BLACK, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(FG_BLACK, BG_MASK);
         return os;
}
std::ostream& fg_blue (std::ostream &os) [inline]
Definition at line 368 of file Terminal.h.
References BG_MASK, FG_BRIGHT_BLUE, Terminal::SetColor(), and terminal.
{
         os.flush();
         terminal.SetColor(FG_BRIGHT_BLUE, BG_MASK);
         return os;
}
std::ostream& fg_cyan (std::ostream &os) [inline]
Definition at line 375 of file Terminal.h.
References BG_MASK, FG_BRIGHT_CYAN, Terminal::SetColor(), and terminal.
Referenced by IrcEngine::NotifyNewObject(), and IrcParser::ParseNextRecvQueueItem().
{
         os.flush();
         terminal.SetColor(FG_BRIGHT_CYAN, BG_MASK);
         return os;
}
std::ostream& fg_green (std::ostream &os) [inline]
Definition at line 382 of file Terminal.h.
References BG_MASK, FG_BRIGHT_GREEN, Terminal::SetColor(), and terminal.
Referenced by host_to_ipv4().
{
         os.flush();
         terminal.SetColor(FG_BRIGHT_GREEN, BG_MASK);
         return os;
}
std::ostream& fg_grey (std::ostream &os) [inline]
Definition at line 389 of file Terminal.h.
References BG_MASK, FG_GREY, Terminal::SetColor(), and terminal.
Referenced by Configuration::CreateDefault().
{
         os.flush();
         terminal.SetColor(FG_GREY, BG_MASK);
         return os;
}
std::ostream& fg_magenta (std::ostream &os) [inline]
Definition at line 396 of file Terminal.h.
References BG_MASK, FG_BRIGHT_MAGENTA, Terminal::SetColor(), and terminal.
Referenced by IrcParser::ParseNextRecvQueueItem(), and IrcConnection::SendBypass().
{
         os.flush();
         terminal.SetColor(FG_BRIGHT_MAGENTA, BG_MASK);
         return os;
}
std::ostream& fg_red (std::ostream &os) [inline]
Definition at line 403 of file Terminal.h.
References BG_MASK, FG_BRIGHT_RED, Terminal::SetColor(), and terminal.
Referenced by IrcConnection::AddChannel(), IrcChannel::AddNamesUser(), IrcConnection::AddToRecvQueue(), IrcChannel::AddUser(), IrcConnection::AutoChangeNick(), IrcConnection::Cleanup(), IrcParser::Cleanup(), Configuration::CreateDefault(), IrcFactory::DeleteIrcObject(), IrcChannel::DeleteUser(), IrcParser::ExtractIrcBufData(), Log::Flush(), IrcParser::Handle001(), IrcParser::Handle002(), IrcParser::Handle005(), IrcParser::Handle333(), IrcParser::Handle353(), IrcParser::Handle366(), IrcParser::HandleCap(), IrcParser::HandleKick(), IrcParser::HandleKill(), IrcParser::HandleMode(), IrcParser::HandlePrivmsg(), IrcParser::HandleQuit(), IrcParser::HandleTopic(), IrcParser::HasChannelPrefix(), host_to_ipv4(), ipv4_to_host(), IrcParser::IrcParser(), IrcParser::ModeHasArgument(), net_startup(), IrcEngine::NotifyListeners(), Log::Open(), IrcParser::ParseConnectionQueues(), IrcParser::ParseNextRecvQueueItem(), IrcParser::ParseParam(), IrcParser::ParseParameters(), IrcParser::ProcessNextSendQueueItem(), IrcParser::RunParser(), IrcNetwork::Setup(), IrcParser::SplitSender(), Runtime::ThreadStopping(), IrcParser::TriggerSync(), IrcNetwork::UpdateServerInfo(), and Runtime::WaitThenKillThread().
{
         os.flush();
         terminal.SetColor(FG_BRIGHT_RED, BG_MASK);
         return os;
}
std::ostream& fg_white (std::ostream &os) [inline]
Definition at line 410 of file Terminal.h.
References BG_MASK, FG_BRIGHT_WHITE, Terminal::SetColor(), and terminal.
Referenced by IrcEngine::NotifyNewObject(), and IrcParser::ParseNextRecvQueueItem().
{
         os.flush();
         terminal.SetColor(FG_BRIGHT_WHITE, BG_MASK);
         return os;
}
std::ostream& fg_yellow (std::ostream &os) [inline]
Definition at line 417 of file Terminal.h.
References BG_MASK, FG_BRIGHT_YELLOW, Terminal::SetColor(), and terminal.
Referenced by Runtime::WaitThenKillThread().
{
         os.flush();
         terminal.SetColor(FG_BRIGHT_YELLOW, BG_MASK);
         return os;
}
Variable Documentation
class Terminal terminal [static]
Referenced by bg_black(), bg_blue(), bg_cyan(), bg_green(), bg_grey(), bg_magenta(), bg_red(), bg_white(), bg_yellow(), bgfg_default(), clear(), fg_black(), fg_blue(), fg_cyan(), fg_green(), fg_grey(), fg_magenta(), fg_red(), fg_white(), and fg_yellow().
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.