Terminal
NAME
Terminal -
SYNOPSIS
#include <Terminal.h>
Public Member Functions
Terminal ()
void Clear ()
char GetCharacter ()
void SetColor (uint16_t rgb, uint16_t mask)
void SetDefault ()
Private Member Functions
void InternalUpdate ()
Private Attributes
HANDLE _console
DWORD _written
uint32_t _size
uint16_t _default_attrib
CONSOLE_SCREEN_BUFFER_INFO _csbi
Detailed Description
Console/Terminal output support for streaming colours into standard ostreams.
Enables changing colours like:
std::cout << fg_white << "White Foreground, " << bg_cyan << "Cyan Background\n";
Significantly more legible than outputting, call colour change function, output again, repeat, etc.
Callers within this application should not assume the result of a prior call (i.e. any colour could be fg/bg) - you should always set the desired colours on invocation.
We use SetColor instead of 'real' English as more people tend to understand or expect the US version of the spelling.
Since Windows and Linux/Unix command-lines differ so much, each class declaration is contained in its own if preprocessor block.
Definition at line 54 of file Terminal.h.
Constructor & Destructor Documentation
Terminal::Terminal () [inline]
Definition at line 111 of file Terminal.h.
        {
                _console = GetStdHandle(STD_OUTPUT_HANDLE);
                GetConsoleScreenBufferInfo(_console, &_csbi);
                _default_attrib = _csbi.wAttributes;
        }
Member Function Documentation
void Terminal::Clear () [inline]
Definition at line 120 of file Terminal.h.
Referenced by clear().
        {
                COORD coordScreen = { 0, 0 };
                InternalUpdate();
                FillConsoleOutputCharacter(_console, ' ', _size,
                        coordScreen, &_written);
                InternalUpdate();
                FillConsoleOutputAttribute(_console, _csbi.wAttributes,
                        _size, coordScreen, &_written);
                SetConsoleCursorPosition(_console, coordScreen);
        }
char Terminal::GetCharacter () [inline]
Definition at line 135 of file Terminal.h.
        {
                while ( !_kbhit() )
                {
                        return (char)_getch();
                }
        }
void Terminal::InternalUpdate () [inline], [private]
Definition at line 104 of file Terminal.h.
        {
                GetConsoleScreenBufferInfo(_console, &_csbi);
                _size = _csbi.dwSize.X * _csbi.dwSize.Y;
        }
void Terminal::SetColor (uint16_trgb, uint16_tmask) [inline]
Definition at line 145 of file Terminal.h.
Referenced by bg_black(), bg_blue(), bg_cyan(), bg_green(), bg_grey(), bg_magenta(), bg_red(), bg_white(), bg_yellow(), fg_black(), fg_blue(), fg_cyan(), fg_green(), fg_grey(), fg_magenta(), fg_red(), fg_white(), and fg_yellow().
        {
                InternalUpdate();
                _csbi.wAttributes &= mask;
                _csbi.wAttributes |= rgb;
                SetConsoleTextAttribute(_console, _csbi.wAttributes);
        }
void Terminal::SetDefault () [inline]
Definition at line 158 of file Terminal.h.
Referenced by bgfg_default().
        {
                _csbi.wAttributes = _default_attrib;
                SetConsoleTextAttribute(_console, _csbi.wAttributes);
        }
Member Data Documentation
HANDLE Terminal::_console [private]
Definition at line 97 of file Terminal.h.
CONSOLE_SCREEN_BUFFER_INFO Terminal::_csbi [private]
Definition at line 101 of file Terminal.h.
uint16_t Terminal::_default_attrib [private]
Definition at line 100 of file Terminal.h.
uint32_t Terminal::_size [private]
Definition at line 99 of file Terminal.h.
DWORD Terminal::_written [private]
Definition at line 98 of file Terminal.h.
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.