.TH "types.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
types.h \- 
.PP
Defines the platform data types for the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'compiler\&.h'\fP
.br
\fC#include 'definitions\&.h'\fP
.br
\fC#include <cstdint>\fP
.br

.SH "Detailed Description"
.PP 
Defines the platform data types for the application\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBtypes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
