.TH "user_modes_change" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_modes_change \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <irc_structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBbefore\fP"
.br
.ti -1c
.RI "uint16_t \fBafter\fP"
.br
.ti -1c
.RI "const \fBmode_update\fP * \fBmu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 152 of file irc_structs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t user_modes_change::after"

.PP
Definition at line 155 of file irc_structs\&.h\&.
.SS "uint16_t user_modes_change::before"

.PP
Definition at line 154 of file irc_structs\&.h\&.
.SS "const \fBmode_update\fP * user_modes_change::mu"

.PP
Definition at line 156 of file irc_structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
