utils.cc
NAME
utils.cc -
SYNOPSIS
#include <cstring>
#include <cstdarg>
#include <cstdio>
#include <ctype.h>
#include <cstdlib>
#include <Windows.h>
#include 'utils.h'
Functions
std::string build_string (int16_t num_args,...)
uint64_t get_ms_time ()
CHARSTRINGTYPE mbstr_to_chartypestr (std::string &src)
char * skip_whitespace (char *str)
uint32_t strlcat (char *dest, const char *src, uint32_t dest_size)
uint32_t strlcpy (char *dest, const char *src, uint32_t dest_size)
uint32_t str_format (char *destination, uint32_t dest_size, char *format,...)
char * str_token (char *src, const char *delim, char **context)
char * str_trim (char *src)
Detailed Description
Author:
James Warren
Copyright:
James Warren, 2014
License:
Zlib (see license.txt or http://opensource.org/licenses/Zlib)
Definition in file utils.cc.
Function Documentation
std::string build_string (int16_tnum_args, ...)
Creates a std::string from any supplied parameters.
Much easier than putting a bunch of individual line appends or having to stream it; works with input of std::string, char*, etc. - anything a normal std::string assignment is capable of.
Originally created so we could have a one-liner for std::runtime_error.
Warning:
Use the BUILD_STRING macro; this handles the automatic argument count, so changes won't result in the counter being incorrect
Return values:
std::string
Definition at line 31 of file utils.cc.
{
        std::string ret_str;
        va_list args;
        va_start(args, num_args);
        while ( num_args-- >= 0 )
        {
                ret_str.append((char*)va_arg(args, char*));
        }
        va_end(args);
        return ret_str;
}
uint64_t get_ms_time ()
Gets the current time in milliseconds.
Used for timing operations - store the first call to this as a start_time, and then use the second call to determine the duration.
Returns:
Returns the number of milliseconds since January 1, 1601 (UTC).
Definition at line 106 of file utils.cc.
Referenced by app_exec(), and app_init().
{
#if defined(_WIN32)
        FILETIME ft;
        LARGE_INTEGER li;
        /* Get the amount of 100 nano seconds intervals elapsed since January 1,
         * 1601 (UTC) and copy it to a LARGE_INTEGER structure. */
        GetSystemTimeAsFileTime(&ft);
        li.LowPart = ft.dwLowDateTime;
        li.HighPart = ft.dwHighDateTime;
        uint64_t ret = li.QuadPart;
        ret -= 116444736000000000LL; /* Convert from file time to UNIX epoch time. */
        ret /= 10000; /* From 100 nano seconds (10^-7) to 1 millisecond (10^-3) intervals */
        return ret;
#else
        struct timeval tv;
        gettimeofday(&tv, NULL);
        uint64_t ret = tv.tv_usec;
        /* Convert from micro seconds (10^-6) to milliseconds (10^-3) */
        ret /= 1000;
        /* Adds the seconds (10^0) after converting them to milliseconds (10^-3) */
        ret += (tv.tv_sec * 1000);
        return ret;
#endif
}
CHARSTRINGTYPE mbstr_to_chartypestr (std::string &src)
Takes the input std::string and converts it to the platform type string. Just a helper to prevent code/preprocessor spam when dealing with Win32 vs *nix builds.
Where CHARSTRINGTYPE == std::string, this function performs no modifications.
Returns:
Returns the input string as the platform type specific string, converting where needed.
Definition at line 142 of file utils.cc.
References mb_to_utf8().
{
#if defined(_WIN32)
        CHARTYPE x[4096];
        CHARSTRINGTYPE ret;
        mb_to_utf8(x, src.c_str(), _countof(x));
        ret = x;
        return ret;
#else
        return src;
#endif
}
char* skip_whitespace (char *str)
Definition at line 161 of file utils.cc.
Referenced by str_trim().
{
        while ( isspace(*str) )
                ++str;
        return str;
}
uint32_t str_format (char *dest, uint32_tdest_size, char *format, ...)
Formats a string into the buffer specified by dest.
This function is identical to snprintf, only there is no need to concern with the buffer size. Nul-termination is guaranteed if dest_size is at least 1. Improper use of format strings can still result in security risks, so always use as much safety as you would to normal statements.
char buf[24]; int32_t num = 5; str_format('The integer is: %i; amazing stuff!\\n'), num);
In this case, the string is truncated to 'The integer is: 5; amaz'.
Parameters:
dest The buffer to store the formatted string in
dest_size The size of the destination buffer
format The format of the input string
... Variable arguments for the format string
Returns:
Returns 0 if any parameter is incorrect, or of not great enough size, or 'format' is null or less than 2 characters in length.
Returns the number of characters (excluding the nul), or -1 (SIZE_MAX) if the text was truncated to fit in the buffer.
Definition at line 252 of file utils.cc.
Referenced by Configuration::LoadUI(), ObjectPool< IrcUser >::ReportReferencedObject(), IrcConnection::SendAway(), IrcConnection::SendCTCP(), IrcConnection::SendCTCPNotice(), IrcConnection::SendIdentify(), IrcConnection::SendInvite(), IrcConnection::SendJoin(), IrcConnection::SendKick(), IrcConnection::SendMode(), IrcConnection::SendNick(), IrcConnection::SendNotice(), IrcConnection::SendPart(), IrcConnection::SendPrivmsg(), IrcConnection::SendQuit(), IrcConnection::SendTopic(), IrcConnection::SendUser(), and IrcConnection::Setup().
{
        int32_t res = 0;
        va_list varg;
        if ( destination == nullptr )
                return 0;
        if ( format == nullptr )
                return 0;
        if ( dest_size <= 1 )
                return 0;
        va_start(varg, format);
#if MSVC_IS_VS8_OR_LATER
# pragma warning ( push )
# pragma warning ( disable : 4996 ) // vsnprintf - unsafe function
#endif
        /* always leave 1 for the nul terminator - this is the security complaint
         * that visual studio will warn us about. Since we have coded round it,
         * forcing each instance to include '-1' with a min 'dest_size' of 1, this
         * is perfectly safe. */
        res = vsnprintf(destination, (dest_size - 1), format, varg);
#if MSVC_IS_VS8_OR_LATER
# pragma warning ( pop )
#endif
        va_end(varg);
        if ( res == -1 )
        {
                // destination text has been truncated/error
                destination[dest_size - 1] = '\0';
                return 0;
        }
        else
        {
                // to ensure nul-termination
                destination[res] = '\0';
        }
        // will be positive as not an error
        return (uint32_t) res;
}
char* str_token (char *src, const char *delim, char **context)
Equivalent of strtok_r, cross-platform.
Definition at line 306 of file utils.cc.
Referenced by IrcConnection::EstablishConnection(), IrcParser::Handle005(), IrcParser::Handle353(), and IrcParser::HandleMode().
{
        char* ret = nullptr;
        if ( src == nullptr )
        {
                src = *context;
        }
        // skip leading delimiters
        while ( *src && strchr(delim, *src) )
        {
                ++src;
        }
        if ( *src == '\0' )
                return ret;
        ret = src;
        // break on end of string or upon finding a delimiter
        while ( *src && !strchr(delim, *src) )
        {
                ++src;
        }
        // if a delimiter was found, nul it
        if ( *src )
        {
                *src++ = '\0';
        }
        *context = src;
        return ret;
}
char* str_trim (char *src)
Definition at line 350 of file utils.cc.
References skip_whitespace().
{
        size_t len;
        char* e;
        if ( src == nullptr )
                return nullptr;
        src = skip_whitespace(src);
        len = strlen(src);
        if ( !len )
                return src;
        e = src + len - 1;
        while ( e >= src && isspace(*e) )
                e--;
        *(e + 1) = '\0';
        return src;
}
uint32_t strlcat (char *dest, const char *src, uint32_tdest_size)
Appends src into the buffer specified by dest, up to a limit of size
1. nul termination is guaranteed if size is at least 1 - unlike the OpenBSD version of strlcat, if no nul is found in dest, it is inserted at the final position. This is a change for tiny safety sake.
Is an exact match of the OpenBSD strlcat.
Parameters:
dest The destination buffer
src The string to append
dest_size The size of the destination buffer
Returns:
The length of the string that was attempted to be created. So, strlen of dest + strlen of src. If this is greater than or equal to size, truncation has occurred, and should be handled by the caller.
Definition at line 174 of file utils.cc.
Referenced by IrcConnection::EstablishConnection(), and IrcConnection::SendInit().
{
        register char* d = dest;
        register const char* s = src;
        register uint32_t n = dest_size;
        uint32_t len;
        // Find the end of dst and adjust bytes left but don't go past end
        while ( *d != '\0' && n-- != 0 )
                d++;
        len = d - dest;
        n = dest_size - len;
        if ( n == 0 )
                return (len + strlen(s));
        while ( *s != '\0' )
        {
                if ( n != 1 )
                {
                        *d++ = *s;
                        n--;
                }
                s++;
        }
        *d = '\0';
        // count does not include NUL
        return (len + (s - src));
}
uint32_t strlcpy (char *dest, const char *src, uint32_tdest_size)
Copies src into the buffer specified by dest, up to a limit of size
1. Always starts copying src and overwrites anything previously there. nul termination is guaranteed if size is at least 1.
Is an exact match of the OpenBSD strlcpy.
Parameters:
dest The destination buffer
src The string to copy
dest_size The size of the destination buffer
Returns:
The length of the string that was attempted to be created. So, strlen of src. If this is greater than or equal to size, truncation has occurred, and should be handled by the caller.
Definition at line 214 of file utils.cc.
Referenced by IrcConnection::EstablishConnection(), ObjectPool< IrcUser >::Get(), ObjectPool< IrcUser >::GetObject(), Runtime::GetObjectFromModule(), IrcParser::Handle005(), host_to_ipv4(), IrcParser::ParseParameters(), IrcConnection::SendInit(), and IrcConnection::SendQuit().
{
        register char* d = dest;
        register const char* s = src;
        register uint32_t n = dest_size;
        // Copy as many bytes as will fit
        if ( n != 0 && --n != 0 )
        {
                do
                {
                        if ( (*d++ = *s++) == 0 )
                                break;
                } while ( --n != 0 );
        }
        // Not enough room in dest, add NUL and traverse rest of src
        if ( n == 0 )
        {
                if ( dest_size != 0 )
                {
                        // nul-terminate dest
                        *d = '\0';
                }
                while ( *s++ );
        }
        // count does not include NUL
        return (s - src - 1);
}
Author
Generated automatically by Doxygen for Social Bot Interface from the source code.