.TH "version.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
version.h \- 
.PP
Application and API versions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'definitions\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAPPLICATION_VERSION_MAJOR\fP   0"
.br
.ti -1c
.RI "#define \fBAPPLICATION_VERSION_MINOR\fP   1"
.br
.ti -1c
.RI "#define \fBAPPLICATION_VERSION_REVISION\fP   1"
.br
.ti -1c
.RI "#define \fBAPPLICATION_VERSION_BUILD\fP   0"
.br
.ti -1c
.RI "#define \fBAPPLICATION_VERSION_STR\fP"
.br
.ti -1c
.RI "#define \fBAPPLICATION_VERSION_DATETIME\fP   ' (' __DATE__ ', ' __TIME__ ')'"
.br
.ti -1c
.RI "#define \fBAPI_VERSION_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBAPI_VERSION_MINOR\fP   0"
.br
.ti -1c
.RI "#define \fBAPI_VERSION_REVISION\fP   0"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBAPPLICATION_VERSION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application and API versions\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBversion\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define API_VERSION_MAJOR   1"

.PP
Definition at line 55 of file version\&.h\&.
.SS "#define API_VERSION_MINOR   0"

.PP
Definition at line 56 of file version\&.h\&.
.SS "#define API_VERSION_REVISION   0"

.PP
Definition at line 57 of file version\&.h\&.
.SS "#define APPLICATION_VERSION_BUILD   0"

.PP
Definition at line 25 of file version\&.h\&.
.SS "#define APPLICATION_VERSION_DATETIME   ' (' __DATE__ ', ' __TIME__ ')'"

.PP
Definition at line 40 of file version\&.h\&.
.SS "#define APPLICATION_VERSION_MAJOR   0"

.PP
Definition at line 16 of file version\&.h\&.
.SS "#define APPLICATION_VERSION_MINOR   1"

.PP
Definition at line 19 of file version\&.h\&.
.SS "#define APPLICATION_VERSION_REVISION   1"

.PP
Definition at line 22 of file version\&.h\&.
.SS "#define APPLICATION_VERSION_STR"
\fBValue:\fP
.PP
.nf
STRINGIFY(APPLICATION_VERSION_MAJOR)      \
        "\&." STRINGIFY(APPLICATION_VERSION_MINOR) \
        "\&." STRINGIFY(APPLICATION_VERSION_REVISION)      \
        "\&." STRINGIFY(APPLICATION_VERSION_BUILD)
.fi
.PP
Definition at line 34 of file version\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const int APPLICATION_VERSION\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
          1000000 * APPLICATION_VERSION_MAJOR
        +   10000 * APPLICATION_VERSION_MINOR
        +     100 * APPLICATION_VERSION_REVISION
        +       1 * APPLICATION_VERSION_BUILD
.fi
.PP
Definition at line 28 of file version\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
