.TH "win32.h" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
win32.h \- 
.PP
Win32 specific module functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBinstance\fP (void *params)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Win32 specific module functionality\&. 


.PP
\fBAuthor:\fP
.RS 4
James Warren 
.RE
.PP

.PP
Definition in file \fBwin32\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void* instance (void *params)"
Returns a pointer to the interface instance\&. Return type must be void as the api/runtime cannot know what object the instance will be, since it's compiled with no knowledge of the interface\&.
.PP
\fBWarning:\fP
.RS 4
Assumes \fBspawn_interface()\fP has been called before now as part of the loading procedure, which creates the object this refers to\&. Third-party interfaces can do this however they want, but is useful to know what to expect\&. 
.RE
.PP

.PP
Definition at line 35 of file interface\&.cc\&.
.PP
References APP_NAMESPACE, and irc_engine\&.
.PP
.nf
38 {
39         // unused
40         params;
41 
42         return irc_engine\&.get();
43 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Social Bot Interface from the source code\&.
