.TH "irc.bak Directory Reference" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc.bak Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbak/config_structs\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/irc_channel_modes\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/irc_structs\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/irc_user_modes\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcChannel\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcChannel\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcConnection\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcConnection\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/ircd_bahamut\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/ircd_ngircd\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcEngine\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcEngine\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcFactory\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcFactory\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcListener\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcNetwork\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcNetwork\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcObject\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcObject\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcParser\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcParser\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcPool\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcPool\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/IrcUser\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/IrcUser\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/live_structs\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/nethelper\&.cc\fP"
.br
.ti -1c
.RI "file \fBbak/nethelper\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/rfc1459\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/rfc2812\&.h\fP"
.br
.ti -1c
.RI "file \fBbak/win32\&.cc\fP"
.br
.ti -1c
.RI "file \fBwin32\&.h\fP"
.br
.RI "\fIWin32 specific module functionality\&. \fP"
.in -1c
