.TH "sbi Directory Reference" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sbi Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapp\&.cc\fP"
.br
.ti -1c
.RI "file \fBapp\&.h\fP"
.br
.RI "\fIApplication initialization, execution, and cleanup routines\&. \fP"
.ti -1c
.RI "file \fBgetopt\&.cc\fP"
.br
.ti -1c
.RI "file \fBgetopt\&.h\fP"
.br
.RI "\fIWin32 version of *nix getopt for parsing command line options\&. \fP"
.ti -1c
.RI "file \fBmain\&.cc\fP"
.br
.in -1c
