.TH "api Directory Reference" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAllocator\&.cc\fP"
.br
.ti -1c
.RI "file \fBAllocator\&.h\fP"
.br
.RI "\fIMemory Allocation tracking for the application\&. \fP"
.ti -1c
.RI "file \fBchar_helper\&.h\fP"
.br
.RI "\fICross-platform string conversion helper (mostly for Windows) \fP"
.ti -1c
.RI "file \fBcompiler\&.h\fP"
.br
.RI "\fISupported compiler macros, definitions and functionality\&. \fP"
.ti -1c
.RI "file \fBConfiguration\&.cc\fP"
.br
.ti -1c
.RI "file \fBConfiguration\&.h\fP"
.br
.RI "\fIThe application configuration\&. \fP"
.ti -1c
.RI "file \fBcrash_handler\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrash_handler\&.h\fP"
.br
.RI "\fIApplication crash handling\&. \fP"
.ti -1c
.RI "file \fBdefinitions\&.h\fP"
.br
.RI "\fICommon definitions and helper macros\&. \fP"
.ti -1c
.RI "file \fBinterface_status\&.h\fP"
.br
.RI "\fIInterface library status codes\&. \fP"
.ti -1c
.RI "file \fBLog\&.cc\fP"
.br
.ti -1c
.RI "file \fBLog\&.h\fP"
.br
.RI "\fI\fBLog\fP file writing for the application\&. \fP"
.ti -1c
.RI "file \fBmodules\&.h\fP"
.br
.RI "\fIPlugins/modules components\&. \fP"
.ti -1c
.RI "file \fBRuntime\&.cc\fP"
.br
.ti -1c
.RI "file \fBRuntime\&.h\fP"
.br
.RI "\fIApplication globally-accessible singleton\&. \fP"
.ti -1c
.RI "file \fBTerminal\&.h\fP"
.br
.RI "\fIWin32 console and Linux/Unix terminal colour output formatting\&. \fP"
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.RI "\fIDefines the platform data types for the application\&. \fP"
.ti -1c
.RI "file \fButils\&.cc\fP"
.br
.ti -1c
.RI "file \fButils\&.h\fP"
.br
.RI "\fIConsistent secure string & utility functionality, multi-platform\&. \fP"
.ti -1c
.RI "file \fButils_linux\&.cc\fP"
.br
.ti -1c
.RI "file \fButils_linux\&.h\fP"
.br
.RI "\fILinux-specific utility functions\&. \fP"
.ti -1c
.RI "file \fButils_win\&.cc\fP"
.br
.ti -1c
.RI "file \fButils_win\&.h\fP"
.br
.RI "\fIWindows-specific utility functions\&. \fP"
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.RI "\fIApplication and API versions\&. \fP"
.in -1c
