.TH "Qt5GUI Directory Reference" 3 "Mon Jun 23 2014" "Version 0.1" "Social Bot Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Qt5GUI Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgenerated\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAboutDialog\&.cc\fP"
.br
.ti -1c
.RI "file \fBAboutDialog\&.h\fP"
.br
.RI "\fIQt5GUI 'About' dialog\&. \fP"
.ti -1c
.RI "file \fBInterfacesLoadDialog\&.h\fP"
.br
.RI "\fIQt5GUI 'Load Interface' dialog\&. \fP"
.ti -1c
.RI "file \fBInterfacesUnloadDialog\&.h\fP"
.br
.RI "\fIQt5GUI 'Unload Interface' dialog\&. \fP"
.ti -1c
.RI "file \fBlibrary\&.cc\fP"
.br
.ti -1c
.RI "file \fBlibrary\&.h\fP"
.br
.RI "\fIQt5GUI library core components for execution\&. \fP"
.ti -1c
.RI "file \fBModulesLoadDialog\&.h\fP"
.br
.RI "\fIQt5GUI 'Load Module' dialog\&. \fP"
.ti -1c
.RI "file \fBModulesUnloadDialog\&.h\fP"
.br
.RI "\fIQt5GUI 'Unload Module' dialog\&. \fP"
.ti -1c
.RI "file \fBUI\&.cc\fP"
.br
.ti -1c
.RI "file \fBUI\&.h\fP"
.br
.RI "\fIQt5GUI root\&. \fP"
.in -1c
