#pragma once

/*-----------------------------------------------------------------------------
 * auto generated by build tool - all changes will be overwritten on build
 *----------------------------------------------------------------------------*/

// sets up compiler definitions needed before our own headers; no dependencies
#include <api/compiler.h>

// uses libconfig as the configuration library
#define USING_LIBCONFIG

// uses Boost as the networking library
#define USING_BOOST_NET

// debug build
#define _DEBUG 1

/*-----------------------------------------------------------------------------
 * definition conflict checker
 *----------------------------------------------------------------------------*/

#if defined(USING_BOOST_NET) && defined(USING_OPENSSL_NET)
#	error "Boost and OpenSSL Net libraries enabled; only 1 can be used at a time"
#endif
#if defined(USING_LIBCONFIG) && defined(USING_JSON_CONFIG)
#	error "libconfig and JSON config libraries enabled; only 1 can be used at a time"
#endif

